// Code generated by Kitex v0.15.2. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sdkws "github.com/rhp-QE/roc-im-server/kitex_gen/sdkws"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BatchSendMessage(ctx context.Context, Req *sdkws.BatchSendMessageRequest, callOptions ...callopt.Option) (r *sdkws.BatchSendMessageResponse, err error)
	FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListRequest, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResponse, err error)
	BatchGetMessages(ctx context.Context, Req *sdkws.BatchGetMessagesRequest, callOptions ...callopt.Option) (r *sdkws.BatchGetMessagesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) BatchSendMessage(ctx context.Context, Req *sdkws.BatchSendMessageRequest, callOptions ...callopt.Option) (r *sdkws.BatchSendMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchSendMessage(ctx, Req)
}

func (p *kMessageServiceClient) FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListRequest, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchConvMessageList(ctx, Req)
}

func (p *kMessageServiceClient) BatchGetMessages(ctx context.Context, Req *sdkws.BatchGetMessagesRequest, callOptions ...callopt.Option) (r *sdkws.BatchGetMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetMessages(ctx, Req)
}
