// Code generated by Kitex v0.15.2. DO NOT EDIT.

package messageservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	message "github.com/rhp-QE/roc-im-server/kitex_gen/message"
	sdkws "github.com/rhp-QE/roc-im-server/kitex_gen/sdkws"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"BatchSendMessage": kitex.NewMethodInfo(
		batchSendMessageHandler,
		newBatchSendMessageArgs,
		newBatchSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchChangeMessages": kitex.NewMethodInfo(
		batchChangeMessagesHandler,
		newBatchChangeMessagesArgs,
		newBatchChangeMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FetchConvMessageList": kitex.NewMethodInfo(
		fetchConvMessageListHandler,
		newFetchConvMessageListArgs,
		newFetchConvMessageListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGetMessages": kitex.NewMethodInfo(
		batchGetMessagesHandler,
		newBatchGetMessagesArgs,
		newBatchGetMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	messageServiceServiceInfo                = NewServiceInfo()
	messageServiceServiceInfoForClient       = NewServiceInfoForClient()
	messageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return messageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return messageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func batchSendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.BatchSendMessageRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(message.MessageService).BatchSendMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchSendMessageArgs:
		success, err := handler.(message.MessageService).BatchSendMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchSendMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchSendMessageArgs() interface{} {
	return &BatchSendMessageArgs{}
}

func newBatchSendMessageResult() interface{} {
	return &BatchSendMessageResult{}
}

type BatchSendMessageArgs struct {
	Req *sdkws.BatchSendMessageRequest
}

func (p *BatchSendMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchSendMessageArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchSendMessageRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchSendMessageArgs_Req_DEFAULT *sdkws.BatchSendMessageRequest

func (p *BatchSendMessageArgs) GetReq() *sdkws.BatchSendMessageRequest {
	if !p.IsSetReq() {
		return BatchSendMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchSendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchSendMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchSendMessageResult struct {
	Success *sdkws.BatchSendMessageResponse
}

var BatchSendMessageResult_Success_DEFAULT *sdkws.BatchSendMessageResponse

func (p *BatchSendMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchSendMessageResult) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchSendMessageResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchSendMessageResult) GetSuccess() *sdkws.BatchSendMessageResponse {
	if !p.IsSetSuccess() {
		return BatchSendMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchSendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.BatchSendMessageResponse)
}

func (p *BatchSendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchSendMessageResult) GetResult() interface{} {
	return p.Success
}

func batchChangeMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.BatchChangeMessagesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(message.MessageService).BatchChangeMessages(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchChangeMessagesArgs:
		success, err := handler.(message.MessageService).BatchChangeMessages(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchChangeMessagesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchChangeMessagesArgs() interface{} {
	return &BatchChangeMessagesArgs{}
}

func newBatchChangeMessagesResult() interface{} {
	return &BatchChangeMessagesResult{}
}

type BatchChangeMessagesArgs struct {
	Req *sdkws.BatchChangeMessagesRequest
}

func (p *BatchChangeMessagesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchChangeMessagesArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchChangeMessagesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchChangeMessagesArgs_Req_DEFAULT *sdkws.BatchChangeMessagesRequest

func (p *BatchChangeMessagesArgs) GetReq() *sdkws.BatchChangeMessagesRequest {
	if !p.IsSetReq() {
		return BatchChangeMessagesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchChangeMessagesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchChangeMessagesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchChangeMessagesResult struct {
	Success *sdkws.BatchChangeMessagesResponse
}

var BatchChangeMessagesResult_Success_DEFAULT *sdkws.BatchChangeMessagesResponse

func (p *BatchChangeMessagesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchChangeMessagesResult) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchChangeMessagesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchChangeMessagesResult) GetSuccess() *sdkws.BatchChangeMessagesResponse {
	if !p.IsSetSuccess() {
		return BatchChangeMessagesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchChangeMessagesResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.BatchChangeMessagesResponse)
}

func (p *BatchChangeMessagesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchChangeMessagesResult) GetResult() interface{} {
	return p.Success
}

func fetchConvMessageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchConvMessageListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(message.MessageService).FetchConvMessageList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchConvMessageListArgs:
		success, err := handler.(message.MessageService).FetchConvMessageList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchConvMessageListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchConvMessageListArgs() interface{} {
	return &FetchConvMessageListArgs{}
}

func newFetchConvMessageListResult() interface{} {
	return &FetchConvMessageListResult{}
}

type FetchConvMessageListArgs struct {
	Req *sdkws.FetchConvMessageListRequest
}

func (p *FetchConvMessageListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchConvMessageListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchConvMessageListArgs_Req_DEFAULT *sdkws.FetchConvMessageListRequest

func (p *FetchConvMessageListArgs) GetReq() *sdkws.FetchConvMessageListRequest {
	if !p.IsSetReq() {
		return FetchConvMessageListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchConvMessageListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchConvMessageListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchConvMessageListResult struct {
	Success *sdkws.FetchConvMessageListResponse
}

var FetchConvMessageListResult_Success_DEFAULT *sdkws.FetchConvMessageListResponse

func (p *FetchConvMessageListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchConvMessageListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchConvMessageListResult) GetSuccess() *sdkws.FetchConvMessageListResponse {
	if !p.IsSetSuccess() {
		return FetchConvMessageListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchConvMessageListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchConvMessageListResponse)
}

func (p *FetchConvMessageListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchConvMessageListResult) GetResult() interface{} {
	return p.Success
}

func batchGetMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.BatchGetMessagesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(message.MessageService).BatchGetMessages(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetMessagesArgs:
		success, err := handler.(message.MessageService).BatchGetMessages(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetMessagesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetMessagesArgs() interface{} {
	return &BatchGetMessagesArgs{}
}

func newBatchGetMessagesResult() interface{} {
	return &BatchGetMessagesResult{}
}

type BatchGetMessagesArgs struct {
	Req *sdkws.BatchGetMessagesRequest
}

func (p *BatchGetMessagesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetMessagesArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchGetMessagesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetMessagesArgs_Req_DEFAULT *sdkws.BatchGetMessagesRequest

func (p *BatchGetMessagesArgs) GetReq() *sdkws.BatchGetMessagesRequest {
	if !p.IsSetReq() {
		return BatchGetMessagesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetMessagesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetMessagesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetMessagesResult struct {
	Success *sdkws.BatchGetMessagesResponse
}

var BatchGetMessagesResult_Success_DEFAULT *sdkws.BatchGetMessagesResponse

func (p *BatchGetMessagesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetMessagesResult) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchGetMessagesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetMessagesResult) GetSuccess() *sdkws.BatchGetMessagesResponse {
	if !p.IsSetSuccess() {
		return BatchGetMessagesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetMessagesResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.BatchGetMessagesResponse)
}

func (p *BatchGetMessagesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetMessagesResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) BatchSendMessage(ctx context.Context, Req *sdkws.BatchSendMessageRequest) (r *sdkws.BatchSendMessageResponse, err error) {
	var _args BatchSendMessageArgs
	_args.Req = Req
	var _result BatchSendMessageResult
	if err = p.c.Call(ctx, "BatchSendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchChangeMessages(ctx context.Context, Req *sdkws.BatchChangeMessagesRequest) (r *sdkws.BatchChangeMessagesResponse, err error) {
	var _args BatchChangeMessagesArgs
	_args.Req = Req
	var _result BatchChangeMessagesResult
	if err = p.c.Call(ctx, "BatchChangeMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListRequest) (r *sdkws.FetchConvMessageListResponse, err error) {
	var _args FetchConvMessageListArgs
	_args.Req = Req
	var _result FetchConvMessageListResult
	if err = p.c.Call(ctx, "FetchConvMessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetMessages(ctx context.Context, Req *sdkws.BatchGetMessagesRequest) (r *sdkws.BatchGetMessagesResponse, err error) {
	var _args BatchGetMessagesArgs
	_args.Req = Req
	var _result BatchGetMessagesResult
	if err = p.c.Call(ctx, "BatchGetMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
