// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sdkws

import "github.com/cloudwego/prutal"

// 包含消息的完整信息，是系统中最核心的消息结构
type MessageData struct {
	SendID     string  `protobuf:"bytes,1,opt,name=sendID" json:"sendID,omitempty"`           // 发送者用户ID
	RecvID     string  `protobuf:"bytes,2,opt,name=recvID" json:"recvID,omitempty"`           // 接收者用户ID (单聊时使用)
	ConvID     string  `protobuf:"bytes,3,opt,name=convID" json:"convID,omitempty"`           // 会话ID (群聊时使用)
	CMessaegID string  `protobuf:"bytes,4,opt,name=cMessaegID" json:"cMessaegID,omitempty"`   // 客户端生成的消息ID
	SMessageID string  `protobuf:"bytes,5,opt,name=sMessageID" json:"sMessageID,omitempty"`   // 服务器生成的消息ID
	ConvType   int32   `protobuf:"varint,6,opt,name=convType" json:"convType,omitempty"`      // 会话类型 (1:单聊 2:群聊 3:系统通知)
	Content    []byte  `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`         // 消息内容 (JSON格式的字节数组)
	Seq        int64   `protobuf:"varint,8,opt,name=seq" json:"seq,omitempty"`                // 消息序列号
	SendTime   float64 `protobuf:"fixed64,9,opt,name=sendTime" json:"sendTime,omitempty"`     // 消息发送时间戳
	Status     int32   `protobuf:"varint,10,opt,name=status" json:"status,omitempty"`         // 消息状态 (1:发送中 2:发送成功 3:发送失败 4:已删除 5:已撤回)
	IsRead     bool    `protobuf:"varint,11,opt,name=isRead" json:"isRead,omitempty"`         // 是否已读
	IsDeleted  bool    `protobuf:"varint,12,opt,name=isDeleted" json:"isDeleted,omitempty"`   // 是否已删除
	IsRecalled bool    `protobuf:"varint,13,opt,name=isRecalled" json:"isRecalled,omitempty"` // 是否已撤回
	IsPinned   bool    `protobuf:"varint,14,opt,name=isPinned" json:"isPinned,omitempty"`     // 是否已置顶
	SyncExt    string  `protobuf:"bytes,15,opt,name=syncExt" json:"syncExt,omitempty"`        // 同步扩展字段
	DStatus    int32   `protobuf:"varint,16,opt,name=dStatus" json:"dStatus,omitempty"`       // 状态， 二进制掩码  0：实时消息 1：离线消息（没有被接收过） 2：消息更新
	Propertys  string  `protobuf:"bytes,17,opt,name=propertys" json:"propertys,omitempty"`    // 消息属性
}

func (x *MessageData) Reset() { *x = MessageData{} }

func (x *MessageData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MessageData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MessageData) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MessageData) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MessageData) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *MessageData) GetCMessaegID() string {
	if x != nil {
		return x.CMessaegID
	}
	return ""
}

func (x *MessageData) GetSMessageID() string {
	if x != nil {
		return x.SMessageID
	}
	return ""
}

func (x *MessageData) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageData) GetSendTime() float64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageData) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MessageData) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *MessageData) GetIsRecalled() bool {
	if x != nil {
		return x.IsRecalled
	}
	return false
}

func (x *MessageData) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *MessageData) GetSyncExt() string {
	if x != nil {
		return x.SyncExt
	}
	return ""
}

func (x *MessageData) GetDStatus() int32 {
	if x != nil {
		return x.DStatus
	}
	return 0
}

func (x *MessageData) GetPropertys() string {
	if x != nil {
		return x.Propertys
	}
	return ""
}

// 会话信息
type ConversationData struct {
	ConvID      string         `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`            // 会话ID
	OwnerID     string         `protobuf:"bytes,2,opt,name=ownerID" json:"ownerID,omitempty"`          // 会话拥有者用户ID
	ConvType    int32          `protobuf:"varint,3,opt,name=convType" json:"convType,omitempty"`       // 会话类型
	Messages    []*MessageData `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`        // 会话消息列表
	LastMessage *MessageData   `protobuf:"bytes,5,opt,name=lastMessage" json:"lastMessage,omitempty"`  // 会话最后一条消息
	UnreadCount int64          `protobuf:"varint,6,opt,name=unreadCount" json:"unreadCount,omitempty"` // 会话未读消息数量
	IsMuted     bool           `protobuf:"varint,7,opt,name=isMuted" json:"isMuted,omitempty"`         // 会话是否静音
	IsTop       bool           `protobuf:"varint,8,opt,name=isTop" json:"isTop,omitempty"`             // 会话是否置顶
	IsDelete    bool           `protobuf:"varint,9,opt,name=isDelete" json:"isDelete,omitempty"`
	IsBlocked   bool           `protobuf:"varint,10,opt,name=isBlocked" json:"isBlocked,omitempty"`
	SyncExt     string         `protobuf:"bytes,11,opt,name=syncExt" json:"syncExt,omitempty"`
	Members     string         `protobuf:"bytes,12,opt,name=members" json:"members,omitempty"`
	Name        string         `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	AvatarURL   string         `protobuf:"bytes,14,opt,name=avatarURL" json:"avatarURL,omitempty"`
}

func (x *ConversationData) Reset() { *x = ConversationData{} }

func (x *ConversationData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ConversationData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationData) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *ConversationData) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *ConversationData) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *ConversationData) GetMessages() []*MessageData {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationData) GetLastMessage() *MessageData {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ConversationData) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationData) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *ConversationData) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *ConversationData) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *ConversationData) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *ConversationData) GetSyncExt() string {
	if x != nil {
		return x.SyncExt
	}
	return ""
}

func (x *ConversationData) GetMembers() string {
	if x != nil {
		return x.Members
	}
	return ""
}

func (x *ConversationData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationData) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

// 发送消息 --------------------------------
type SendMessageResult struct {
	ErrorCode string       `protobuf:"bytes,1,opt,name=errorCode" json:"errorCode,omitempty"` // 错误码
	ErrorMsg  string       `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`   // 错误信息
	Msg       *MessageData `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`             // 消息
}

func (x *SendMessageResult) Reset() { *x = SendMessageResult{} }

func (x *SendMessageResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMessageResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMessageResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SendMessageResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SendMessageResult) GetMsg() *MessageData {
	if x != nil {
		return x.Msg
	}
	return nil
}

type BatchSendMessageRequest struct {
	Msgs []*MessageData `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty"` // 消息列表
}

func (x *BatchSendMessageRequest) Reset() { *x = BatchSendMessageRequest{} }

func (x *BatchSendMessageRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchSendMessageRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchSendMessageRequest) GetMsgs() []*MessageData {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type BatchSendMessageResponse struct {
	Results []*SendMessageResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *BatchSendMessageResponse) Reset() { *x = BatchSendMessageResponse{} }

func (x *BatchSendMessageResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchSendMessageResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchSendMessageResponse) GetResults() []*SendMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 命令消息 -----------------------------------
type CmdMessage struct {
	Cmd int32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Id  int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`

	// 2001 : 会话状态发生改变 (删除) 会话创建走的另一个接口
	// 2002 : 会话已读状态发生改变
	// 2003 : 置顶状态发生改变
	// 2004 :
	// 2005 : 会话syncExt 发生改变
	Message      *MessageData      `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Conversation *ConversationData `protobuf:"bytes,4,opt,name=conversation" json:"conversation,omitempty"`
	Cursor       int64             `protobuf:"varint,5,opt,name=cursor" json:"cursor,omitempty"`
}

func (x *CmdMessage) Reset() { *x = CmdMessage{} }

func (x *CmdMessage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CmdMessage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CmdMessage) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CmdMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmdMessage) GetMessage() *MessageData {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CmdMessage) GetConversation() *ConversationData {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *CmdMessage) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type CmdMessageOptResult struct {
	Cmd       int32  `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Id        int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	ErrorCode int32  `protobuf:"varint,3,opt,name=errorCode" json:"errorCode,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (x *CmdMessageOptResult) Reset() { *x = CmdMessageOptResult{} }

func (x *CmdMessageOptResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CmdMessageOptResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CmdMessageOptResult) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CmdMessageOptResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmdMessageOptResult) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CmdMessageOptResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 更改消息请求 --------------------------------
type BatchChangeMessagesRequest struct {
	CmdMessages []*CmdMessage `protobuf:"bytes,1,rep,name=cmdMessages" json:"cmdMessages,omitempty"`
}

func (x *BatchChangeMessagesRequest) Reset() { *x = BatchChangeMessagesRequest{} }

func (x *BatchChangeMessagesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchChangeMessagesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchChangeMessagesRequest) GetCmdMessages() []*CmdMessage {
	if x != nil {
		return x.CmdMessages
	}
	return nil
}

type BatchChangeMessagesResponse struct {
	Results []*CmdMessageOptResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *BatchChangeMessagesResponse) Reset() { *x = BatchChangeMessagesResponse{} }

func (x *BatchChangeMessagesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchChangeMessagesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchChangeMessagesResponse) GetResults() []*CmdMessageOptResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 更改会话请求 --------------------------------
type BatchChangeConversationsRequest struct {
	CmdMessages []*CmdMessage `protobuf:"bytes,1,rep,name=cmdMessages" json:"cmdMessages,omitempty"`
}

func (x *BatchChangeConversationsRequest) Reset() { *x = BatchChangeConversationsRequest{} }

func (x *BatchChangeConversationsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchChangeConversationsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchChangeConversationsRequest) GetCmdMessages() []*CmdMessage {
	if x != nil {
		return x.CmdMessages
	}
	return nil
}

type BatchChangeConversationsResponse struct {
	Results []*CmdMessageOptResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *BatchChangeConversationsResponse) Reset() { *x = BatchChangeConversationsResponse{} }

func (x *BatchChangeConversationsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchChangeConversationsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchChangeConversationsResponse) GetResults() []*CmdMessageOptResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 单链拉取 ------------------------------------
type FetchConvMessageListRequest struct {
	ConvID  string `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`
	Cursor  int64  `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Limit   int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Forward bool   `protobuf:"varint,4,opt,name=forward" json:"forward,omitempty"`
}

func (x *FetchConvMessageListRequest) Reset() { *x = FetchConvMessageListRequest{} }

func (x *FetchConvMessageListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchConvMessageListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchConvMessageListRequest) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *FetchConvMessageListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

type FetchConvMessageListResponse struct {
	Messages  []*MessageData `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	HaveMore  bool           `protobuf:"varint,2,opt,name=haveMore" json:"haveMore,omitempty"`
	ErrorCode int32          `protobuf:"varint,3,opt,name=errorCode" json:"errorCode,omitempty"`
	Error     string         `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (x *FetchConvMessageListResponse) Reset() { *x = FetchConvMessageListResponse{} }

func (x *FetchConvMessageListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchConvMessageListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchConvMessageListResponse) GetMessages() []*MessageData {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FetchConvMessageListResponse) GetHaveMore() bool {
	if x != nil {
		return x.HaveMore
	}
	return false
}

func (x *FetchConvMessageListResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *FetchConvMessageListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 混链拉取 ------------------------------------
type FetchUserRecentConvListRequest struct {
	UserID  string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Cursor  int64  `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"` // 水位
	Limit   int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Forward bool   `protobuf:"varint,4,opt,name=forward" json:"forward,omitempty"`
	News    bool   `protobuf:"varint,5,opt,name=news" json:"news,omitempty"` // 是否拉取新消息
}

func (x *FetchUserRecentConvListRequest) Reset() { *x = FetchUserRecentConvListRequest{} }

func (x *FetchUserRecentConvListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchUserRecentConvListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchUserRecentConvListRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FetchUserRecentConvListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *FetchUserRecentConvListRequest) GetNews() bool {
	if x != nil {
		return x.News
	}
	return false
}

type FetchUserRecentConvListResponse struct {
	Conversations []*ConversationData `protobuf:"bytes,1,rep,name=conversations" json:"conversations,omitempty"`
	Left          int64               `protobuf:"varint,2,opt,name=left" json:"left,omitempty"` // 左右闭合
	Right         int64               `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`
	HasMore       bool                `protobuf:"varint,4,opt,name=hasMore" json:"hasMore,omitempty"`
}

func (x *FetchUserRecentConvListResponse) Reset() { *x = FetchUserRecentConvListResponse{} }

func (x *FetchUserRecentConvListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchUserRecentConvListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchUserRecentConvListResponse) GetConversations() []*ConversationData {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *FetchUserRecentConvListResponse) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *FetchUserRecentConvListResponse) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *FetchUserRecentConvListResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 混链连续性检查 -------------------------------
type UserMessageIntegrityCheckRequest struct {
	UserID  string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`   // 用户ID
	Left    int64    `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`      // 左区间
	Right   int64    `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`    // 右区间
	ConvIDs []string `protobuf:"bytes,4,rep,name=convIDs" json:"convIDs,omitempty"` // 会话ID列表
}

func (x *UserMessageIntegrityCheckRequest) Reset() { *x = UserMessageIntegrityCheckRequest{} }

func (x *UserMessageIntegrityCheckRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserMessageIntegrityCheckRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserMessageIntegrityCheckRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserMessageIntegrityCheckRequest) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *UserMessageIntegrityCheckRequest) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *UserMessageIntegrityCheckRequest) GetConvIDs() []string {
	if x != nil {
		return x.ConvIDs
	}
	return nil
}

type UserMessageIntegrityCheckResponse struct {
	IsIntegrity   bool                `protobuf:"varint,1,opt,name=isIntegrity" json:"isIntegrity,omitempty"`    // 是否完整
	Left          int64               `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`                  // 左右闭合
	Right         int64               `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`                // 右区间
	Conversations []*ConversationData `protobuf:"bytes,4,rep,name=conversations" json:"conversations,omitempty"` // 补齐的会话信息
}

func (x *UserMessageIntegrityCheckResponse) Reset() { *x = UserMessageIntegrityCheckResponse{} }

func (x *UserMessageIntegrityCheckResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserMessageIntegrityCheckResponse) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *UserMessageIntegrityCheckResponse) GetIsIntegrity() bool {
	if x != nil {
		return x.IsIntegrity
	}
	return false
}

func (x *UserMessageIntegrityCheckResponse) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *UserMessageIntegrityCheckResponse) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *UserMessageIntegrityCheckResponse) GetConversations() []*ConversationData {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// 批量获取消息 ------------------------------------
type GetMessageResult struct {
	MessageID string       `protobuf:"bytes,1,opt,name=messageID" json:"messageID,omitempty"` // 请求的消息ID
	Message   *MessageData `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`     // 消息数据（如果获取成功）
	ErrorCode string       `protobuf:"bytes,3,opt,name=errorCode" json:"errorCode,omitempty"` // 错误码（如果获取失败）
	ErrorMsg  string       `protobuf:"bytes,4,opt,name=errorMsg" json:"errorMsg,omitempty"`   // 错误信息（如果获取失败）
}

func (x *GetMessageResult) Reset() { *x = GetMessageResult{} }

func (x *GetMessageResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMessageResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMessageResult) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *GetMessageResult) GetMessage() *MessageData {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GetMessageResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetMessageResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type BatchGetMessagesRequest struct {
	MessageIDs []string `protobuf:"bytes,1,rep,name=messageIDs" json:"messageIDs,omitempty"` // 消息ID列表
	ConvID     string   `protobuf:"bytes,2,opt,name=convID" json:"convID,omitempty"`         // 会话ID（可选，用于过滤）
}

func (x *BatchGetMessagesRequest) Reset() { *x = BatchGetMessagesRequest{} }

func (x *BatchGetMessagesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetMessagesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetMessagesRequest) GetMessageIDs() []string {
	if x != nil {
		return x.MessageIDs
	}
	return nil
}

func (x *BatchGetMessagesRequest) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

type BatchGetMessagesResponse struct {
	Results []*GetMessageResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"` // 结果列表，每个结果包含消息和对应的错误信息
}

func (x *BatchGetMessagesResponse) Reset() { *x = BatchGetMessagesResponse{} }

func (x *BatchGetMessagesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetMessagesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetMessagesResponse) GetResults() []*GetMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 批量获取会话 ------------------------------------
type GetConversationResult struct {
	ConvID       string            `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`             // 请求的会话ID
	Conversation *ConversationData `protobuf:"bytes,2,opt,name=conversation" json:"conversation,omitempty"` // 会话数据（如果获取成功）
	ErrorCode    string            `protobuf:"bytes,3,opt,name=errorCode" json:"errorCode,omitempty"`       // 错误码（如果获取失败）
	ErrorMsg     string            `protobuf:"bytes,4,opt,name=errorMsg" json:"errorMsg,omitempty"`         // 错误信息（如果获取失败）
}

func (x *GetConversationResult) Reset() { *x = GetConversationResult{} }

func (x *GetConversationResult) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConversationResult) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *GetConversationResult) GetConversation() *ConversationData {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *GetConversationResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetConversationResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type BatchGetConversationsRequest struct {
	ConvIDs []string `protobuf:"bytes,1,rep,name=convIDs" json:"convIDs,omitempty"` // 会话ID列表
	OwnerID string   `protobuf:"bytes,2,opt,name=ownerID" json:"ownerID,omitempty"` // 会话拥有者用户ID（可选，用于过滤）
}

func (x *BatchGetConversationsRequest) Reset() { *x = BatchGetConversationsRequest{} }

func (x *BatchGetConversationsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetConversationsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetConversationsRequest) GetConvIDs() []string {
	if x != nil {
		return x.ConvIDs
	}
	return nil
}

func (x *BatchGetConversationsRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type BatchGetConversationsResponse struct {
	Results []*GetConversationResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"` // 结果列表，每个结果包含会话和对应的错误信息
}

func (x *BatchGetConversationsResponse) Reset() { *x = BatchGetConversationsResponse{} }

func (x *BatchGetConversationsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetConversationsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetConversationsResponse) GetResults() []*GetConversationResult {
	if x != nil {
		return x.Results
	}
	return nil
}
