// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sdkws

import "github.com/cloudwego/prutal"

// 包含消息的完整信息，是系统中最核心的消息结构
type MessageData struct {
	SendID     string  `protobuf:"bytes,1,opt,name=sendID" json:"sendID,omitempty"`           // 发送者用户ID
	RecvID     string  `protobuf:"bytes,2,opt,name=recvID" json:"recvID,omitempty"`           // 接收者用户ID (单聊时使用)
	ConvID     string  `protobuf:"bytes,3,opt,name=convID" json:"convID,omitempty"`           // 会话ID (群聊时使用)
	CMessaegID string  `protobuf:"bytes,4,opt,name=cMessaegID" json:"cMessaegID,omitempty"`   // 客户端生成的消息ID
	SMessageID string  `protobuf:"bytes,5,opt,name=sMessageID" json:"sMessageID,omitempty"`   // 服务器生成的消息ID
	ConvType   int32   `protobuf:"varint,6,opt,name=convType" json:"convType,omitempty"`      // 会话类型 (1:单聊 2:群聊 3:系统通知)
	Content    []byte  `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`         // 消息内容 (JSON格式的字节数组)
	Seq        int64   `protobuf:"varint,8,opt,name=seq" json:"seq,omitempty"`                // 消息序列号
	SendTime   float64 `protobuf:"fixed64,9,opt,name=sendTime" json:"sendTime,omitempty"`     // 消息发送时间戳
	Status     int32   `protobuf:"varint,10,opt,name=status" json:"status,omitempty"`         // 消息状态 (1:发送中 2:发送成功 3:发送失败 4:已删除 5:已撤回)
	IsRead     bool    `protobuf:"varint,11,opt,name=isRead" json:"isRead,omitempty"`         // 是否已读
	IsDeleted  bool    `protobuf:"varint,12,opt,name=isDeleted" json:"isDeleted,omitempty"`   // 是否已删除
	IsRecalled bool    `protobuf:"varint,13,opt,name=isRecalled" json:"isRecalled,omitempty"` // 是否已撤回
	IsPinned   bool    `protobuf:"varint,14,opt,name=isPinned" json:"isPinned,omitempty"`     // 是否已置顶
	SyncExt    string  `protobuf:"bytes,15,opt,name=syncExt" json:"syncExt,omitempty"`        // 同步扩展字段
	DStatus    int32   `protobuf:"varint,16,opt,name=dStatus" json:"dStatus,omitempty"`       // 状态， 二进制掩码  0：实时消息 1：离线消息（没有被接收过） 2：消息更新
	Propertys  string  `protobuf:"bytes,17,opt,name=propertys" json:"propertys,omitempty"`    // 消息属性
}

func (x *MessageData) Reset() { *x = MessageData{} }

func (x *MessageData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MessageData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MessageData) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MessageData) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MessageData) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *MessageData) GetCMessaegID() string {
	if x != nil {
		return x.CMessaegID
	}
	return ""
}

func (x *MessageData) GetSMessageID() string {
	if x != nil {
		return x.SMessageID
	}
	return ""
}

func (x *MessageData) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageData) GetSendTime() float64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageData) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MessageData) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *MessageData) GetIsRecalled() bool {
	if x != nil {
		return x.IsRecalled
	}
	return false
}

func (x *MessageData) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *MessageData) GetSyncExt() string {
	if x != nil {
		return x.SyncExt
	}
	return ""
}

func (x *MessageData) GetDStatus() int32 {
	if x != nil {
		return x.DStatus
	}
	return 0
}

func (x *MessageData) GetPropertys() string {
	if x != nil {
		return x.Propertys
	}
	return ""
}

// 会话信息
type ConversationData struct {
	ConvID        string         `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`               // 会话ID
	OwnerID       string         `protobuf:"bytes,2,opt,name=ownerID" json:"ownerID,omitempty"`             // 会话拥有者用户ID
	ConvType      int32          `protobuf:"varint,3,opt,name=convType" json:"convType,omitempty"`          // 会话类型
	Version       int64          `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`            // 会话版本
	Messages      []*MessageData `protobuf:"bytes,5,rep,name=messages" json:"messages,omitempty"`           // 会话消息列表
	LastMessage   *MessageData   `protobuf:"bytes,6,opt,name=lastMessage" json:"lastMessage,omitempty"`     // 会话最后一条消息
	LastMessageID string         `protobuf:"bytes,7,opt,name=lastMessageID" json:"lastMessageID,omitempty"` // 会话最后一条消息ID
	UnreadCount   int64          `protobuf:"varint,8,opt,name=unreadCount" json:"unreadCount,omitempty"`    // 会话未读消息数量
	IsMuted       bool           `protobuf:"varint,9,opt,name=isMuted" json:"isMuted,omitempty"`            // 会话是否静音
	IsTop         bool           `protobuf:"varint,10,opt,name=isTop" json:"isTop,omitempty"`               // 会话是否置顶
	IsDelete      bool           `protobuf:"varint,11,opt,name=isDelete" json:"isDelete,omitempty"`
	IsBlocked     bool           `protobuf:"varint,12,opt,name=isBlocked" json:"isBlocked,omitempty"`
	SyncExt       string         `protobuf:"bytes,13,opt,name=syncExt" json:"syncExt,omitempty"`
	Members       string         `protobuf:"bytes,14,opt,name=members" json:"members,omitempty"`
	Name          string         `protobuf:"bytes,15,opt,name=name" json:"name,omitempty"`
	AvatarURL     string         `protobuf:"bytes,16,opt,name=avatarURL" json:"avatarURL,omitempty"`
}

func (x *ConversationData) Reset() { *x = ConversationData{} }

func (x *ConversationData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ConversationData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationData) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *ConversationData) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *ConversationData) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *ConversationData) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConversationData) GetMessages() []*MessageData {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationData) GetLastMessage() *MessageData {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ConversationData) GetLastMessageID() string {
	if x != nil {
		return x.LastMessageID
	}
	return ""
}

func (x *ConversationData) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationData) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *ConversationData) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *ConversationData) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *ConversationData) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *ConversationData) GetSyncExt() string {
	if x != nil {
		return x.SyncExt
	}
	return ""
}

func (x *ConversationData) GetMembers() string {
	if x != nil {
		return x.Members
	}
	return ""
}

func (x *ConversationData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationData) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

// 发送消息 --------------------------------
type SendMessageResult struct {
	ErrorCode string       `protobuf:"bytes,1,opt,name=errorCode" json:"errorCode,omitempty"` // 错误码
	ErrorMsg  string       `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`   // 错误信息
	Msg       *MessageData `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`             // 消息
}

func (x *SendMessageResult) Reset() { *x = SendMessageResult{} }

func (x *SendMessageResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMessageResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMessageResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SendMessageResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SendMessageResult) GetMsg() *MessageData {
	if x != nil {
		return x.Msg
	}
	return nil
}

type BatchSendMessageRequest struct {
	Msgs []*MessageData `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty"` // 消息列表
}

func (x *BatchSendMessageRequest) Reset() { *x = BatchSendMessageRequest{} }

func (x *BatchSendMessageRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchSendMessageRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchSendMessageRequest) GetMsgs() []*MessageData {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type BatchSendMessageResponse struct {
	Results []*SendMessageResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (x *BatchSendMessageResponse) Reset() { *x = BatchSendMessageResponse{} }

func (x *BatchSendMessageResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchSendMessageResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchSendMessageResponse) GetResults() []*SendMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 命令消息 -----------------------------------
type CmdMessage struct {
	Cmd int32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Id  int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`

	// 二进制数据
	Data    []byte `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Version int64  `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Uid     string `protobuf:"bytes,6,opt,name=uid" json:"uid,omitempty"`
}

func (x *CmdMessage) Reset() { *x = CmdMessage{} }

func (x *CmdMessage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CmdMessage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CmdMessage) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CmdMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmdMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CmdMessage) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CmdMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 单链拉取 ------------------------------------
type FetchConvMessageListRequest struct {
	Mode    int64  `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	ConvID  string `protobuf:"bytes,3,opt,name=convID" json:"convID,omitempty"`
	Version int64  `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Limit   int64  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	Left    int64  `protobuf:"varint,6,opt,name=left" json:"left,omitempty"`
	Right   int64  `protobuf:"varint,7,opt,name=right" json:"right,omitempty"`
}

func (x *FetchConvMessageListRequest) Reset() { *x = FetchConvMessageListRequest{} }

func (x *FetchConvMessageListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchConvMessageListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchConvMessageListRequest) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FetchConvMessageListRequest) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *FetchConvMessageListRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *FetchConvMessageListRequest) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

type FetchConvMessageListResponse struct {
	Messages []*MessageData `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	Left     int64          `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`
	Right    int64          `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`
	HaveMore bool           `protobuf:"varint,4,opt,name=haveMore" json:"haveMore,omitempty"`
	Error    string         `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (x *FetchConvMessageListResponse) Reset() { *x = FetchConvMessageListResponse{} }

func (x *FetchConvMessageListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchConvMessageListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchConvMessageListResponse) GetMessages() []*MessageData {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FetchConvMessageListResponse) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *FetchConvMessageListResponse) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *FetchConvMessageListResponse) GetHaveMore() bool {
	if x != nil {
		return x.HaveMore
	}
	return false
}

func (x *FetchConvMessageListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 混链拉取 ------------------------------------
type FetchUserRecentConvListRequest struct {
	Mode         int64  `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	UserID       string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Version      int64  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Limit        int64  `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	LowVersion   int64  `protobuf:"varint,5,opt,name=lowVersion" json:"lowVersion,omitempty"`
	UpperVersion int64  `protobuf:"varint,6,opt,name=upperVersion" json:"upperVersion,omitempty"`
}

func (x *FetchUserRecentConvListRequest) Reset() { *x = FetchUserRecentConvListRequest{} }

func (x *FetchUserRecentConvListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchUserRecentConvListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchUserRecentConvListRequest) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FetchUserRecentConvListRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetLowVersion() int64 {
	if x != nil {
		return x.LowVersion
	}
	return 0
}

func (x *FetchUserRecentConvListRequest) GetUpperVersion() int64 {
	if x != nil {
		return x.UpperVersion
	}
	return 0
}

type FetchUserRecentConvListResponse struct {
	Conversations []*ConversationData `protobuf:"bytes,1,rep,name=conversations" json:"conversations,omitempty"`
	Left          int64               `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`
	Right         int64               `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`
	HaveMore      bool                `protobuf:"varint,4,opt,name=haveMore" json:"haveMore,omitempty"`
	Error         string              `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (x *FetchUserRecentConvListResponse) Reset() { *x = FetchUserRecentConvListResponse{} }

func (x *FetchUserRecentConvListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FetchUserRecentConvListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchUserRecentConvListResponse) GetConversations() []*ConversationData {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *FetchUserRecentConvListResponse) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *FetchUserRecentConvListResponse) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *FetchUserRecentConvListResponse) GetHaveMore() bool {
	if x != nil {
		return x.HaveMore
	}
	return false
}

func (x *FetchUserRecentConvListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 混链连续性检查 -------------------------------
type UserMessageIntegrityCheckRequest struct {
	UserID  string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`   // 用户ID
	Left    int64    `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`      // 左区间
	Right   int64    `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`    // 右区间
	ConvIDs []string `protobuf:"bytes,4,rep,name=convIDs" json:"convIDs,omitempty"` // 会话ID列表
}

func (x *UserMessageIntegrityCheckRequest) Reset() { *x = UserMessageIntegrityCheckRequest{} }

func (x *UserMessageIntegrityCheckRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserMessageIntegrityCheckRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserMessageIntegrityCheckRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserMessageIntegrityCheckRequest) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *UserMessageIntegrityCheckRequest) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *UserMessageIntegrityCheckRequest) GetConvIDs() []string {
	if x != nil {
		return x.ConvIDs
	}
	return nil
}

type UserMessageIntegrityCheckResponse struct {
	IsIntegrity   bool                `protobuf:"varint,1,opt,name=isIntegrity" json:"isIntegrity,omitempty"`    // 是否完整
	Left          int64               `protobuf:"varint,2,opt,name=left" json:"left,omitempty"`                  // 左右闭合
	Right         int64               `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`                // 右区间
	Conversations []*ConversationData `protobuf:"bytes,4,rep,name=conversations" json:"conversations,omitempty"` // 补齐的会话信息
}

func (x *UserMessageIntegrityCheckResponse) Reset() { *x = UserMessageIntegrityCheckResponse{} }

func (x *UserMessageIntegrityCheckResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserMessageIntegrityCheckResponse) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *UserMessageIntegrityCheckResponse) GetIsIntegrity() bool {
	if x != nil {
		return x.IsIntegrity
	}
	return false
}

func (x *UserMessageIntegrityCheckResponse) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *UserMessageIntegrityCheckResponse) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *UserMessageIntegrityCheckResponse) GetConversations() []*ConversationData {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// 批量获取消息 ------------------------------------
type GetMessageResult struct {
	MessageID string       `protobuf:"bytes,1,opt,name=messageID" json:"messageID,omitempty"` // 请求的消息ID
	Message   *MessageData `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`     // 消息数据（如果获取成功）
	ErrorCode string       `protobuf:"bytes,3,opt,name=errorCode" json:"errorCode,omitempty"` // 错误码（如果获取失败）
	ErrorMsg  string       `protobuf:"bytes,4,opt,name=errorMsg" json:"errorMsg,omitempty"`   // 错误信息（如果获取失败）
}

func (x *GetMessageResult) Reset() { *x = GetMessageResult{} }

func (x *GetMessageResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMessageResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMessageResult) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *GetMessageResult) GetMessage() *MessageData {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GetMessageResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetMessageResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type BatchGetMessagesRequest struct {
	MessageIDs []string `protobuf:"bytes,1,rep,name=messageIDs" json:"messageIDs,omitempty"` // 消息ID列表
	ConvID     string   `protobuf:"bytes,2,opt,name=convID" json:"convID,omitempty"`         // 会话ID（可选，用于过滤）
}

func (x *BatchGetMessagesRequest) Reset() { *x = BatchGetMessagesRequest{} }

func (x *BatchGetMessagesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetMessagesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetMessagesRequest) GetMessageIDs() []string {
	if x != nil {
		return x.MessageIDs
	}
	return nil
}

func (x *BatchGetMessagesRequest) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

type BatchGetMessagesResponse struct {
	Results []*GetMessageResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"` // 结果列表，每个结果包含消息和对应的错误信息
}

func (x *BatchGetMessagesResponse) Reset() { *x = BatchGetMessagesResponse{} }

func (x *BatchGetMessagesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetMessagesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetMessagesResponse) GetResults() []*GetMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 批量获取会话 ------------------------------------
type GetConversationResult struct {
	ConvID       string            `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`             // 请求的会话ID
	Conversation *ConversationData `protobuf:"bytes,2,opt,name=conversation" json:"conversation,omitempty"` // 会话数据（如果获取成功）
	ErrorCode    string            `protobuf:"bytes,3,opt,name=errorCode" json:"errorCode,omitempty"`       // 错误码（如果获取失败）
	ErrorMsg     string            `protobuf:"bytes,4,opt,name=errorMsg" json:"errorMsg,omitempty"`         // 错误信息（如果获取失败）
}

func (x *GetConversationResult) Reset() { *x = GetConversationResult{} }

func (x *GetConversationResult) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConversationResult) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *GetConversationResult) GetConversation() *ConversationData {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *GetConversationResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetConversationResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type BatchGetConversationsRequest struct {
	ConvIDs []string `protobuf:"bytes,1,rep,name=convIDs" json:"convIDs,omitempty"` // 会话ID列表
	OwnerID string   `protobuf:"bytes,2,opt,name=ownerID" json:"ownerID,omitempty"` // 会话拥有者用户ID（可选，用于过滤）
}

func (x *BatchGetConversationsRequest) Reset() { *x = BatchGetConversationsRequest{} }

func (x *BatchGetConversationsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetConversationsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetConversationsRequest) GetConvIDs() []string {
	if x != nil {
		return x.ConvIDs
	}
	return nil
}

func (x *BatchGetConversationsRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type BatchGetConversationsResponse struct {
	Results []*GetConversationResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"` // 结果列表，每个结果包含会话和对应的错误信息
}

func (x *BatchGetConversationsResponse) Reset() { *x = BatchGetConversationsResponse{} }

func (x *BatchGetConversationsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchGetConversationsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchGetConversationsResponse) GetResults() []*GetConversationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 创建群聊
type CreateGroupRequest struct {
	OwnerID    string   `protobuf:"bytes,1,opt,name=ownerID" json:"ownerID,omitempty"`       // 会话拥有者用户ID
	Name       string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`             // 群聊名称
	MemberUIDs []string `protobuf:"bytes,3,rep,name=memberUIDs" json:"memberUIDs,omitempty"` // 群聊成员用户ID列表
}

func (x *CreateGroupRequest) Reset() { *x = CreateGroupRequest{} }

func (x *CreateGroupRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateGroupRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateGroupRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberUIDs() []string {
	if x != nil {
		return x.MemberUIDs
	}
	return nil
}

type CreateGroupResponse struct {
	ErrorCode    int32             `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"`      // 错误码
	ErrorMsg     string            `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`         // 错误信息
	Conversation *ConversationData `protobuf:"bytes,3,opt,name=conversation" json:"conversation,omitempty"` // 会话数据
}

func (x *CreateGroupResponse) Reset() { *x = CreateGroupResponse{} }

func (x *CreateGroupResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateGroupResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateGroupResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateGroupResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CreateGroupResponse) GetConversation() *ConversationData {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// 邀请进群
type InviteGroupMembersRequest struct {
	ConvID     string   `protobuf:"bytes,1,opt,name=convID" json:"convID,omitempty"`         // 会话ID
	MemberUIDs []string `protobuf:"bytes,2,rep,name=memberUIDs" json:"memberUIDs,omitempty"` // 群聊成员用户ID列表
}

func (x *InviteGroupMembersRequest) Reset() { *x = InviteGroupMembersRequest{} }

func (x *InviteGroupMembersRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *InviteGroupMembersRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InviteGroupMembersRequest) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *InviteGroupMembersRequest) GetMemberUIDs() []string {
	if x != nil {
		return x.MemberUIDs
	}
	return nil
}

type InviteGroupMembersResponse struct {
	ErrorCode int32  `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"` // 错误码
	ErrorMsg  string `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`    // 错误信息
}

func (x *InviteGroupMembersResponse) Reset() { *x = InviteGroupMembersResponse{} }

func (x *InviteGroupMembersResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *InviteGroupMembersResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InviteGroupMembersResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *InviteGroupMembersResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 被邀请进群信息
type InvitedGroupInfo struct {
	Conversation *ConversationData `protobuf:"bytes,1,opt,name=conversation" json:"conversation,omitempty"` // 会话数据
}

func (x *InvitedGroupInfo) Reset() { *x = InvitedGroupInfo{} }

func (x *InvitedGroupInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *InvitedGroupInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InvitedGroupInfo) GetConversation() *ConversationData {
	if x != nil {
		return x.Conversation
	}
	return nil
}
