// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sequenceservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sequence "github.com/rhp-QE/roc-im-server/kitex_gen/sequence"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetNextSeq(ctx context.Context, Req *sequence.GetNextSeqRequest, callOptions ...callopt.Option) (r *sequence.GetNextSeqResponse, err error)
	BatchGetNextSeq(ctx context.Context, Req *sequence.BatchGetNextSeqRequest, callOptions ...callopt.Option) (r *sequence.BatchGetNextSeqResponse, err error)
	GetMaxSeq(ctx context.Context, Req *sequence.GetMaxSeqRequest, callOptions ...callopt.Option) (r *sequence.GetMaxSeqResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSequenceServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSequenceServiceClient struct {
	*kClient
}

func (p *kSequenceServiceClient) GetNextSeq(ctx context.Context, Req *sequence.GetNextSeqRequest, callOptions ...callopt.Option) (r *sequence.GetNextSeqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNextSeq(ctx, Req)
}

func (p *kSequenceServiceClient) BatchGetNextSeq(ctx context.Context, Req *sequence.BatchGetNextSeqRequest, callOptions ...callopt.Option) (r *sequence.BatchGetNextSeqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetNextSeq(ctx, Req)
}

func (p *kSequenceServiceClient) GetMaxSeq(ctx context.Context, Req *sequence.GetMaxSeqRequest, callOptions ...callopt.Option) (r *sequence.GetMaxSeqResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMaxSeq(ctx, Req)
}
