// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sequenceservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	sequence "github.com/rhp-QE/roc-im-server/kitex_gen/sequence"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetNextSeq": kitex.NewMethodInfo(
		getNextSeqHandler,
		newGetNextSeqArgs,
		newGetNextSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGetNextSeq": kitex.NewMethodInfo(
		batchGetNextSeqHandler,
		newBatchGetNextSeqArgs,
		newBatchGetNextSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetMaxSeq": kitex.NewMethodInfo(
		getMaxSeqHandler,
		newGetMaxSeqArgs,
		newGetMaxSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	sequenceServiceServiceInfo                = NewServiceInfo()
	sequenceServiceServiceInfoForClient       = NewServiceInfoForClient()
	sequenceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return sequenceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return sequenceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return sequenceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SequenceService"
	handlerType := (*sequence.SequenceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sequence",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func getNextSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sequence.GetNextSeqRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(sequence.SequenceService).GetNextSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetNextSeqArgs:
		success, err := handler.(sequence.SequenceService).GetNextSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetNextSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetNextSeqArgs() interface{} {
	return &GetNextSeqArgs{}
}

func newGetNextSeqResult() interface{} {
	return &GetNextSeqResult{}
}

type GetNextSeqArgs struct {
	Req *sequence.GetNextSeqRequest
}

func (p *GetNextSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetNextSeqArgs) Unmarshal(in []byte) error {
	msg := new(sequence.GetNextSeqRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetNextSeqArgs_Req_DEFAULT *sequence.GetNextSeqRequest

func (p *GetNextSeqArgs) GetReq() *sequence.GetNextSeqRequest {
	if !p.IsSetReq() {
		return GetNextSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetNextSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetNextSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetNextSeqResult struct {
	Success *sequence.GetNextSeqResponse
}

var GetNextSeqResult_Success_DEFAULT *sequence.GetNextSeqResponse

func (p *GetNextSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetNextSeqResult) Unmarshal(in []byte) error {
	msg := new(sequence.GetNextSeqResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetNextSeqResult) GetSuccess() *sequence.GetNextSeqResponse {
	if !p.IsSetSuccess() {
		return GetNextSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetNextSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*sequence.GetNextSeqResponse)
}

func (p *GetNextSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetNextSeqResult) GetResult() interface{} {
	return p.Success
}

func batchGetNextSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sequence.BatchGetNextSeqRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(sequence.SequenceService).BatchGetNextSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetNextSeqArgs:
		success, err := handler.(sequence.SequenceService).BatchGetNextSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetNextSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetNextSeqArgs() interface{} {
	return &BatchGetNextSeqArgs{}
}

func newBatchGetNextSeqResult() interface{} {
	return &BatchGetNextSeqResult{}
}

type BatchGetNextSeqArgs struct {
	Req *sequence.BatchGetNextSeqRequest
}

func (p *BatchGetNextSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetNextSeqArgs) Unmarshal(in []byte) error {
	msg := new(sequence.BatchGetNextSeqRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetNextSeqArgs_Req_DEFAULT *sequence.BatchGetNextSeqRequest

func (p *BatchGetNextSeqArgs) GetReq() *sequence.BatchGetNextSeqRequest {
	if !p.IsSetReq() {
		return BatchGetNextSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetNextSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetNextSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetNextSeqResult struct {
	Success *sequence.BatchGetNextSeqResponse
}

var BatchGetNextSeqResult_Success_DEFAULT *sequence.BatchGetNextSeqResponse

func (p *BatchGetNextSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetNextSeqResult) Unmarshal(in []byte) error {
	msg := new(sequence.BatchGetNextSeqResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetNextSeqResult) GetSuccess() *sequence.BatchGetNextSeqResponse {
	if !p.IsSetSuccess() {
		return BatchGetNextSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetNextSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*sequence.BatchGetNextSeqResponse)
}

func (p *BatchGetNextSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetNextSeqResult) GetResult() interface{} {
	return p.Success
}

func getMaxSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sequence.GetMaxSeqRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(sequence.SequenceService).GetMaxSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetMaxSeqArgs:
		success, err := handler.(sequence.SequenceService).GetMaxSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetMaxSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetMaxSeqArgs() interface{} {
	return &GetMaxSeqArgs{}
}

func newGetMaxSeqResult() interface{} {
	return &GetMaxSeqResult{}
}

type GetMaxSeqArgs struct {
	Req *sequence.GetMaxSeqRequest
}

func (p *GetMaxSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetMaxSeqArgs) Unmarshal(in []byte) error {
	msg := new(sequence.GetMaxSeqRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetMaxSeqArgs_Req_DEFAULT *sequence.GetMaxSeqRequest

func (p *GetMaxSeqArgs) GetReq() *sequence.GetMaxSeqRequest {
	if !p.IsSetReq() {
		return GetMaxSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetMaxSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetMaxSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetMaxSeqResult struct {
	Success *sequence.GetMaxSeqResponse
}

var GetMaxSeqResult_Success_DEFAULT *sequence.GetMaxSeqResponse

func (p *GetMaxSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetMaxSeqResult) Unmarshal(in []byte) error {
	msg := new(sequence.GetMaxSeqResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetMaxSeqResult) GetSuccess() *sequence.GetMaxSeqResponse {
	if !p.IsSetSuccess() {
		return GetMaxSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetMaxSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*sequence.GetMaxSeqResponse)
}

func (p *GetMaxSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetMaxSeqResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetNextSeq(ctx context.Context, Req *sequence.GetNextSeqRequest) (r *sequence.GetNextSeqResponse, err error) {
	var _args GetNextSeqArgs
	_args.Req = Req
	var _result GetNextSeqResult
	if err = p.c.Call(ctx, "GetNextSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetNextSeq(ctx context.Context, Req *sequence.BatchGetNextSeqRequest) (r *sequence.BatchGetNextSeqResponse, err error) {
	var _args BatchGetNextSeqArgs
	_args.Req = Req
	var _result BatchGetNextSeqResult
	if err = p.c.Call(ctx, "BatchGetNextSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMaxSeq(ctx context.Context, Req *sequence.GetMaxSeqRequest) (r *sequence.GetMaxSeqResponse, err error) {
	var _args GetMaxSeqArgs
	_args.Req = Req
	var _result GetMaxSeqResult
	if err = p.c.Call(ctx, "GetMaxSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
