// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sequence

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 获取下一个序列号请求 (递增)
type GetNextSeqIncRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"` // 唯一ID
}

func (x *GetNextSeqIncRequest) Reset() { *x = GetNextSeqIncRequest{} }

func (x *GetNextSeqIncRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetNextSeqIncRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetNextSeqIncRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取下一个序列号 (连续递增）
type GetNextSeqConsecutiveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"` // 唯一ID
}

func (x *GetNextSeqConsecutiveRequest) Reset() { *x = GetNextSeqConsecutiveRequest{} }

func (x *GetNextSeqConsecutiveRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetNextSeqConsecutiveRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetNextSeqConsecutiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取下一个序列号响应
type GetNextSeqResponse struct {
	Seq       int64  `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`              // 生成的序列号
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code" json:"error_code,omitempty"` // 错误码
	ErrorMsg  string `protobuf:"bytes,3,opt,name=error_msg" json:"error_msg,omitempty"`   // 错误信息
}

func (x *GetNextSeqResponse) Reset() { *x = GetNextSeqResponse{} }

func (x *GetNextSeqResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetNextSeqResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetNextSeqResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetNextSeqResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetNextSeqResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SequenceService interface {
	GetNextSeqInc(ctx context.Context, req *GetNextSeqIncRequest) (res *GetNextSeqResponse, err error)
	GetNextSeqConsecutive(ctx context.Context, req *GetNextSeqConsecutiveRequest) (res *GetNextSeqResponse, err error)
}
