// Code generated by Kitex v0.13.1. DO NOT EDIT.

package msg

import (
	"context"
	"github.com/rhp-QE/roc-im-server/internal/kitex_gen/sdkws"

	"github.com/cloudwego/prutal"
)

type MsgDataToMQ struct {
	Token   string         `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	MsgData *sdkws.MsgData `protobuf:"bytes,2,opt,name=msgData" json:"msgData,omitempty"`
}

func (x *MsgDataToMQ) Reset() { *x = MsgDataToMQ{} }

func (x *MsgDataToMQ) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MsgDataToMQ) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MsgDataToMQ) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgDataToMQ) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type MsgDataToDB struct {
	MsgData *sdkws.MsgData `protobuf:"bytes,1,opt,name=msgData" json:"msgData,omitempty"`
}

func (x *MsgDataToDB) Reset() { *x = MsgDataToDB{} }

func (x *MsgDataToDB) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MsgDataToDB) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MsgDataToDB) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type PushMsgDataToMQ struct {
	MsgData        *sdkws.MsgData `protobuf:"bytes,1,opt,name=msgData" json:"msgData,omitempty"`
	ConversationID string         `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
}

func (x *PushMsgDataToMQ) Reset() { *x = PushMsgDataToMQ{} }

func (x *PushMsgDataToMQ) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushMsgDataToMQ) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushMsgDataToMQ) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *PushMsgDataToMQ) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type MsgDataToMongoByMQ struct {
	LastSeq        int64            `protobuf:"varint,1,opt,name=lastSeq" json:"lastSeq,omitempty"`
	ConversationID string           `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	MsgData        []*sdkws.MsgData `protobuf:"bytes,3,rep,name=msgData" json:"msgData,omitempty"`
}

func (x *MsgDataToMongoByMQ) Reset() { *x = MsgDataToMongoByMQ{} }

func (x *MsgDataToMongoByMQ) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MsgDataToMongoByMQ) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MsgDataToMongoByMQ) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *MsgDataToMongoByMQ) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *MsgDataToMongoByMQ) GetMsgData() []*sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type GetMaxAndMinSeqReq struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *GetMaxAndMinSeqReq) Reset() { *x = GetMaxAndMinSeqReq{} }

func (x *GetMaxAndMinSeqReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMaxAndMinSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMaxAndMinSeqReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetMaxAndMinSeqResp struct {
	MaxSeq int64 `protobuf:"varint,1,opt,name=MaxSeq" json:"MaxSeq,omitempty"`
	MinSeq int64 `protobuf:"varint,2,opt,name=MinSeq" json:"MinSeq,omitempty"`
}

func (x *GetMaxAndMinSeqResp) Reset() { *x = GetMaxAndMinSeqResp{} }

func (x *GetMaxAndMinSeqResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMaxAndMinSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMaxAndMinSeqResp) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *GetMaxAndMinSeqResp) GetMinSeq() int64 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

type SendMsgReq struct {
	MsgData *sdkws.MsgData `protobuf:"bytes,3,opt,name=msgData" json:"msgData,omitempty"`
}

func (x *SendMsgReq) Reset() { *x = SendMsgReq{} }

func (x *SendMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type SendMsgResp struct {
	ServerMsgID string         `protobuf:"bytes,1,opt,name=serverMsgID" json:"serverMsgID,omitempty"`
	ClientMsgID string         `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	SendTime    int64          `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
	Modify      *sdkws.MsgData `protobuf:"bytes,4,opt,name=modify" json:"modify,omitempty"`
}

func (x *SendMsgResp) Reset() { *x = SendMsgResp{} }

func (x *SendMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMsgResp) GetServerMsgID() string {
	if x != nil {
		return x.ServerMsgID
	}
	return ""
}

func (x *SendMsgResp) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *SendMsgResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendMsgResp) GetModify() *sdkws.MsgData {
	if x != nil {
		return x.Modify
	}
	return nil
}

type SendSimpleMsgReq struct {
	MsgData *sdkws.MsgData `protobuf:"bytes,3,opt,name=msgData" json:"msgData,omitempty"`
}

func (x *SendSimpleMsgReq) Reset() { *x = SendSimpleMsgReq{} }

func (x *SendSimpleMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendSimpleMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendSimpleMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type SendSimpleMsgResp struct {
	ServerMsgID string         `protobuf:"bytes,1,opt,name=serverMsgID" json:"serverMsgID,omitempty"`
	ClientMsgID string         `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	SendTime    int64          `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
	Modify      *sdkws.MsgData `protobuf:"bytes,4,opt,name=modify" json:"modify,omitempty"`
}

func (x *SendSimpleMsgResp) Reset() { *x = SendSimpleMsgResp{} }

func (x *SendSimpleMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendSimpleMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendSimpleMsgResp) GetServerMsgID() string {
	if x != nil {
		return x.ServerMsgID
	}
	return ""
}

func (x *SendSimpleMsgResp) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *SendSimpleMsgResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendSimpleMsgResp) GetModify() *sdkws.MsgData {
	if x != nil {
		return x.Modify
	}
	return nil
}

type SetSendMsgStatusReq struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *SetSendMsgStatusReq) Reset() { *x = SetSendMsgStatusReq{} }

func (x *SetSendMsgStatusReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SetSendMsgStatusReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetSendMsgStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetSendMsgStatusResp struct {
}

func (x *SetSendMsgStatusResp) Reset() { *x = SetSendMsgStatusResp{} }

func (x *SetSendMsgStatusResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SetSendMsgStatusResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetSendMsgStatusReq struct {
}

func (x *GetSendMsgStatusReq) Reset() { *x = GetSendMsgStatusReq{} }

func (x *GetSendMsgStatusReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSendMsgStatusReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetSendMsgStatusResp struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *GetSendMsgStatusResp) Reset() { *x = GetSendMsgStatusResp{} }

func (x *GetSendMsgStatusResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSendMsgStatusResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSendMsgStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MsgDataToModifyByMQ struct {
	Messages       []*sdkws.MsgData `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	ConversationID string           `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
}

func (x *MsgDataToModifyByMQ) Reset() { *x = MsgDataToModifyByMQ{} }

func (x *MsgDataToModifyByMQ) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MsgDataToModifyByMQ) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MsgDataToModifyByMQ) GetMessages() []*sdkws.MsgData {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MsgDataToModifyByMQ) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type DelMsgsReq struct {
}

func (x *DelMsgsReq) Reset() { *x = DelMsgsReq{} }

func (x *DelMsgsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DelMsgsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DelMsgsResp struct {
}

func (x *DelMsgsResp) Reset() { *x = DelMsgsResp{} }

func (x *DelMsgsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DelMsgsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type RevokeMsgReq struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Seq            int64  `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	UserID         string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
}

func (x *RevokeMsgReq) Reset() { *x = RevokeMsgReq{} }

func (x *RevokeMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RevokeMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RevokeMsgReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *RevokeMsgReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RevokeMsgReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type RevokeMsgResp struct {
}

func (x *RevokeMsgResp) Reset() { *x = RevokeMsgResp{} }

func (x *RevokeMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RevokeMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type MarkMsgsAsReadReq struct {
	ConversationID string  `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs           []int64 `protobuf:"varint,2,rep,packed,name=seqs" json:"seqs,omitempty"`
	UserID         string  `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
}

func (x *MarkMsgsAsReadReq) Reset() { *x = MarkMsgsAsReadReq{} }

func (x *MarkMsgsAsReadReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MarkMsgsAsReadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MarkMsgsAsReadReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *MarkMsgsAsReadReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *MarkMsgsAsReadReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type MarkMsgsAsReadResp struct {
}

func (x *MarkMsgsAsReadResp) Reset() { *x = MarkMsgsAsReadResp{} }

func (x *MarkMsgsAsReadResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MarkMsgsAsReadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type MarkConversationAsReadReq struct {
	ConversationID string  `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	UserID         string  `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	HasReadSeq     int64   `protobuf:"varint,3,opt,name=hasReadSeq" json:"hasReadSeq,omitempty"`
	Seqs           []int64 `protobuf:"varint,4,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *MarkConversationAsReadReq) Reset() { *x = MarkConversationAsReadReq{} }

func (x *MarkConversationAsReadReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *MarkConversationAsReadReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MarkConversationAsReadReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *MarkConversationAsReadReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MarkConversationAsReadReq) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *MarkConversationAsReadReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type MarkConversationAsReadResp struct {
}

func (x *MarkConversationAsReadResp) Reset() { *x = MarkConversationAsReadResp{} }

func (x *MarkConversationAsReadResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *MarkConversationAsReadResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type SetConversationHasReadSeqReq struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	UserID         string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	HasReadSeq     int64  `protobuf:"varint,3,opt,name=hasReadSeq" json:"hasReadSeq,omitempty"`
	NoNotification bool   `protobuf:"varint,4,opt,name=noNotification" json:"noNotification,omitempty"`
}

func (x *SetConversationHasReadSeqReq) Reset() { *x = SetConversationHasReadSeqReq{} }

func (x *SetConversationHasReadSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetConversationHasReadSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetConversationHasReadSeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SetConversationHasReadSeqReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SetConversationHasReadSeqReq) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *SetConversationHasReadSeqReq) GetNoNotification() bool {
	if x != nil {
		return x.NoNotification
	}
	return false
}

type SetConversationHasReadSeqResp struct {
}

func (x *SetConversationHasReadSeqResp) Reset() { *x = SetConversationHasReadSeqResp{} }

func (x *SetConversationHasReadSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetConversationHasReadSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DeleteSyncOpt struct {
	IsSyncSelf  bool `protobuf:"varint,3,opt,name=IsSyncSelf" json:"IsSyncSelf,omitempty"`
	IsSyncOther bool `protobuf:"varint,4,opt,name=IsSyncOther" json:"IsSyncOther,omitempty"`
}

func (x *DeleteSyncOpt) Reset() { *x = DeleteSyncOpt{} }

func (x *DeleteSyncOpt) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteSyncOpt) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteSyncOpt) GetIsSyncSelf() bool {
	if x != nil {
		return x.IsSyncSelf
	}
	return false
}

func (x *DeleteSyncOpt) GetIsSyncOther() bool {
	if x != nil {
		return x.IsSyncOther
	}
	return false
}

type ClearConversationsMsgReq struct {
	ConversationIDs []string       `protobuf:"bytes,1,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
	UserID          string         `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	DeleteSyncOpt   *DeleteSyncOpt `protobuf:"bytes,3,opt,name=deleteSyncOpt" json:"deleteSyncOpt,omitempty"`
}

func (x *ClearConversationsMsgReq) Reset() { *x = ClearConversationsMsgReq{} }

func (x *ClearConversationsMsgReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ClearConversationsMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearConversationsMsgReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

func (x *ClearConversationsMsgReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ClearConversationsMsgReq) GetDeleteSyncOpt() *DeleteSyncOpt {
	if x != nil {
		return x.DeleteSyncOpt
	}
	return nil
}

type ClearConversationsMsgResp struct {
}

func (x *ClearConversationsMsgResp) Reset() { *x = ClearConversationsMsgResp{} }

func (x *ClearConversationsMsgResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ClearConversationsMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type UserClearAllMsgReq struct {
	UserID        string         `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	DeleteSyncOpt *DeleteSyncOpt `protobuf:"bytes,3,opt,name=deleteSyncOpt" json:"deleteSyncOpt,omitempty"`
}

func (x *UserClearAllMsgReq) Reset() { *x = UserClearAllMsgReq{} }

func (x *UserClearAllMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserClearAllMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserClearAllMsgReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserClearAllMsgReq) GetDeleteSyncOpt() *DeleteSyncOpt {
	if x != nil {
		return x.DeleteSyncOpt
	}
	return nil
}

type UserClearAllMsgResp struct {
}

func (x *UserClearAllMsgResp) Reset() { *x = UserClearAllMsgResp{} }

func (x *UserClearAllMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserClearAllMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DeleteMsgsReq struct {
	ConversationID string         `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs           []int64        `protobuf:"varint,2,rep,packed,name=seqs" json:"seqs,omitempty"`
	UserID         string         `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	DeleteSyncOpt  *DeleteSyncOpt `protobuf:"bytes,4,opt,name=deleteSyncOpt" json:"deleteSyncOpt,omitempty"`
}

func (x *DeleteMsgsReq) Reset() { *x = DeleteMsgsReq{} }

func (x *DeleteMsgsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteMsgsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteMsgsReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *DeleteMsgsReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *DeleteMsgsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeleteMsgsReq) GetDeleteSyncOpt() *DeleteSyncOpt {
	if x != nil {
		return x.DeleteSyncOpt
	}
	return nil
}

type DeleteMsgsResp struct {
}

func (x *DeleteMsgsResp) Reset() { *x = DeleteMsgsResp{} }

func (x *DeleteMsgsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteMsgsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DeleteMsgPhysicalReq struct {
	ConversationIDs []string `protobuf:"bytes,1,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
	Timestamp       int64    `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (x *DeleteMsgPhysicalReq) Reset() { *x = DeleteMsgPhysicalReq{} }

func (x *DeleteMsgPhysicalReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteMsgPhysicalReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteMsgPhysicalReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

func (x *DeleteMsgPhysicalReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeleteMsgPhysicalResp struct {
}

func (x *DeleteMsgPhysicalResp) Reset() { *x = DeleteMsgPhysicalResp{} }

func (x *DeleteMsgPhysicalResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteMsgPhysicalResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DeleteMsgPhysicalBySeqReq struct {
	ConversationID string  `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs           []int64 `protobuf:"varint,2,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *DeleteMsgPhysicalBySeqReq) Reset() { *x = DeleteMsgPhysicalBySeqReq{} }

func (x *DeleteMsgPhysicalBySeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteMsgPhysicalBySeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteMsgPhysicalBySeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *DeleteMsgPhysicalBySeqReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type DeleteMsgPhysicalBySeqResp struct {
}

func (x *DeleteMsgPhysicalBySeqResp) Reset() { *x = DeleteMsgPhysicalBySeqResp{} }

func (x *DeleteMsgPhysicalBySeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteMsgPhysicalBySeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetMaxSeqsReq struct {
	ConversationIDs []string `protobuf:"bytes,1,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
}

func (x *GetMaxSeqsReq) Reset() { *x = GetMaxSeqsReq{} }

func (x *GetMaxSeqsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMaxSeqsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMaxSeqsReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

type GetHasReadSeqsReq struct {
	UserID          string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationIDs []string `protobuf:"bytes,2,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
}

func (x *GetHasReadSeqsReq) Reset() { *x = GetHasReadSeqsReq{} }

func (x *GetHasReadSeqsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetHasReadSeqsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetHasReadSeqsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetHasReadSeqsReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

type SeqsInfoResp struct {
	MaxSeqs map[string]int64 `protobuf:"bytes,1,rep,name=maxSeqs" json:"maxSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (x *SeqsInfoResp) Reset() { *x = SeqsInfoResp{} }

func (x *SeqsInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SeqsInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SeqsInfoResp) GetMaxSeqs() map[string]int64 {
	if x != nil {
		return x.MaxSeqs
	}
	return nil
}

type GetMsgByConversationIDsReq struct {
	ConversationIDs []string         `protobuf:"bytes,1,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
	MaxSeqs         map[string]int64 `protobuf:"bytes,2,rep,name=maxSeqs" json:"maxSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (x *GetMsgByConversationIDsReq) Reset() { *x = GetMsgByConversationIDsReq{} }

func (x *GetMsgByConversationIDsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetMsgByConversationIDsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMsgByConversationIDsReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

func (x *GetMsgByConversationIDsReq) GetMaxSeqs() map[string]int64 {
	if x != nil {
		return x.MaxSeqs
	}
	return nil
}

type GetMsgByConversationIDsResp struct {
	MsgDatas map[string]*sdkws.MsgData `protobuf:"bytes,1,rep,name=msgDatas" json:"msgDatas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *GetMsgByConversationIDsResp) Reset() { *x = GetMsgByConversationIDsResp{} }

func (x *GetMsgByConversationIDsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetMsgByConversationIDsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMsgByConversationIDsResp) GetMsgDatas() map[string]*sdkws.MsgData {
	if x != nil {
		return x.MsgDatas
	}
	return nil
}

type GetConversationMaxSeqReq struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
}

func (x *GetConversationMaxSeqReq) Reset() { *x = GetConversationMaxSeqReq{} }

func (x *GetConversationMaxSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationMaxSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConversationMaxSeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type GetConversationMaxSeqResp struct {
	MaxSeq int64 `protobuf:"varint,1,opt,name=maxSeq" json:"maxSeq,omitempty"`
}

func (x *GetConversationMaxSeqResp) Reset() { *x = GetConversationMaxSeqResp{} }

func (x *GetConversationMaxSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationMaxSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConversationMaxSeqResp) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type GetConversationsHasReadAndMaxSeqReq struct {
	UserID          string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationIDs []string `protobuf:"bytes,2,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
	ReturnPinned    bool     `protobuf:"varint,3,opt,name=returnPinned" json:"returnPinned,omitempty"`
}

func (x *GetConversationsHasReadAndMaxSeqReq) Reset() { *x = GetConversationsHasReadAndMaxSeqReq{} }

func (x *GetConversationsHasReadAndMaxSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationsHasReadAndMaxSeqReq) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GetConversationsHasReadAndMaxSeqReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetConversationsHasReadAndMaxSeqReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

func (x *GetConversationsHasReadAndMaxSeqReq) GetReturnPinned() bool {
	if x != nil {
		return x.ReturnPinned
	}
	return false
}

type Seqs struct {
	MaxSeq     int64 `protobuf:"varint,1,opt,name=maxSeq" json:"maxSeq,omitempty"`
	HasReadSeq int64 `protobuf:"varint,2,opt,name=hasReadSeq" json:"hasReadSeq,omitempty"`
	MaxSeqTime int64 `protobuf:"varint,3,opt,name=maxSeqTime" json:"maxSeqTime,omitempty"`
}

func (x *Seqs) Reset() { *x = Seqs{} }

func (x *Seqs) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Seqs) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Seqs) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Seqs) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *Seqs) GetMaxSeqTime() int64 {
	if x != nil {
		return x.MaxSeqTime
	}
	return 0
}

type GetConversationsHasReadAndMaxSeqResp struct {
	Seqs                  map[string]*Seqs `protobuf:"bytes,1,rep,name=seqs" json:"seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PinnedConversationIDs []string         `protobuf:"bytes,2,rep,name=pinnedConversationIDs" json:"pinnedConversationIDs,omitempty"`
}

func (x *GetConversationsHasReadAndMaxSeqResp) Reset() { *x = GetConversationsHasReadAndMaxSeqResp{} }

func (x *GetConversationsHasReadAndMaxSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetConversationsHasReadAndMaxSeqResp) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GetConversationsHasReadAndMaxSeqResp) GetSeqs() map[string]*Seqs {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *GetConversationsHasReadAndMaxSeqResp) GetPinnedConversationIDs() []string {
	if x != nil {
		return x.PinnedConversationIDs
	}
	return nil
}

type GetActiveUserReq struct {
	Start      int64                    `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End        int64                    `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	Ase        bool                     `protobuf:"varint,3,opt,name=ase" json:"ase,omitempty"`
	Group      bool                     `protobuf:"varint,4,opt,name=group" json:"group,omitempty"`
	Pagination *sdkws.RequestPagination `protobuf:"bytes,5,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *GetActiveUserReq) Reset() { *x = GetActiveUserReq{} }

func (x *GetActiveUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetActiveUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveUserReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetActiveUserReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GetActiveUserReq) GetAse() bool {
	if x != nil {
		return x.Ase
	}
	return false
}

func (x *GetActiveUserReq) GetGroup() bool {
	if x != nil {
		return x.Group
	}
	return false
}

func (x *GetActiveUserReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ActiveUser struct {
	User  *sdkws.UserInfo `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Count int64           `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *ActiveUser) Reset() { *x = ActiveUser{} }

func (x *ActiveUser) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ActiveUser) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ActiveUser) GetUser() *sdkws.UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ActiveUser) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetActiveUserResp struct {
	MsgCount  int64            `protobuf:"varint,1,opt,name=msgCount" json:"msgCount,omitempty"`
	UserCount int64            `protobuf:"varint,2,opt,name=userCount" json:"userCount,omitempty"`
	DateCount map[string]int64 `protobuf:"bytes,3,rep,name=dateCount" json:"dateCount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Users     []*ActiveUser    `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
}

func (x *GetActiveUserResp) Reset() { *x = GetActiveUserResp{} }

func (x *GetActiveUserResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetActiveUserResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveUserResp) GetMsgCount() int64 {
	if x != nil {
		return x.MsgCount
	}
	return 0
}

func (x *GetActiveUserResp) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *GetActiveUserResp) GetDateCount() map[string]int64 {
	if x != nil {
		return x.DateCount
	}
	return nil
}

func (x *GetActiveUserResp) GetUsers() []*ActiveUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetActiveGroupReq struct {
	Start      int64                    `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End        int64                    `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	Ase        bool                     `protobuf:"varint,3,opt,name=ase" json:"ase,omitempty"`
	Pagination *sdkws.RequestPagination `protobuf:"bytes,4,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *GetActiveGroupReq) Reset() { *x = GetActiveGroupReq{} }

func (x *GetActiveGroupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetActiveGroupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveGroupReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetActiveGroupReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GetActiveGroupReq) GetAse() bool {
	if x != nil {
		return x.Ase
	}
	return false
}

func (x *GetActiveGroupReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ActiveGroup struct {
	Group *sdkws.GroupInfo `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Count int64            `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *ActiveGroup) Reset() { *x = ActiveGroup{} }

func (x *ActiveGroup) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ActiveGroup) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ActiveGroup) GetGroup() *sdkws.GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *ActiveGroup) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetActiveGroupResp struct {
	MsgCount   int64            `protobuf:"varint,1,opt,name=msgCount" json:"msgCount,omitempty"`
	GroupCount int64            `protobuf:"varint,2,opt,name=groupCount" json:"groupCount,omitempty"`
	DateCount  map[string]int64 `protobuf:"bytes,3,rep,name=dateCount" json:"dateCount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Groups     []*ActiveGroup   `protobuf:"bytes,4,rep,name=groups" json:"groups,omitempty"`
}

func (x *GetActiveGroupResp) Reset() { *x = GetActiveGroupResp{} }

func (x *GetActiveGroupResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetActiveGroupResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveGroupResp) GetMsgCount() int64 {
	if x != nil {
		return x.MsgCount
	}
	return 0
}

func (x *GetActiveGroupResp) GetGroupCount() int64 {
	if x != nil {
		return x.GroupCount
	}
	return 0
}

func (x *GetActiveGroupResp) GetDateCount() map[string]int64 {
	if x != nil {
		return x.DateCount
	}
	return nil
}

func (x *GetActiveGroupResp) GetGroups() []*ActiveGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type SearchMessageReq struct {
	SendID      string                   `protobuf:"bytes,1,opt,name=sendID" json:"sendID,omitempty"` //发送者ID
	RecvID      string                   `protobuf:"bytes,2,opt,name=recvID" json:"recvID,omitempty"` //接收者ID
	ContentType int32                    `protobuf:"varint,3,opt,name=contentType" json:"contentType,omitempty"`
	SendTime    string                   `protobuf:"bytes,4,opt,name=sendTime" json:"sendTime,omitempty"`
	SessionType int32                    `protobuf:"varint,5,opt,name=sessionType" json:"sessionType,omitempty"`
	Pagination  *sdkws.RequestPagination `protobuf:"bytes,6,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *SearchMessageReq) Reset() { *x = SearchMessageReq{} }

func (x *SearchMessageReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchMessageReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchMessageReq) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *SearchMessageReq) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *SearchMessageReq) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *SearchMessageReq) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

func (x *SearchMessageReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *SearchMessageReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchChatLog struct {
	ChatLog   *ChatLog `protobuf:"bytes,1,opt,name=chatLog" json:"chatLog,omitempty"`
	IsRevoked bool     `protobuf:"varint,2,opt,name=isRevoked" json:"isRevoked,omitempty"`
}

func (x *SearchChatLog) Reset() { *x = SearchChatLog{} }

func (x *SearchChatLog) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchChatLog) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchChatLog) GetChatLog() *ChatLog {
	if x != nil {
		return x.ChatLog
	}
	return nil
}

func (x *SearchChatLog) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

type SearchedMsgData struct {
	MsgData   *sdkws.MsgData `protobuf:"bytes,1,opt,name=msgData" json:"msgData,omitempty"`
	IsRevoked bool           `protobuf:"varint,2,opt,name=isRevoked" json:"isRevoked,omitempty"`
}

func (x *SearchedMsgData) Reset() { *x = SearchedMsgData{} }

func (x *SearchedMsgData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchedMsgData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchedMsgData) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *SearchedMsgData) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

type SearchMessageResp struct {
	ChatLogs    []*SearchChatLog `protobuf:"bytes,1,rep,name=chatLogs" json:"chatLogs,omitempty"`
	ChatLogsNum int32            `protobuf:"varint,2,opt,name=chatLogsNum" json:"chatLogsNum,omitempty"`
}

func (x *SearchMessageResp) Reset() { *x = SearchMessageResp{} }

func (x *SearchMessageResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchMessageResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchMessageResp) GetChatLogs() []*SearchChatLog {
	if x != nil {
		return x.ChatLogs
	}
	return nil
}

func (x *SearchMessageResp) GetChatLogsNum() int32 {
	if x != nil {
		return x.ChatLogsNum
	}
	return 0
}

type ChatLog struct {
	ServerMsgID      string `protobuf:"bytes,1,opt,name=serverMsgID" json:"serverMsgID,omitempty"`
	ClientMsgID      string `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	SendID           string `protobuf:"bytes,3,opt,name=sendID" json:"sendID,omitempty"`
	RecvID           string `protobuf:"bytes,4,opt,name=recvID" json:"recvID,omitempty"`
	GroupID          string `protobuf:"bytes,5,opt,name=groupID" json:"groupID,omitempty"`
	RecvNickname     string `protobuf:"bytes,6,opt,name=recvNickname" json:"recvNickname,omitempty"`
	SenderPlatformID int32  `protobuf:"varint,7,opt,name=senderPlatformID" json:"senderPlatformID,omitempty"`
	SenderNickname   string `protobuf:"bytes,8,opt,name=senderNickname" json:"senderNickname,omitempty"`
	SenderFaceURL    string `protobuf:"bytes,9,opt,name=senderFaceURL" json:"senderFaceURL,omitempty"`
	GroupName        string `protobuf:"bytes,10,opt,name=groupName" json:"groupName,omitempty"`
	SessionType      int32  `protobuf:"varint,11,opt,name=sessionType" json:"sessionType,omitempty"`
	MsgFrom          int32  `protobuf:"varint,12,opt,name=msgFrom" json:"msgFrom,omitempty"`
	ContentType      int32  `protobuf:"varint,13,opt,name=contentType" json:"contentType,omitempty"`
	Content          string `protobuf:"bytes,14,opt,name=content" json:"content,omitempty"`
	Status           int32  `protobuf:"varint,15,opt,name=status" json:"status,omitempty"`
	SendTime         int64  `protobuf:"varint,16,opt,name=sendTime" json:"sendTime,omitempty"`
	CreateTime       int64  `protobuf:"varint,17,opt,name=createTime" json:"createTime,omitempty"`
	Ex               string `protobuf:"bytes,18,opt,name=ex" json:"ex,omitempty"`
	GroupFaceURL     string `protobuf:"bytes,19,opt,name=groupFaceURL" json:"groupFaceURL,omitempty"`
	GroupMemberCount uint32 `protobuf:"varint,20,opt,name=groupMemberCount" json:"groupMemberCount,omitempty"`
	Seq              int64  `protobuf:"varint,21,opt,name=seq" json:"seq,omitempty"`
	GroupOwner       string `protobuf:"bytes,22,opt,name=groupOwner" json:"groupOwner,omitempty"`
	GroupType        int32  `protobuf:"varint,23,opt,name=groupType" json:"groupType,omitempty"`
}

func (x *ChatLog) Reset() { *x = ChatLog{} }

func (x *ChatLog) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatLog) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatLog) GetServerMsgID() string {
	if x != nil {
		return x.ServerMsgID
	}
	return ""
}

func (x *ChatLog) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *ChatLog) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *ChatLog) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *ChatLog) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *ChatLog) GetRecvNickname() string {
	if x != nil {
		return x.RecvNickname
	}
	return ""
}

func (x *ChatLog) GetSenderPlatformID() int32 {
	if x != nil {
		return x.SenderPlatformID
	}
	return 0
}

func (x *ChatLog) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *ChatLog) GetSenderFaceURL() string {
	if x != nil {
		return x.SenderFaceURL
	}
	return ""
}

func (x *ChatLog) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ChatLog) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ChatLog) GetMsgFrom() int32 {
	if x != nil {
		return x.MsgFrom
	}
	return 0
}

func (x *ChatLog) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *ChatLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatLog) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChatLog) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ChatLog) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ChatLog) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *ChatLog) GetGroupFaceURL() string {
	if x != nil {
		return x.GroupFaceURL
	}
	return ""
}

func (x *ChatLog) GetGroupMemberCount() uint32 {
	if x != nil {
		return x.GroupMemberCount
	}
	return 0
}

func (x *ChatLog) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatLog) GetGroupOwner() string {
	if x != nil {
		return x.GroupOwner
	}
	return ""
}

func (x *ChatLog) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

type BatchSendMessageReq struct {
	RecvIDList []string       `protobuf:"bytes,1,rep,name=recvIDList" json:"recvIDList,omitempty"`
	MsgData    *sdkws.MsgData `protobuf:"bytes,2,opt,name=msgData" json:"msgData,omitempty"`
}

func (x *BatchSendMessageReq) Reset() { *x = BatchSendMessageReq{} }

func (x *BatchSendMessageReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BatchSendMessageReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchSendMessageReq) GetRecvIDList() []string {
	if x != nil {
		return x.RecvIDList
	}
	return nil
}

func (x *BatchSendMessageReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type BatchSendMessageResp struct {
}

func (x *BatchSendMessageResp) Reset() { *x = BatchSendMessageResp{} }

func (x *BatchSendMessageResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BatchSendMessageResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetServerTimeReq struct {
}

func (x *GetServerTimeReq) Reset() { *x = GetServerTimeReq{} }

func (x *GetServerTimeReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetServerTimeReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetServerTimeResp struct {
	ServerTime int64 `protobuf:"varint,1,opt,name=serverTime" json:"serverTime,omitempty"`
}

func (x *GetServerTimeResp) Reset() { *x = GetServerTimeResp{} }

func (x *GetServerTimeResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetServerTimeResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetServerTimeResp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ClearMsgReq struct {
	Conversations []string `protobuf:"bytes,1,rep,name=conversations" json:"conversations,omitempty"`
}

func (x *ClearMsgReq) Reset() { *x = ClearMsgReq{} }

func (x *ClearMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearMsgReq) GetConversations() []string {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ClearMsgResp struct {
}

func (x *ClearMsgResp) Reset() { *x = ClearMsgResp{} }

func (x *ClearMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DestructMsgsReq struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Limit     int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (x *DestructMsgsReq) Reset() { *x = DestructMsgsReq{} }

func (x *DestructMsgsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DestructMsgsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DestructMsgsReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DestructMsgsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DestructMsgsResp struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (x *DestructMsgsResp) Reset() { *x = DestructMsgsResp{} }

func (x *DestructMsgsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DestructMsgsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DestructMsgsResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetUserConversationsMinSeqReq struct {
	UserIDs        []string `protobuf:"bytes,1,rep,name=userIDs" json:"userIDs,omitempty"`
	ConversationID string   `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	Seq            int64    `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
}

func (x *SetUserConversationsMinSeqReq) Reset() { *x = SetUserConversationsMinSeqReq{} }

func (x *SetUserConversationsMinSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationsMinSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetUserConversationsMinSeqReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

func (x *SetUserConversationsMinSeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SetUserConversationsMinSeqReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SetUserConversationsMinSeqResp struct {
}

func (x *SetUserConversationsMinSeqResp) Reset() { *x = SetUserConversationsMinSeqResp{} }

func (x *SetUserConversationsMinSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationsMinSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type ConversationSeqs struct {
	ConversationID string  `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs           []int64 `protobuf:"varint,3,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *ConversationSeqs) Reset() { *x = ConversationSeqs{} }

func (x *ConversationSeqs) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ConversationSeqs) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationSeqs) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ConversationSeqs) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type GetSeqMessageReq struct {
	UserID        string              `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Conversations []*ConversationSeqs `protobuf:"bytes,2,rep,name=conversations" json:"conversations,omitempty"`
	Order         sdkws.PullOrder     `protobuf:"varint,3,opt,name=order" json:"order,omitempty"`
}

func (x *GetSeqMessageReq) Reset() { *x = GetSeqMessageReq{} }

func (x *GetSeqMessageReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSeqMessageReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSeqMessageReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetSeqMessageReq) GetConversations() []*ConversationSeqs {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *GetSeqMessageReq) GetOrder() sdkws.PullOrder {
	if x != nil {
		return x.Order
	}
	return sdkws.PullOrder_PullOrderAsc
}

type GetSeqMessageResp struct {
	Msgs             map[string]*sdkws.PullMsgs `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NotificationMsgs map[string]*sdkws.PullMsgs `protobuf:"bytes,2,rep,name=notificationMsgs" json:"notificationMsgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *GetSeqMessageResp) Reset() { *x = GetSeqMessageResp{} }

func (x *GetSeqMessageResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSeqMessageResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSeqMessageResp) GetMsgs() map[string]*sdkws.PullMsgs {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *GetSeqMessageResp) GetNotificationMsgs() map[string]*sdkws.PullMsgs {
	if x != nil {
		return x.NotificationMsgs
	}
	return nil
}

type GetActiveConversationReq struct {
	ConversationIDs []string `protobuf:"bytes,1,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
	Limit           int64    `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (x *GetActiveConversationReq) Reset() { *x = GetActiveConversationReq{} }

func (x *GetActiveConversationReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetActiveConversationReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveConversationReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

func (x *GetActiveConversationReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ActiveConversation struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	LastTime       int64  `protobuf:"varint,2,opt,name=lastTime" json:"lastTime,omitempty"`
	MaxSeq         int64  `protobuf:"varint,3,opt,name=maxSeq" json:"maxSeq,omitempty"`
}

func (x *ActiveConversation) Reset() { *x = ActiveConversation{} }

func (x *ActiveConversation) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ActiveConversation) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ActiveConversation) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ActiveConversation) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

func (x *ActiveConversation) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type GetActiveConversationResp struct {
	Conversations []*ActiveConversation `protobuf:"bytes,1,rep,name=conversations" json:"conversations,omitempty"`
}

func (x *GetActiveConversationResp) Reset() { *x = GetActiveConversationResp{} }

func (x *GetActiveConversationResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetActiveConversationResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetActiveConversationResp) GetConversations() []*ActiveConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type SetUserConversationMaxSeqReq struct {
	ConversationID string   `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	OwnerUserID    []string `protobuf:"bytes,2,rep,name=ownerUserID" json:"ownerUserID,omitempty"`
	MaxSeq         int64    `protobuf:"varint,3,opt,name=maxSeq" json:"maxSeq,omitempty"`
}

func (x *SetUserConversationMaxSeqReq) Reset() { *x = SetUserConversationMaxSeqReq{} }

func (x *SetUserConversationMaxSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationMaxSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetUserConversationMaxSeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SetUserConversationMaxSeqReq) GetOwnerUserID() []string {
	if x != nil {
		return x.OwnerUserID
	}
	return nil
}

func (x *SetUserConversationMaxSeqReq) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type SetUserConversationMaxSeqResp struct {
}

func (x *SetUserConversationMaxSeqResp) Reset() { *x = SetUserConversationMaxSeqResp{} }

func (x *SetUserConversationMaxSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationMaxSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type SetUserConversationMinSeqReq struct {
	ConversationID string   `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	OwnerUserID    []string `protobuf:"bytes,2,rep,name=ownerUserID" json:"ownerUserID,omitempty"`
	MinSeq         int64    `protobuf:"varint,3,opt,name=minSeq" json:"minSeq,omitempty"`
}

func (x *SetUserConversationMinSeqReq) Reset() { *x = SetUserConversationMinSeqReq{} }

func (x *SetUserConversationMinSeqReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationMinSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetUserConversationMinSeqReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SetUserConversationMinSeqReq) GetOwnerUserID() []string {
	if x != nil {
		return x.OwnerUserID
	}
	return nil
}

func (x *SetUserConversationMinSeqReq) GetMinSeq() int64 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

type SetUserConversationMinSeqResp struct {
}

func (x *SetUserConversationMinSeqResp) Reset() { *x = SetUserConversationMinSeqResp{} }

func (x *SetUserConversationMinSeqResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetUserConversationMinSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetLastMessageSeqByTimeReq struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Time           int64  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
}

func (x *GetLastMessageSeqByTimeReq) Reset() { *x = GetLastMessageSeqByTimeReq{} }

func (x *GetLastMessageSeqByTimeReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetLastMessageSeqByTimeReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetLastMessageSeqByTimeReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *GetLastMessageSeqByTimeReq) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type GetLastMessageSeqByTimeResp struct {
	Seq int64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
}

func (x *GetLastMessageSeqByTimeResp) Reset() { *x = GetLastMessageSeqByTimeResp{} }

func (x *GetLastMessageSeqByTimeResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetLastMessageSeqByTimeResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetLastMessageSeqByTimeResp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GetLastMessageReq struct {
	UserID          string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationIDs []string `protobuf:"bytes,2,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
}

func (x *GetLastMessageReq) Reset() { *x = GetLastMessageReq{} }

func (x *GetLastMessageReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetLastMessageReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetLastMessageReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetLastMessageReq) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

type GetLastMessageResp struct {
	Msgs map[string]*sdkws.MsgData `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *GetLastMessageResp) Reset() { *x = GetLastMessageResp{} }

func (x *GetLastMessageResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetLastMessageResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetLastMessageResp) GetMsgs() map[string]*sdkws.MsgData {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type MessageService interface {
	GetMaxSeq(ctx context.Context, req *sdkws.GetMaxSeqReq) (res *sdkws.GetMaxSeqResp, err error)
	GetMaxSeqs(ctx context.Context, req *GetMaxSeqsReq) (res *SeqsInfoResp, err error)
	GetHasReadSeqs(ctx context.Context, req *GetHasReadSeqsReq) (res *SeqsInfoResp, err error)
	GetMsgByConversationIDs(ctx context.Context, req *GetMsgByConversationIDsReq) (res *GetMsgByConversationIDsResp, err error)
	GetConversationMaxSeq(ctx context.Context, req *GetConversationMaxSeqReq) (res *GetConversationMaxSeqResp, err error)
	PullMessageBySeqs(ctx context.Context, req *sdkws.PullMessageBySeqsReq) (res *sdkws.PullMessageBySeqsResp, err error)
	GetSeqMessage(ctx context.Context, req *GetSeqMessageReq) (res *GetSeqMessageResp, err error)
	SearchMessage(ctx context.Context, req *SearchMessageReq) (res *SearchMessageResp, err error)
	SendMessages(ctx context.Context, req *sdkws.SendMessageReq) (res *sdkws.SendMessageResp, err error)
	SendSimpleMsg(ctx context.Context, req *SendSimpleMsgReq) (res *SendSimpleMsgResp, err error)
	SetUserConversationsMinSeq(ctx context.Context, req *SetUserConversationsMinSeqReq) (res *SetUserConversationsMinSeqResp, err error)
	ClearConversationsMsg(ctx context.Context, req *ClearConversationsMsgReq) (res *ClearConversationsMsgResp, err error)
	UserClearAllMsg(ctx context.Context, req *UserClearAllMsgReq) (res *UserClearAllMsgResp, err error)
	DeleteMsgs(ctx context.Context, req *DeleteMsgsReq) (res *DeleteMsgsResp, err error)
	DeleteMsgPhysicalBySeq(ctx context.Context, req *DeleteMsgPhysicalBySeqReq) (res *DeleteMsgPhysicalBySeqResp, err error)
	DeleteMsgPhysical(ctx context.Context, req *DeleteMsgPhysicalReq) (res *DeleteMsgPhysicalResp, err error)
	SetSendMsgStatus(ctx context.Context, req *SetSendMsgStatusReq) (res *SetSendMsgStatusResp, err error)
	GetSendMsgStatus(ctx context.Context, req *GetSendMsgStatusReq) (res *GetSendMsgStatusResp, err error)
	RevokeMsg(ctx context.Context, req *RevokeMsgReq) (res *RevokeMsgResp, err error)
	MarkMsgsAsRead(ctx context.Context, req *MarkMsgsAsReadReq) (res *MarkMsgsAsReadResp, err error)
	MarkConversationAsRead(ctx context.Context, req *MarkConversationAsReadReq) (res *MarkConversationAsReadResp, err error)
	SetConversationHasReadSeq(ctx context.Context, req *SetConversationHasReadSeqReq) (res *SetConversationHasReadSeqResp, err error)
	GetConversationsHasReadAndMaxSeq(ctx context.Context, req *GetConversationsHasReadAndMaxSeqReq) (res *GetConversationsHasReadAndMaxSeqResp, err error)
	GetActiveUser(ctx context.Context, req *GetActiveUserReq) (res *GetActiveUserResp, err error)
	GetActiveGroup(ctx context.Context, req *GetActiveGroupReq) (res *GetActiveGroupResp, err error)
	GetServerTime(ctx context.Context, req *GetServerTimeReq) (res *GetServerTimeResp, err error)
	ClearMsg(ctx context.Context, req *ClearMsgReq) (res *ClearMsgResp, err error)
	DestructMsgs(ctx context.Context, req *DestructMsgsReq) (res *DestructMsgsResp, err error)
	GetActiveConversation(ctx context.Context, req *GetActiveConversationReq) (res *GetActiveConversationResp, err error)
	SetUserConversationMaxSeq(ctx context.Context, req *SetUserConversationMaxSeqReq) (res *SetUserConversationMaxSeqResp, err error)
	SetUserConversationMinSeq(ctx context.Context, req *SetUserConversationMinSeqReq) (res *SetUserConversationMinSeqResp, err error)
	GetLastMessageSeqByTime(ctx context.Context, req *GetLastMessageSeqByTimeReq) (res *GetLastMessageSeqByTimeResp, err error)
	GetLastMessage(ctx context.Context, req *GetLastMessageReq) (res *GetLastMessageResp, err error)
}
