// Code generated by Kitex v0.15.2. DO NOT EDIT.

package message

import (
	"context"
	"github.com/rhp-QE/roc-im-server/kitex_gen/sdkws"
)

type MessageService interface {
	BatchSendMessage(ctx context.Context, req *sdkws.BatchSendMessageRequest) (res *sdkws.BatchSendMessageResponse, err error)
	BatchChangeMessages(ctx context.Context, req *sdkws.BatchChangeMessagesRequest) (res *sdkws.BatchChangeMessagesResponse, err error)
	FetchConvMessageList(ctx context.Context, req *sdkws.FetchConvMessageListRequest) (res *sdkws.FetchConvMessageListResponse, err error)
	BatchGetMessages(ctx context.Context, req *sdkws.BatchGetMessagesRequest) (res *sdkws.BatchGetMessagesResponse, err error)
}
