// Code generated by Kitex v0.13.1. DO NOT EDIT.

package sdkws

import (
	"strconv"

	"github.com/cloudwego/prutal"
)

// /////////////////////////////////base end/////////////////////////////////////
type PullOrder int32

const (
	PullOrder_PullOrderAsc  PullOrder = 0
	PullOrder_PullOrderDesc PullOrder = 1
)

// Enum value maps for PullOrder.
var PullOrder_name = map[int32]string{
	0: "PullOrderAsc",
	1: "PullOrderDesc",
}

var PullOrder_value = map[string]int32{
	"PullOrderAsc":  0,
	"PullOrderDesc": 1,
}

func (x PullOrder) String() string {
	s, ok := PullOrder_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type GroupInfo struct {
	GroupID                string `protobuf:"bytes,1,opt,name=groupID" json:"groupID,omitempty"`
	GroupName              string `protobuf:"bytes,2,opt,name=groupName" json:"groupName,omitempty"`
	Notification           string `protobuf:"bytes,3,opt,name=notification" json:"notification,omitempty"`
	Introduction           string `protobuf:"bytes,4,opt,name=introduction" json:"introduction,omitempty"`
	FaceURL                string `protobuf:"bytes,5,opt,name=faceURL" json:"faceURL,omitempty"`
	OwnerUserID            string `protobuf:"bytes,6,opt,name=ownerUserID" json:"ownerUserID,omitempty"`
	CreateTime             int64  `protobuf:"varint,7,opt,name=createTime" json:"createTime,omitempty"`
	MemberCount            uint32 `protobuf:"varint,8,opt,name=memberCount" json:"memberCount,omitempty"`
	Ex                     string `protobuf:"bytes,9,opt,name=ex" json:"ex,omitempty"`
	Status                 int32  `protobuf:"varint,10,opt,name=status" json:"status,omitempty"`
	CreatorUserID          string `protobuf:"bytes,11,opt,name=creatorUserID" json:"creatorUserID,omitempty"`
	GroupType              int32  `protobuf:"varint,12,opt,name=groupType" json:"groupType,omitempty"`
	NeedVerification       int32  `protobuf:"varint,13,opt,name=needVerification" json:"needVerification,omitempty"`
	LookMemberInfo         int32  `protobuf:"varint,14,opt,name=lookMemberInfo" json:"lookMemberInfo,omitempty"`
	ApplyMemberFriend      int32  `protobuf:"varint,15,opt,name=applyMemberFriend" json:"applyMemberFriend,omitempty"`
	NotificationUpdateTime int64  `protobuf:"varint,16,opt,name=notificationUpdateTime" json:"notificationUpdateTime,omitempty"`
	NotificationUserID     string `protobuf:"bytes,17,opt,name=notificationUserID" json:"notificationUserID,omitempty"`
}

func (x *GroupInfo) Reset() { *x = GroupInfo{} }

func (x *GroupInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *GroupInfo) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *GroupInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *GroupInfo) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

func (x *GroupInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupInfo) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *GroupInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfo) GetCreatorUserID() string {
	if x != nil {
		return x.CreatorUserID
	}
	return ""
}

func (x *GroupInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupInfo) GetNeedVerification() int32 {
	if x != nil {
		return x.NeedVerification
	}
	return 0
}

func (x *GroupInfo) GetLookMemberInfo() int32 {
	if x != nil {
		return x.LookMemberInfo
	}
	return 0
}

func (x *GroupInfo) GetApplyMemberFriend() int32 {
	if x != nil {
		return x.ApplyMemberFriend
	}
	return 0
}

func (x *GroupInfo) GetNotificationUpdateTime() int64 {
	if x != nil {
		return x.NotificationUpdateTime
	}
	return 0
}

func (x *GroupInfo) GetNotificationUserID() string {
	if x != nil {
		return x.NotificationUserID
	}
	return ""
}

type GroupInfoForSet struct {
	GroupID           string `protobuf:"bytes,1,opt,name=groupID" json:"groupID,omitempty"`
	GroupName         string `protobuf:"bytes,2,opt,name=groupName" json:"groupName,omitempty"`
	Notification      string `protobuf:"bytes,3,opt,name=notification" json:"notification,omitempty"`
	Introduction      string `protobuf:"bytes,4,opt,name=introduction" json:"introduction,omitempty"`
	FaceURL           string `protobuf:"bytes,5,opt,name=faceURL" json:"faceURL,omitempty"`
	Ex                string `protobuf:"bytes,6,opt,name=ex" json:"ex,omitempty"`
	NeedVerification  int32  `protobuf:"varint,7,opt,name=needVerification" json:"needVerification,omitempty"`
	LookMemberInfo    int32  `protobuf:"varint,8,opt,name=lookMemberInfo" json:"lookMemberInfo,omitempty"`
	ApplyMemberFriend int32  `protobuf:"varint,9,opt,name=applyMemberFriend" json:"applyMemberFriend,omitempty"`
}

func (x *GroupInfoForSet) Reset() { *x = GroupInfoForSet{} }

func (x *GroupInfoForSet) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupInfoForSet) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupInfoForSet) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupInfoForSet) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfoForSet) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *GroupInfoForSet) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *GroupInfoForSet) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *GroupInfoForSet) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *GroupInfoForSet) GetNeedVerification() int32 {
	if x != nil {
		return x.NeedVerification
	}
	return 0
}

func (x *GroupInfoForSet) GetLookMemberInfo() int32 {
	if x != nil {
		return x.LookMemberInfo
	}
	return 0
}

func (x *GroupInfoForSet) GetApplyMemberFriend() int32 {
	if x != nil {
		return x.ApplyMemberFriend
	}
	return 0
}

type GroupMemberFullInfo struct {
	GroupID        string `protobuf:"bytes,1,opt,name=groupID" json:"groupID,omitempty"`
	UserID         string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	RoleLevel      int32  `protobuf:"varint,3,opt,name=roleLevel" json:"roleLevel,omitempty"`
	JoinTime       int64  `protobuf:"varint,4,opt,name=joinTime" json:"joinTime,omitempty"`
	Nickname       string `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	FaceURL        string `protobuf:"bytes,6,opt,name=faceURL" json:"faceURL,omitempty"`
	AppMangerLevel int32  `protobuf:"varint,7,opt,name=appMangerLevel" json:"appMangerLevel,omitempty"` //if >0
	JoinSource     int32  `protobuf:"varint,8,opt,name=joinSource" json:"joinSource,omitempty"`
	OperatorUserID string `protobuf:"bytes,9,opt,name=operatorUserID" json:"operatorUserID,omitempty"`
	Ex             string `protobuf:"bytes,10,opt,name=ex" json:"ex,omitempty"`
	MuteEndTime    int64  `protobuf:"varint,11,opt,name=muteEndTime" json:"muteEndTime,omitempty"`
	InviterUserID  string `protobuf:"bytes,12,opt,name=inviterUserID" json:"inviterUserID,omitempty"`
}

func (x *GroupMemberFullInfo) Reset() { *x = GroupMemberFullInfo{} }

func (x *GroupMemberFullInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupMemberFullInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupMemberFullInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupMemberFullInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GroupMemberFullInfo) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *GroupMemberFullInfo) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *GroupMemberFullInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMemberFullInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *GroupMemberFullInfo) GetAppMangerLevel() int32 {
	if x != nil {
		return x.AppMangerLevel
	}
	return 0
}

func (x *GroupMemberFullInfo) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupMemberFullInfo) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *GroupMemberFullInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *GroupMemberFullInfo) GetMuteEndTime() int64 {
	if x != nil {
		return x.MuteEndTime
	}
	return 0
}

func (x *GroupMemberFullInfo) GetInviterUserID() string {
	if x != nil {
		return x.InviterUserID
	}
	return ""
}

type PublicUserInfo struct {
	UserID   string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	FaceURL  string `protobuf:"bytes,3,opt,name=faceURL" json:"faceURL,omitempty"`
	Ex       string `protobuf:"bytes,4,opt,name=ex" json:"ex,omitempty"`
}

func (x *PublicUserInfo) Reset() { *x = PublicUserInfo{} }

func (x *PublicUserInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PublicUserInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PublicUserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PublicUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PublicUserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *PublicUserInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type UserInfo struct {
	UserID           string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname         string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	FaceURL          string `protobuf:"bytes,3,opt,name=faceURL" json:"faceURL,omitempty"`
	Ex               string `protobuf:"bytes,4,opt,name=ex" json:"ex,omitempty"`
	CreateTime       int64  `protobuf:"varint,5,opt,name=createTime" json:"createTime,omitempty"`
	AppMangerLevel   int32  `protobuf:"varint,6,opt,name=appMangerLevel" json:"appMangerLevel,omitempty"`
	GlobalRecvMsgOpt int32  `protobuf:"varint,7,opt,name=globalRecvMsgOpt" json:"globalRecvMsgOpt,omitempty"`
}

func (x *UserInfo) Reset() { *x = UserInfo{} }

func (x *UserInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *UserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetAppMangerLevel() int32 {
	if x != nil {
		return x.AppMangerLevel
	}
	return 0
}

func (x *UserInfo) GetGlobalRecvMsgOpt() int32 {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return 0
}

type UserInfoWithEx struct {
	UserID           string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname         string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	FaceURL          string `protobuf:"bytes,3,opt,name=faceURL" json:"faceURL,omitempty"`
	Ex               string `protobuf:"bytes,4,opt,name=ex" json:"ex,omitempty"`
	GlobalRecvMsgOpt int32  `protobuf:"varint,7,opt,name=globalRecvMsgOpt" json:"globalRecvMsgOpt,omitempty"`
}

func (x *UserInfoWithEx) Reset() { *x = UserInfoWithEx{} }

func (x *UserInfoWithEx) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfoWithEx) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfoWithEx) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfoWithEx) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoWithEx) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserInfoWithEx) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *UserInfoWithEx) GetGlobalRecvMsgOpt() int32 {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return 0
}

type FriendInfo struct {
	OwnerUserID    string    `protobuf:"bytes,1,opt,name=ownerUserID" json:"ownerUserID,omitempty"`
	Remark         string    `protobuf:"bytes,2,opt,name=remark" json:"remark,omitempty"`
	CreateTime     int64     `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	FriendUser     *UserInfo `protobuf:"bytes,4,opt,name=friendUser" json:"friendUser,omitempty"`
	AddSource      int32     `protobuf:"varint,5,opt,name=addSource" json:"addSource,omitempty"`
	OperatorUserID string    `protobuf:"bytes,6,opt,name=operatorUserID" json:"operatorUserID,omitempty"`
	Ex             string    `protobuf:"bytes,7,opt,name=ex" json:"ex,omitempty"`
	IsPinned       bool      `protobuf:"varint,8,opt,name=isPinned" json:"isPinned,omitempty"`
}

func (x *FriendInfo) Reset() { *x = FriendInfo{} }

func (x *FriendInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendInfo) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FriendInfo) GetFriendUser() *UserInfo {
	if x != nil {
		return x.FriendUser
	}
	return nil
}

func (x *FriendInfo) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *FriendInfo) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *FriendInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *FriendInfo) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type BlackInfo struct {
	OwnerUserID    string          `protobuf:"bytes,1,opt,name=ownerUserID" json:"ownerUserID,omitempty"`
	CreateTime     int64           `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	BlackUserInfo  *PublicUserInfo `protobuf:"bytes,3,opt,name=blackUserInfo" json:"blackUserInfo,omitempty"`
	AddSource      int32           `protobuf:"varint,4,opt,name=addSource" json:"addSource,omitempty"`
	OperatorUserID string          `protobuf:"bytes,5,opt,name=operatorUserID" json:"operatorUserID,omitempty"`
	Ex             string          `protobuf:"bytes,6,opt,name=ex" json:"ex,omitempty"`
}

func (x *BlackInfo) Reset() { *x = BlackInfo{} }

func (x *BlackInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BlackInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BlackInfo) GetOwnerUserID() string {
	if x != nil {
		return x.OwnerUserID
	}
	return ""
}

func (x *BlackInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *BlackInfo) GetBlackUserInfo() *PublicUserInfo {
	if x != nil {
		return x.BlackUserInfo
	}
	return nil
}

func (x *BlackInfo) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *BlackInfo) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *BlackInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type GroupRequest struct {
	UserInfo      *PublicUserInfo `protobuf:"bytes,1,opt,name=userInfo" json:"userInfo,omitempty"`
	GroupInfo     *GroupInfo      `protobuf:"bytes,2,opt,name=groupInfo" json:"groupInfo,omitempty"`
	HandleResult  int32           `protobuf:"varint,3,opt,name=handleResult" json:"handleResult,omitempty"`
	ReqMsg        string          `protobuf:"bytes,4,opt,name=reqMsg" json:"reqMsg,omitempty"`
	HandleMsg     string          `protobuf:"bytes,5,opt,name=handleMsg" json:"handleMsg,omitempty"`
	ReqTime       int64           `protobuf:"varint,6,opt,name=reqTime" json:"reqTime,omitempty"`
	HandleUserID  string          `protobuf:"bytes,7,opt,name=handleUserID" json:"handleUserID,omitempty"`
	HandleTime    int64           `protobuf:"varint,8,opt,name=handleTime" json:"handleTime,omitempty"`
	Ex            string          `protobuf:"bytes,9,opt,name=ex" json:"ex,omitempty"`
	JoinSource    int32           `protobuf:"varint,10,opt,name=joinSource" json:"joinSource,omitempty"`
	InviterUserID string          `protobuf:"bytes,11,opt,name=inviterUserID" json:"inviterUserID,omitempty"`
}

func (x *GroupRequest) Reset() { *x = GroupRequest{} }

func (x *GroupRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupRequest) GetUserInfo() *PublicUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *GroupRequest) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GroupRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

func (x *GroupRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupRequest) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *GroupRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupRequest) GetHandleUserID() string {
	if x != nil {
		return x.HandleUserID
	}
	return ""
}

func (x *GroupRequest) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *GroupRequest) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *GroupRequest) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupRequest) GetInviterUserID() string {
	if x != nil {
		return x.InviterUserID
	}
	return ""
}

type FriendRequest struct {
	FromUserID    string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	FromNickname  string `protobuf:"bytes,2,opt,name=fromNickname" json:"fromNickname,omitempty"`
	FromFaceURL   string `protobuf:"bytes,3,opt,name=fromFaceURL" json:"fromFaceURL,omitempty"`
	ToUserID      string `protobuf:"bytes,4,opt,name=toUserID" json:"toUserID,omitempty"`
	ToNickname    string `protobuf:"bytes,5,opt,name=toNickname" json:"toNickname,omitempty"`
	ToFaceURL     string `protobuf:"bytes,6,opt,name=toFaceURL" json:"toFaceURL,omitempty"`
	HandleResult  int32  `protobuf:"varint,7,opt,name=handleResult" json:"handleResult,omitempty"`
	ReqMsg        string `protobuf:"bytes,8,opt,name=reqMsg" json:"reqMsg,omitempty"`
	CreateTime    int64  `protobuf:"varint,9,opt,name=createTime" json:"createTime,omitempty"`
	HandlerUserID string `protobuf:"bytes,10,opt,name=handlerUserID" json:"handlerUserID,omitempty"`
	HandleMsg     string `protobuf:"bytes,11,opt,name=handleMsg" json:"handleMsg,omitempty"`
	HandleTime    int64  `protobuf:"varint,12,opt,name=handleTime" json:"handleTime,omitempty"`
	Ex            string `protobuf:"bytes,13,opt,name=ex" json:"ex,omitempty"`
}

func (x *FriendRequest) Reset() { *x = FriendRequest{} }

func (x *FriendRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendRequest) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *FriendRequest) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *FriendRequest) GetFromFaceURL() string {
	if x != nil {
		return x.FromFaceURL
	}
	return ""
}

func (x *FriendRequest) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

func (x *FriendRequest) GetToNickname() string {
	if x != nil {
		return x.ToNickname
	}
	return ""
}

func (x *FriendRequest) GetToFaceURL() string {
	if x != nil {
		return x.ToFaceURL
	}
	return ""
}

func (x *FriendRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

func (x *FriendRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendRequest) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FriendRequest) GetHandlerUserID() string {
	if x != nil {
		return x.HandlerUserID
	}
	return ""
}

func (x *FriendRequest) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *FriendRequest) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *FriendRequest) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type PullMessageBySeqsReq struct {
	UserID    string      `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	SeqRanges []*SeqRange `protobuf:"bytes,2,rep,name=seqRanges" json:"seqRanges,omitempty"`
	Order     PullOrder   `protobuf:"varint,3,opt,name=order" json:"order,omitempty"`
}

func (x *PullMessageBySeqsReq) Reset() { *x = PullMessageBySeqsReq{} }

func (x *PullMessageBySeqsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PullMessageBySeqsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PullMessageBySeqsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PullMessageBySeqsReq) GetSeqRanges() []*SeqRange {
	if x != nil {
		return x.SeqRanges
	}
	return nil
}

func (x *PullMessageBySeqsReq) GetOrder() PullOrder {
	if x != nil {
		return x.Order
	}
	return PullOrder_PullOrderAsc
}

type SeqRange struct {
	ConversationID string `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	Begin          int64  `protobuf:"varint,2,opt,name=begin" json:"begin,omitempty"`
	End            int64  `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	Num            int64  `protobuf:"varint,4,opt,name=num" json:"num,omitempty"`
}

func (x *SeqRange) Reset() { *x = SeqRange{} }

func (x *SeqRange) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SeqRange) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SeqRange) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *SeqRange) GetBegin() int64 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *SeqRange) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SeqRange) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PullMsgs struct {
	Msgs   []*MsgData `protobuf:"bytes,1,rep,name=Msgs" json:"Msgs,omitempty"`
	IsEnd  bool       `protobuf:"varint,2,opt,name=isEnd" json:"isEnd,omitempty"`
	EndSeq int64      `protobuf:"varint,3,opt,name=endSeq" json:"endSeq,omitempty"`
}

func (x *PullMsgs) Reset() { *x = PullMsgs{} }

func (x *PullMsgs) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PullMsgs) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PullMsgs) GetMsgs() []*MsgData {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *PullMsgs) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *PullMsgs) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

type PullMessageBySeqsResp struct {
	Msgs             map[string]*PullMsgs `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NotificationMsgs map[string]*PullMsgs `protobuf:"bytes,2,rep,name=notificationMsgs" json:"notificationMsgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *PullMessageBySeqsResp) Reset() { *x = PullMessageBySeqsResp{} }

func (x *PullMessageBySeqsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *PullMessageBySeqsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PullMessageBySeqsResp) GetMsgs() map[string]*PullMsgs {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *PullMessageBySeqsResp) GetNotificationMsgs() map[string]*PullMsgs {
	if x != nil {
		return x.NotificationMsgs
	}
	return nil
}

type GetMaxSeqReq struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
}

func (x *GetMaxSeqReq) Reset() { *x = GetMaxSeqReq{} }

func (x *GetMaxSeqReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMaxSeqReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMaxSeqReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetMaxSeqResp struct {
	MaxSeqs map[string]int64 `protobuf:"bytes,1,rep,name=maxSeqs" json:"maxSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MinSeqs map[string]int64 `protobuf:"bytes,2,rep,name=minSeqs" json:"minSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (x *GetMaxSeqResp) Reset() { *x = GetMaxSeqResp{} }

func (x *GetMaxSeqResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMaxSeqResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMaxSeqResp) GetMaxSeqs() map[string]int64 {
	if x != nil {
		return x.MaxSeqs
	}
	return nil
}

func (x *GetMaxSeqResp) GetMinSeqs() map[string]int64 {
	if x != nil {
		return x.MinSeqs
	}
	return nil
}

type UserSendMsgResp struct {
	ServerMsgID string `protobuf:"bytes,1,opt,name=serverMsgID" json:"serverMsgID,omitempty"`
	ClientMsgID string `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	SendTime    int64  `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
}

func (x *UserSendMsgResp) Reset() { *x = UserSendMsgResp{} }

func (x *UserSendMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserSendMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserSendMsgResp) GetServerMsgID() string {
	if x != nil {
		return x.ServerMsgID
	}
	return ""
}

func (x *UserSendMsgResp) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *UserSendMsgResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type MsgData struct {
	SendID           string           `protobuf:"bytes,1,opt,name=sendID" json:"sendID,omitempty"`
	RecvID           string           `protobuf:"bytes,2,opt,name=recvID" json:"recvID,omitempty"`
	GroupID          string           `protobuf:"bytes,3,opt,name=groupID" json:"groupID,omitempty"`
	ClientMsgID      string           `protobuf:"bytes,4,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	ServerMsgID      string           `protobuf:"bytes,5,opt,name=serverMsgID" json:"serverMsgID,omitempty"`
	SenderPlatformID int32            `protobuf:"varint,6,opt,name=senderPlatformID" json:"senderPlatformID,omitempty"`
	SenderNickname   string           `protobuf:"bytes,7,opt,name=senderNickname" json:"senderNickname,omitempty"`
	SenderFaceURL    string           `protobuf:"bytes,8,opt,name=senderFaceURL" json:"senderFaceURL,omitempty"`
	SessionType      int32            `protobuf:"varint,9,opt,name=sessionType" json:"sessionType,omitempty"`
	MsgFrom          int32            `protobuf:"varint,10,opt,name=msgFrom" json:"msgFrom,omitempty"`
	ContentType      int32            `protobuf:"varint,11,opt,name=contentType" json:"contentType,omitempty"`
	Content          []byte           `protobuf:"bytes,12,opt,name=content" json:"content,omitempty"`
	Seq              int64            `protobuf:"varint,14,opt,name=seq" json:"seq,omitempty"`
	SendTime         int64            `protobuf:"varint,15,opt,name=sendTime" json:"sendTime,omitempty"`
	CreateTime       int64            `protobuf:"varint,16,opt,name=createTime" json:"createTime,omitempty"`
	Status           int32            `protobuf:"varint,17,opt,name=status" json:"status,omitempty"`
	IsRead           bool             `protobuf:"varint,18,opt,name=isRead" json:"isRead,omitempty"`
	Options          map[string]bool  `protobuf:"bytes,19,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OfflinePushInfo  *OfflinePushInfo `protobuf:"bytes,20,opt,name=offlinePushInfo" json:"offlinePushInfo,omitempty"`
	AtUserIDList     []string         `protobuf:"bytes,21,rep,name=atUserIDList" json:"atUserIDList,omitempty"`
	AttachedInfo     string           `protobuf:"bytes,22,opt,name=attachedInfo" json:"attachedInfo,omitempty"`
	Ex               string           `protobuf:"bytes,23,opt,name=ex" json:"ex,omitempty"`
}

func (x *MsgData) Reset() { *x = MsgData{} }

func (x *MsgData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MsgData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MsgData) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MsgData) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MsgData) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MsgData) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *MsgData) GetServerMsgID() string {
	if x != nil {
		return x.ServerMsgID
	}
	return ""
}

func (x *MsgData) GetSenderPlatformID() int32 {
	if x != nil {
		return x.SenderPlatformID
	}
	return 0
}

func (x *MsgData) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *MsgData) GetSenderFaceURL() string {
	if x != nil {
		return x.SenderFaceURL
	}
	return ""
}

func (x *MsgData) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *MsgData) GetMsgFrom() int32 {
	if x != nil {
		return x.MsgFrom
	}
	return 0
}

func (x *MsgData) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MsgData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MsgData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgData) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MsgData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MsgData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MsgData) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MsgData) GetOptions() map[string]bool {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MsgData) GetOfflinePushInfo() *OfflinePushInfo {
	if x != nil {
		return x.OfflinePushInfo
	}
	return nil
}

func (x *MsgData) GetAtUserIDList() []string {
	if x != nil {
		return x.AtUserIDList
	}
	return nil
}

func (x *MsgData) GetAttachedInfo() string {
	if x != nil {
		return x.AttachedInfo
	}
	return ""
}

func (x *MsgData) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type PushMessages struct {
	Msgs             map[string]*PullMsgs `protobuf:"bytes,1,rep,name=msgs" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NotificationMsgs map[string]*PullMsgs `protobuf:"bytes,2,rep,name=notificationMsgs" json:"notificationMsgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *PushMessages) Reset() { *x = PushMessages{} }

func (x *PushMessages) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushMessages) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushMessages) GetMsgs() map[string]*PullMsgs {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *PushMessages) GetNotificationMsgs() map[string]*PullMsgs {
	if x != nil {
		return x.NotificationMsgs
	}
	return nil
}

type OfflinePushInfo struct {
	Title         string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Desc          string `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Ex            string `protobuf:"bytes,3,opt,name=ex" json:"ex,omitempty"`
	IOSPushSound  string `protobuf:"bytes,4,opt,name=iOSPushSound" json:"iOSPushSound,omitempty"`
	IOSBadgeCount bool   `protobuf:"varint,5,opt,name=iOSBadgeCount" json:"iOSBadgeCount,omitempty"`
	SignalInfo    string `protobuf:"bytes,6,opt,name=signalInfo" json:"signalInfo,omitempty"`
}

func (x *OfflinePushInfo) Reset() { *x = OfflinePushInfo{} }

func (x *OfflinePushInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OfflinePushInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OfflinePushInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OfflinePushInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OfflinePushInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *OfflinePushInfo) GetIOSPushSound() string {
	if x != nil {
		return x.IOSPushSound
	}
	return ""
}

func (x *OfflinePushInfo) GetIOSBadgeCount() bool {
	if x != nil {
		return x.IOSBadgeCount
	}
	return false
}

func (x *OfflinePushInfo) GetSignalInfo() string {
	if x != nil {
		return x.SignalInfo
	}
	return ""
}

type TipsComm struct {
	Detail      []byte `protobuf:"bytes,1,opt,name=detail" json:"detail,omitempty"`
	DefaultTips string `protobuf:"bytes,2,opt,name=defaultTips" json:"defaultTips,omitempty"`
	JsonDetail  string `protobuf:"bytes,3,opt,name=jsonDetail" json:"jsonDetail,omitempty"`
}

func (x *TipsComm) Reset() { *x = TipsComm{} }

func (x *TipsComm) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TipsComm) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TipsComm) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *TipsComm) GetDefaultTips() string {
	if x != nil {
		return x.DefaultTips
	}
	return ""
}

func (x *TipsComm) GetJsonDetail() string {
	if x != nil {
		return x.JsonDetail
	}
	return ""
}

// OnGroupCreated()
type GroupCreatedTips struct {
	Group                *GroupInfo             `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo   `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	MemberList           []*GroupMemberFullInfo `protobuf:"bytes,3,rep,name=memberList" json:"memberList,omitempty"`
	OperationTime        int64                  `protobuf:"varint,4,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupOwnerUser       *GroupMemberFullInfo   `protobuf:"bytes,5,opt,name=groupOwnerUser" json:"groupOwnerUser,omitempty"`
	GroupMemberVersion   uint64                 `protobuf:"varint,6,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string                 `protobuf:"bytes,7,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupCreatedTips) Reset() { *x = GroupCreatedTips{} }

func (x *GroupCreatedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupCreatedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupCreatedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupCreatedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupCreatedTips) GetMemberList() []*GroupMemberFullInfo {
	if x != nil {
		return x.MemberList
	}
	return nil
}

func (x *GroupCreatedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupCreatedTips) GetGroupOwnerUser() *GroupMemberFullInfo {
	if x != nil {
		return x.GroupOwnerUser
	}
	return nil
}

func (x *GroupCreatedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupCreatedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

// OnGroupInfoSet()
type GroupInfoSetTips struct {
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,1,opt,name=opUser" json:"opUser,omitempty"` //who do this
	MuteTime             int64                `protobuf:"varint,2,opt,name=muteTime" json:"muteTime,omitempty"`
	Group                *GroupInfo           `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,4,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,5,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupInfoSetTips) Reset() { *x = GroupInfoSetTips{} }

func (x *GroupInfoSetTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupInfoSetTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupInfoSetTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupInfoSetTips) GetMuteTime() int64 {
	if x != nil {
		return x.MuteTime
	}
	return 0
}

func (x *GroupInfoSetTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupInfoSetTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupInfoSetTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupInfoSetNameTips struct {
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,1,opt,name=opUser" json:"opUser,omitempty"` //who do this
	Group                *GroupInfo           `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,3,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,4,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupInfoSetNameTips) Reset() { *x = GroupInfoSetNameTips{} }

func (x *GroupInfoSetNameTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupInfoSetNameTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupInfoSetNameTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupInfoSetNameTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupInfoSetNameTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupInfoSetNameTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupInfoSetAnnouncementTips struct {
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,1,opt,name=opUser" json:"opUser,omitempty"` //who do this
	Group                *GroupInfo           `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,3,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,4,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupInfoSetAnnouncementTips) Reset() { *x = GroupInfoSetAnnouncementTips{} }

func (x *GroupInfoSetAnnouncementTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupInfoSetAnnouncementTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupInfoSetAnnouncementTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupInfoSetAnnouncementTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupInfoSetAnnouncementTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupInfoSetAnnouncementTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

// OnJoinGroupApplication()
type JoinGroupApplicationTips struct {
	Group     *GroupInfo      `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Applicant *PublicUserInfo `protobuf:"bytes,2,opt,name=applicant" json:"applicant,omitempty"`
	ReqMsg    string          `protobuf:"bytes,3,opt,name=reqMsg" json:"reqMsg,omitempty"`
}

func (x *JoinGroupApplicationTips) Reset() { *x = JoinGroupApplicationTips{} }

func (x *JoinGroupApplicationTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *JoinGroupApplicationTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *JoinGroupApplicationTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *JoinGroupApplicationTips) GetApplicant() *PublicUserInfo {
	if x != nil {
		return x.Applicant
	}
	return nil
}

func (x *JoinGroupApplicationTips) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

//	OnQuitGroup()
//
// Actively leave the group
type MemberQuitTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	QuitUser             *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=quitUser" json:"quitUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,4,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,5,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *MemberQuitTips) Reset() { *x = MemberQuitTips{} }

func (x *MemberQuitTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MemberQuitTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MemberQuitTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *MemberQuitTips) GetQuitUser() *GroupMemberFullInfo {
	if x != nil {
		return x.QuitUser
	}
	return nil
}

func (x *MemberQuitTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *MemberQuitTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *MemberQuitTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

// OnApplicationGroupAccepted()
type GroupApplicationAcceptedTips struct {
	Group      *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser     *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	HandleMsg  string               `protobuf:"bytes,4,opt,name=handleMsg" json:"handleMsg,omitempty"`
	ReceiverAs int32                `protobuf:"varint,5,opt,name=receiverAs" json:"receiverAs,omitempty"` // admin(==1) or applicant(==0)
}

func (x *GroupApplicationAcceptedTips) Reset() { *x = GroupApplicationAcceptedTips{} }

func (x *GroupApplicationAcceptedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupApplicationAcceptedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupApplicationAcceptedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupApplicationAcceptedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupApplicationAcceptedTips) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *GroupApplicationAcceptedTips) GetReceiverAs() int32 {
	if x != nil {
		return x.ReceiverAs
	}
	return 0
}

// OnApplicationGroupRejected()
type GroupApplicationRejectedTips struct {
	Group      *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser     *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	HandleMsg  string               `protobuf:"bytes,4,opt,name=handleMsg" json:"handleMsg,omitempty"`
	ReceiverAs int32                `protobuf:"varint,5,opt,name=receiverAs" json:"receiverAs,omitempty"` // admin(==1) or applicant(==0)
}

func (x *GroupApplicationRejectedTips) Reset() { *x = GroupApplicationRejectedTips{} }

func (x *GroupApplicationRejectedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupApplicationRejectedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupApplicationRejectedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupApplicationRejectedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupApplicationRejectedTips) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *GroupApplicationRejectedTips) GetReceiverAs() int32 {
	if x != nil {
		return x.ReceiverAs
	}
	return 0
}

// OnTransferGroupOwner()
type GroupOwnerTransferredTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	NewGroupOwner        *GroupMemberFullInfo `protobuf:"bytes,3,opt,name=newGroupOwner" json:"newGroupOwner,omitempty"`
	OldGroupOwner        string               `protobuf:"bytes,4,opt,name=oldGroupOwner" json:"oldGroupOwner,omitempty"`
	OperationTime        int64                `protobuf:"varint,5,opt,name=operationTime" json:"operationTime,omitempty"`
	OldGroupOwnerInfo    *GroupMemberFullInfo `protobuf:"bytes,6,opt,name=oldGroupOwnerInfo" json:"oldGroupOwnerInfo,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,7,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,8,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupOwnerTransferredTips) Reset() { *x = GroupOwnerTransferredTips{} }

func (x *GroupOwnerTransferredTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupOwnerTransferredTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupOwnerTransferredTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupOwnerTransferredTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupOwnerTransferredTips) GetNewGroupOwner() *GroupMemberFullInfo {
	if x != nil {
		return x.NewGroupOwner
	}
	return nil
}

func (x *GroupOwnerTransferredTips) GetOldGroupOwner() string {
	if x != nil {
		return x.OldGroupOwner
	}
	return ""
}

func (x *GroupOwnerTransferredTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupOwnerTransferredTips) GetOldGroupOwnerInfo() *GroupMemberFullInfo {
	if x != nil {
		return x.OldGroupOwnerInfo
	}
	return nil
}

func (x *GroupOwnerTransferredTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupOwnerTransferredTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

// OnMemberKicked()
type MemberKickedTips struct {
	Group                *GroupInfo             `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo   `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	KickedUserList       []*GroupMemberFullInfo `protobuf:"bytes,3,rep,name=kickedUserList" json:"kickedUserList,omitempty"`
	OperationTime        int64                  `protobuf:"varint,4,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64                 `protobuf:"varint,5,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string                 `protobuf:"bytes,6,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *MemberKickedTips) Reset() { *x = MemberKickedTips{} }

func (x *MemberKickedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MemberKickedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MemberKickedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *MemberKickedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *MemberKickedTips) GetKickedUserList() []*GroupMemberFullInfo {
	if x != nil {
		return x.KickedUserList
	}
	return nil
}

func (x *MemberKickedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *MemberKickedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *MemberKickedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

// OnMemberInvited()
type MemberInvitedTips struct {
	Group                *GroupInfo             `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo   `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	InvitedUserList      []*GroupMemberFullInfo `protobuf:"bytes,3,rep,name=invitedUserList" json:"invitedUserList,omitempty"`
	OperationTime        int64                  `protobuf:"varint,4,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64                 `protobuf:"varint,5,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string                 `protobuf:"bytes,6,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
	InviterUser          *GroupMemberFullInfo   `protobuf:"bytes,7,opt,name=inviterUser" json:"inviterUser,omitempty"`
}

func (x *MemberInvitedTips) Reset() { *x = MemberInvitedTips{} }

func (x *MemberInvitedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MemberInvitedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MemberInvitedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *MemberInvitedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *MemberInvitedTips) GetInvitedUserList() []*GroupMemberFullInfo {
	if x != nil {
		return x.InvitedUserList
	}
	return nil
}

func (x *MemberInvitedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *MemberInvitedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *MemberInvitedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

func (x *MemberInvitedTips) GetInviterUser() *GroupMemberFullInfo {
	if x != nil {
		return x.InviterUser
	}
	return nil
}

// Actively join the group
type MemberEnterTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	EntrantUser          *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=entrantUser" json:"entrantUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,5,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,6,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *MemberEnterTips) Reset() { *x = MemberEnterTips{} }

func (x *MemberEnterTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MemberEnterTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MemberEnterTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *MemberEnterTips) GetEntrantUser() *GroupMemberFullInfo {
	if x != nil {
		return x.EntrantUser
	}
	return nil
}

func (x *MemberEnterTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *MemberEnterTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *MemberEnterTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupDismissedTips struct {
	Group         *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser        *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
}

func (x *GroupDismissedTips) Reset() { *x = GroupDismissedTips{} }

func (x *GroupDismissedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupDismissedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupDismissedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupDismissedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupDismissedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type GroupMemberMutedTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	MutedUser            *GroupMemberFullInfo `protobuf:"bytes,4,opt,name=mutedUser" json:"mutedUser,omitempty"`
	MutedSeconds         uint32               `protobuf:"varint,5,opt,name=mutedSeconds" json:"mutedSeconds,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,6,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,7,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupMemberMutedTips) Reset() { *x = GroupMemberMutedTips{} }

func (x *GroupMemberMutedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupMemberMutedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupMemberMutedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupMemberMutedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupMemberMutedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupMemberMutedTips) GetMutedUser() *GroupMemberFullInfo {
	if x != nil {
		return x.MutedUser
	}
	return nil
}

func (x *GroupMemberMutedTips) GetMutedSeconds() uint32 {
	if x != nil {
		return x.MutedSeconds
	}
	return 0
}

func (x *GroupMemberMutedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupMemberMutedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupMemberCancelMutedTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	MutedUser            *GroupMemberFullInfo `protobuf:"bytes,4,opt,name=mutedUser" json:"mutedUser,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,5,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,6,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupMemberCancelMutedTips) Reset() { *x = GroupMemberCancelMutedTips{} }

func (x *GroupMemberCancelMutedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupMemberCancelMutedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupMemberCancelMutedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupMemberCancelMutedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupMemberCancelMutedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupMemberCancelMutedTips) GetMutedUser() *GroupMemberFullInfo {
	if x != nil {
		return x.MutedUser
	}
	return nil
}

func (x *GroupMemberCancelMutedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupMemberCancelMutedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupMutedTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,4,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,5,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupMutedTips) Reset() { *x = GroupMutedTips{} }

func (x *GroupMutedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupMutedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupMutedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupMutedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupMutedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupMutedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupMutedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupCancelMutedTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,4,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,5,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
}

func (x *GroupCancelMutedTips) Reset() { *x = GroupCancelMutedTips{} }

func (x *GroupCancelMutedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupCancelMutedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupCancelMutedTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupCancelMutedTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupCancelMutedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupCancelMutedTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupCancelMutedTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

type GroupMemberInfoSetTips struct {
	Group                *GroupInfo           `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	OpUser               *GroupMemberFullInfo `protobuf:"bytes,2,opt,name=opUser" json:"opUser,omitempty"`
	OperationTime        int64                `protobuf:"varint,3,opt,name=operationTime" json:"operationTime,omitempty"`
	ChangedUser          *GroupMemberFullInfo `protobuf:"bytes,4,opt,name=changedUser" json:"changedUser,omitempty"`
	GroupMemberVersion   uint64               `protobuf:"varint,5,opt,name=groupMemberVersion" json:"groupMemberVersion,omitempty"`
	GroupMemberVersionID string               `protobuf:"bytes,6,opt,name=groupMemberVersionID" json:"groupMemberVersionID,omitempty"`
	GroupSortVersion     uint64               `protobuf:"varint,7,opt,name=groupSortVersion" json:"groupSortVersion,omitempty"`
}

func (x *GroupMemberInfoSetTips) Reset() { *x = GroupMemberInfoSetTips{} }

func (x *GroupMemberInfoSetTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GroupMemberInfoSetTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupMemberInfoSetTips) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupMemberInfoSetTips) GetOpUser() *GroupMemberFullInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *GroupMemberInfoSetTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GroupMemberInfoSetTips) GetChangedUser() *GroupMemberFullInfo {
	if x != nil {
		return x.ChangedUser
	}
	return nil
}

func (x *GroupMemberInfoSetTips) GetGroupMemberVersion() uint64 {
	if x != nil {
		return x.GroupMemberVersion
	}
	return 0
}

func (x *GroupMemberInfoSetTips) GetGroupMemberVersionID() string {
	if x != nil {
		return x.GroupMemberVersionID
	}
	return ""
}

func (x *GroupMemberInfoSetTips) GetGroupSortVersion() uint64 {
	if x != nil {
		return x.GroupSortVersion
	}
	return 0
}

type FriendApplication struct {
	AddTime    int64  `protobuf:"varint,1,opt,name=addTime" json:"addTime,omitempty"`
	AddSource  string `protobuf:"bytes,2,opt,name=addSource" json:"addSource,omitempty"`
	AddWording string `protobuf:"bytes,3,opt,name=addWording" json:"addWording,omitempty"`
}

func (x *FriendApplication) Reset() { *x = FriendApplication{} }

func (x *FriendApplication) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendApplication) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendApplication) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *FriendApplication) GetAddSource() string {
	if x != nil {
		return x.AddSource
	}
	return ""
}

func (x *FriendApplication) GetAddWording() string {
	if x != nil {
		return x.AddWording
	}
	return ""
}

type FromToUserID struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
}

func (x *FromToUserID) Reset() { *x = FromToUserID{} }

func (x *FromToUserID) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FromToUserID) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FromToUserID) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *FromToUserID) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

// FromUserID apply to add ToUserID
type FriendApplicationTips struct {
	FromToUserID *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：发起者； to：接收者
}

func (x *FriendApplicationTips) Reset() { *x = FriendApplicationTips{} }

func (x *FriendApplicationTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FriendApplicationTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendApplicationTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

// FromUserID accept or reject ToUserID
type FriendApplicationApprovedTips struct {
	FromToUserID    *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：同意者；to：请求发起者
	HandleMsg       string        `protobuf:"bytes,2,opt,name=handleMsg" json:"handleMsg,omitempty"`
	FriendVersion   uint64        `protobuf:"varint,3,opt,name=friendVersion" json:"friendVersion,omitempty"`
	FriendVersionID string        `protobuf:"bytes,4,opt,name=friendVersionID" json:"friendVersionID,omitempty"`
}

func (x *FriendApplicationApprovedTips) Reset() { *x = FriendApplicationApprovedTips{} }

func (x *FriendApplicationApprovedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FriendApplicationApprovedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendApplicationApprovedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

func (x *FriendApplicationApprovedTips) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *FriendApplicationApprovedTips) GetFriendVersion() uint64 {
	if x != nil {
		return x.FriendVersion
	}
	return 0
}

func (x *FriendApplicationApprovedTips) GetFriendVersionID() string {
	if x != nil {
		return x.FriendVersionID
	}
	return ""
}

// FromUserID accept or reject ToUserID
type FriendApplicationRejectedTips struct {
	FromToUserID *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：拒绝者；to：请求发起者
	HandleMsg    string        `protobuf:"bytes,2,opt,name=handleMsg" json:"handleMsg,omitempty"`
}

func (x *FriendApplicationRejectedTips) Reset() { *x = FriendApplicationRejectedTips{} }

func (x *FriendApplicationRejectedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FriendApplicationRejectedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendApplicationRejectedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

func (x *FriendApplicationRejectedTips) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

// FromUserID  Added a friend ToUserID
type FriendAddedTips struct {
	Friend          *FriendInfo     `protobuf:"bytes,1,opt,name=friend" json:"friend,omitempty"`
	OperationTime   int64           `protobuf:"varint,2,opt,name=operationTime" json:"operationTime,omitempty"`
	OpUser          *PublicUserInfo `protobuf:"bytes,3,opt,name=opUser" json:"opUser,omitempty"` //who do this
	FriendVersion   uint64          `protobuf:"varint,4,opt,name=friendVersion" json:"friendVersion,omitempty"`
	FriendVersionID string          `protobuf:"bytes,5,opt,name=friendVersionID" json:"friendVersionID,omitempty"`
}

func (x *FriendAddedTips) Reset() { *x = FriendAddedTips{} }

func (x *FriendAddedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendAddedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendAddedTips) GetFriend() *FriendInfo {
	if x != nil {
		return x.Friend
	}
	return nil
}

func (x *FriendAddedTips) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *FriendAddedTips) GetOpUser() *PublicUserInfo {
	if x != nil {
		return x.OpUser
	}
	return nil
}

func (x *FriendAddedTips) GetFriendVersion() uint64 {
	if x != nil {
		return x.FriendVersion
	}
	return 0
}

func (x *FriendAddedTips) GetFriendVersionID() string {
	if x != nil {
		return x.FriendVersionID
	}
	return ""
}

// FromUserID  deleted a friend ToUserID
type FriendDeletedTips struct {
	FromToUserID    *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：owner； to：friend
	FriendVersion   uint64        `protobuf:"varint,2,opt,name=friendVersion" json:"friendVersion,omitempty"`
	FriendVersionID string        `protobuf:"bytes,3,opt,name=friendVersionID" json:"friendVersionID,omitempty"`
}

func (x *FriendDeletedTips) Reset() { *x = FriendDeletedTips{} }

func (x *FriendDeletedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendDeletedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendDeletedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

func (x *FriendDeletedTips) GetFriendVersion() uint64 {
	if x != nil {
		return x.FriendVersion
	}
	return 0
}

func (x *FriendDeletedTips) GetFriendVersionID() string {
	if x != nil {
		return x.FriendVersionID
	}
	return ""
}

type BlackAddedTips struct {
	FromToUserID *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：owner； to：black
}

func (x *BlackAddedTips) Reset() { *x = BlackAddedTips{} }

func (x *BlackAddedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BlackAddedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BlackAddedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

type BlackDeletedTips struct {
	FromToUserID *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：owner； to：black
}

func (x *BlackDeletedTips) Reset() { *x = BlackDeletedTips{} }

func (x *BlackDeletedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BlackDeletedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BlackDeletedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

type FriendInfoChangedTips struct {
	FromToUserID      *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"` //from：changed； to：friend
	FriendVersion     uint64        `protobuf:"varint,2,opt,name=friendVersion" json:"friendVersion,omitempty"`
	FriendVersionID   string        `protobuf:"bytes,3,opt,name=friendVersionID" json:"friendVersionID,omitempty"`
	FriendSortVersion uint64        `protobuf:"varint,4,opt,name=friendSortVersion" json:"friendSortVersion,omitempty"`
}

func (x *FriendInfoChangedTips) Reset() { *x = FriendInfoChangedTips{} }

func (x *FriendInfoChangedTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FriendInfoChangedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendInfoChangedTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

func (x *FriendInfoChangedTips) GetFriendVersion() uint64 {
	if x != nil {
		return x.FriendVersion
	}
	return 0
}

func (x *FriendInfoChangedTips) GetFriendVersionID() string {
	if x != nil {
		return x.FriendVersionID
	}
	return ""
}

func (x *FriendInfoChangedTips) GetFriendSortVersion() uint64 {
	if x != nil {
		return x.FriendSortVersion
	}
	return 0
}

// ////////////////////user/////////////////////
type UserInfoUpdatedTips struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
}

func (x *UserInfoUpdatedTips) Reset() { *x = UserInfoUpdatedTips{} }

func (x *UserInfoUpdatedTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfoUpdatedTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfoUpdatedTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserStatusChangeTips struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	PlatformID int32  `protobuf:"varint,4,opt,name=platformID" json:"platformID,omitempty"`
}

func (x *UserStatusChangeTips) Reset() { *x = UserStatusChangeTips{} }

func (x *UserStatusChangeTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserStatusChangeTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserStatusChangeTips) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *UserStatusChangeTips) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

func (x *UserStatusChangeTips) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserStatusChangeTips) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

type UserCommandAddTips struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
}

func (x *UserCommandAddTips) Reset() { *x = UserCommandAddTips{} }

func (x *UserCommandAddTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserCommandAddTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserCommandAddTips) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *UserCommandAddTips) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

type UserCommandUpdateTips struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
}

func (x *UserCommandUpdateTips) Reset() { *x = UserCommandUpdateTips{} }

func (x *UserCommandUpdateTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserCommandUpdateTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserCommandUpdateTips) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *UserCommandUpdateTips) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

type UserCommandDeleteTips struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
}

func (x *UserCommandDeleteTips) Reset() { *x = UserCommandDeleteTips{} }

func (x *UserCommandDeleteTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UserCommandDeleteTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserCommandDeleteTips) GetFromUserID() string {
	if x != nil {
		return x.FromUserID
	}
	return ""
}

func (x *UserCommandDeleteTips) GetToUserID() string {
	if x != nil {
		return x.ToUserID
	}
	return ""
}

// ////////////////////conversation/////////////////////
type ConversationUpdateTips struct {
	UserID             string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationIDList []string `protobuf:"bytes,2,rep,name=conversationIDList" json:"conversationIDList,omitempty"`
}

func (x *ConversationUpdateTips) Reset() { *x = ConversationUpdateTips{} }

func (x *ConversationUpdateTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ConversationUpdateTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationUpdateTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ConversationUpdateTips) GetConversationIDList() []string {
	if x != nil {
		return x.ConversationIDList
	}
	return nil
}

type ConversationSetPrivateTips struct {
	RecvID         string `protobuf:"bytes,1,opt,name=recvID" json:"recvID,omitempty"`
	SendID         string `protobuf:"bytes,2,opt,name=sendID" json:"sendID,omitempty"`
	IsPrivate      bool   `protobuf:"varint,3,opt,name=isPrivate" json:"isPrivate,omitempty"`
	ConversationID string `protobuf:"bytes,4,opt,name=conversationID" json:"conversationID,omitempty"`
}

func (x *ConversationSetPrivateTips) Reset() { *x = ConversationSetPrivateTips{} }

func (x *ConversationSetPrivateTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ConversationSetPrivateTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationSetPrivateTips) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *ConversationSetPrivateTips) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *ConversationSetPrivateTips) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *ConversationSetPrivateTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type ConversationHasReadTips struct {
	UserID          string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationID  string `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	HasReadSeq      int64  `protobuf:"varint,3,opt,name=hasReadSeq" json:"hasReadSeq,omitempty"`
	UnreadCountTime int64  `protobuf:"varint,4,opt,name=unreadCountTime" json:"unreadCountTime,omitempty"`
}

func (x *ConversationHasReadTips) Reset() { *x = ConversationHasReadTips{} }

func (x *ConversationHasReadTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ConversationHasReadTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationHasReadTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ConversationHasReadTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ConversationHasReadTips) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *ConversationHasReadTips) GetUnreadCountTime() int64 {
	if x != nil {
		return x.UnreadCountTime
	}
	return 0
}

type NotificationElem struct {
	Detail string `protobuf:"bytes,1,opt,name=detail" json:"detail,omitempty"`
}

func (x *NotificationElem) Reset() { *x = NotificationElem{} }

func (x *NotificationElem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *NotificationElem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *NotificationElem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// //////////////////message///////////////////////
type Seqs struct {
	Seqs []int64 `protobuf:"varint,1,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *Seqs) Reset() { *x = Seqs{} }

func (x *Seqs) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Seqs) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Seqs) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type DeleteMessageTips struct {
	OpUserID string  `protobuf:"bytes,1,opt,name=opUserID" json:"opUserID,omitempty"`
	UserID   string  `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Seqs     []int64 `protobuf:"varint,3,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *DeleteMessageTips) Reset() { *x = DeleteMessageTips{} }

func (x *DeleteMessageTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteMessageTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteMessageTips) GetOpUserID() string {
	if x != nil {
		return x.OpUserID
	}
	return ""
}

func (x *DeleteMessageTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeleteMessageTips) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type RevokeMsgTips struct {
	RevokerUserID  string `protobuf:"bytes,1,opt,name=revokerUserID" json:"revokerUserID,omitempty"`
	ClientMsgID    string `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	RevokeTime     int64  `protobuf:"varint,3,opt,name=revokeTime" json:"revokeTime,omitempty"`
	SesstionType   int32  `protobuf:"varint,5,opt,name=sesstionType" json:"sesstionType,omitempty"`
	Seq            int64  `protobuf:"varint,6,opt,name=seq" json:"seq,omitempty"`
	ConversationID string `protobuf:"bytes,7,opt,name=conversationID" json:"conversationID,omitempty"`
	IsAdminRevoke  bool   `protobuf:"varint,8,opt,name=isAdminRevoke" json:"isAdminRevoke,omitempty"`
}

func (x *RevokeMsgTips) Reset() { *x = RevokeMsgTips{} }

func (x *RevokeMsgTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RevokeMsgTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RevokeMsgTips) GetRevokerUserID() string {
	if x != nil {
		return x.RevokerUserID
	}
	return ""
}

func (x *RevokeMsgTips) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *RevokeMsgTips) GetRevokeTime() int64 {
	if x != nil {
		return x.RevokeTime
	}
	return 0
}

func (x *RevokeMsgTips) GetSesstionType() int32 {
	if x != nil {
		return x.SesstionType
	}
	return 0
}

func (x *RevokeMsgTips) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RevokeMsgTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *RevokeMsgTips) GetIsAdminRevoke() bool {
	if x != nil {
		return x.IsAdminRevoke
	}
	return false
}

type MessageRevokedContent struct {
	RevokerID                   string `protobuf:"bytes,1,opt,name=revokerID" json:"revokerID,omitempty"`
	RevokerRole                 int32  `protobuf:"varint,2,opt,name=revokerRole" json:"revokerRole,omitempty"`
	ClientMsgID                 string `protobuf:"bytes,3,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	RevokerNickname             string `protobuf:"bytes,4,opt,name=revokerNickname" json:"revokerNickname,omitempty"`
	RevokeTime                  int64  `protobuf:"varint,5,opt,name=revokeTime" json:"revokeTime,omitempty"`
	SourceMessageSendTime       int64  `protobuf:"varint,6,opt,name=sourceMessageSendTime" json:"sourceMessageSendTime,omitempty"`
	SourceMessageSendID         string `protobuf:"bytes,7,opt,name=sourceMessageSendID" json:"sourceMessageSendID,omitempty"`
	SourceMessageSenderNickname string `protobuf:"bytes,8,opt,name=sourceMessageSenderNickname" json:"sourceMessageSenderNickname,omitempty"`
	SessionType                 int32  `protobuf:"varint,10,opt,name=sessionType" json:"sessionType,omitempty"`
	Seq                         int64  `protobuf:"varint,11,opt,name=seq" json:"seq,omitempty"`
	Ex                          string `protobuf:"bytes,12,opt,name=ex" json:"ex,omitempty"`
}

func (x *MessageRevokedContent) Reset() { *x = MessageRevokedContent{} }

func (x *MessageRevokedContent) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *MessageRevokedContent) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MessageRevokedContent) GetRevokerID() string {
	if x != nil {
		return x.RevokerID
	}
	return ""
}

func (x *MessageRevokedContent) GetRevokerRole() int32 {
	if x != nil {
		return x.RevokerRole
	}
	return 0
}

func (x *MessageRevokedContent) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *MessageRevokedContent) GetRevokerNickname() string {
	if x != nil {
		return x.RevokerNickname
	}
	return ""
}

func (x *MessageRevokedContent) GetRevokeTime() int64 {
	if x != nil {
		return x.RevokeTime
	}
	return 0
}

func (x *MessageRevokedContent) GetSourceMessageSendTime() int64 {
	if x != nil {
		return x.SourceMessageSendTime
	}
	return 0
}

func (x *MessageRevokedContent) GetSourceMessageSendID() string {
	if x != nil {
		return x.SourceMessageSendID
	}
	return ""
}

func (x *MessageRevokedContent) GetSourceMessageSenderNickname() string {
	if x != nil {
		return x.SourceMessageSenderNickname
	}
	return ""
}

func (x *MessageRevokedContent) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *MessageRevokedContent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageRevokedContent) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type ClearConversationTips struct {
	UserID          string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationIDs []string `protobuf:"bytes,2,rep,name=conversationIDs" json:"conversationIDs,omitempty"`
}

func (x *ClearConversationTips) Reset() { *x = ClearConversationTips{} }

func (x *ClearConversationTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ClearConversationTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearConversationTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ClearConversationTips) GetConversationIDs() []string {
	if x != nil {
		return x.ConversationIDs
	}
	return nil
}

type DeleteMsgsTips struct {
	UserID         string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ConversationID string  `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs           []int64 `protobuf:"varint,3,rep,packed,name=seqs" json:"seqs,omitempty"`
}

func (x *DeleteMsgsTips) Reset() { *x = DeleteMsgsTips{} }

func (x *DeleteMsgsTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteMsgsTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteMsgsTips) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeleteMsgsTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *DeleteMsgsTips) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type MarkAsReadTips struct {
	MarkAsReadUserID string  `protobuf:"bytes,1,opt,name=markAsReadUserID" json:"markAsReadUserID,omitempty"`
	ConversationID   string  `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	Seqs             []int64 `protobuf:"varint,3,rep,packed,name=seqs" json:"seqs,omitempty"`
	HasReadSeq       int64   `protobuf:"varint,4,opt,name=hasReadSeq" json:"hasReadSeq,omitempty"`
}

func (x *MarkAsReadTips) Reset() { *x = MarkAsReadTips{} }

func (x *MarkAsReadTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MarkAsReadTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MarkAsReadTips) GetMarkAsReadUserID() string {
	if x != nil {
		return x.MarkAsReadUserID
	}
	return ""
}

func (x *MarkAsReadTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *MarkAsReadTips) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *MarkAsReadTips) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

type SetAppBackgroundStatusReq struct {
	UserID       string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	IsBackground bool   `protobuf:"varint,2,opt,name=isBackground" json:"isBackground,omitempty"`
}

func (x *SetAppBackgroundStatusReq) Reset() { *x = SetAppBackgroundStatusReq{} }

func (x *SetAppBackgroundStatusReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetAppBackgroundStatusReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SetAppBackgroundStatusReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SetAppBackgroundStatusReq) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

type SetAppBackgroundStatusResp struct {
}

func (x *SetAppBackgroundStatusResp) Reset() { *x = SetAppBackgroundStatusResp{} }

func (x *SetAppBackgroundStatusResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SetAppBackgroundStatusResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type ProcessUserCommand struct {
	UserID     string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Type       int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	CreateTime int64  `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	Uuid       string `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Value      string `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (x *ProcessUserCommand) Reset() { *x = ProcessUserCommand{} }

func (x *ProcessUserCommand) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProcessUserCommand) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProcessUserCommand) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ProcessUserCommand) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProcessUserCommand) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProcessUserCommand) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProcessUserCommand) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestPagination struct {
	PageNumber int32 `protobuf:"varint,1,opt,name=pageNumber" json:"pageNumber,omitempty"`
	ShowNumber int32 `protobuf:"varint,2,opt,name=showNumber" json:"showNumber,omitempty"`
}

func (x *RequestPagination) Reset() { *x = RequestPagination{} }

func (x *RequestPagination) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RequestPagination) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RequestPagination) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *RequestPagination) GetShowNumber() int32 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

type FriendsInfoUpdateTips struct {
	FromToUserID    *FromToUserID `protobuf:"bytes,1,opt,name=fromToUserID" json:"fromToUserID,omitempty"`
	FriendIDs       []string      `protobuf:"bytes,2,rep,name=friendIDs" json:"friendIDs,omitempty"`
	FriendVersion   uint64        `protobuf:"varint,3,opt,name=friendVersion" json:"friendVersion,omitempty"`
	FriendVersionID string        `protobuf:"bytes,4,opt,name=friendVersionID" json:"friendVersionID,omitempty"`
}

func (x *FriendsInfoUpdateTips) Reset() { *x = FriendsInfoUpdateTips{} }

func (x *FriendsInfoUpdateTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FriendsInfoUpdateTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendsInfoUpdateTips) GetFromToUserID() *FromToUserID {
	if x != nil {
		return x.FromToUserID
	}
	return nil
}

func (x *FriendsInfoUpdateTips) GetFriendIDs() []string {
	if x != nil {
		return x.FriendIDs
	}
	return nil
}

func (x *FriendsInfoUpdateTips) GetFriendVersion() uint64 {
	if x != nil {
		return x.FriendVersion
	}
	return 0
}

func (x *FriendsInfoUpdateTips) GetFriendVersionID() string {
	if x != nil {
		return x.FriendVersionID
	}
	return ""
}

type SubUserOnlineStatusElem struct {
	UserID            string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	OnlinePlatformIDs []int32 `protobuf:"varint,2,rep,packed,name=onlinePlatformIDs" json:"onlinePlatformIDs,omitempty"`
}

func (x *SubUserOnlineStatusElem) Reset() { *x = SubUserOnlineStatusElem{} }

func (x *SubUserOnlineStatusElem) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SubUserOnlineStatusElem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SubUserOnlineStatusElem) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SubUserOnlineStatusElem) GetOnlinePlatformIDs() []int32 {
	if x != nil {
		return x.OnlinePlatformIDs
	}
	return nil
}

type SubUserOnlineStatusTips struct {
	Subscribers []*SubUserOnlineStatusElem `protobuf:"bytes,1,rep,name=subscribers" json:"subscribers,omitempty"`
}

func (x *SubUserOnlineStatusTips) Reset() { *x = SubUserOnlineStatusTips{} }

func (x *SubUserOnlineStatusTips) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SubUserOnlineStatusTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SubUserOnlineStatusTips) GetSubscribers() []*SubUserOnlineStatusElem {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type SubUserOnlineStatus struct {
	SubscribeUserID   []string `protobuf:"bytes,1,rep,name=subscribeUserID" json:"subscribeUserID,omitempty"`
	UnsubscribeUserID []string `protobuf:"bytes,2,rep,name=unsubscribeUserID" json:"unsubscribeUserID,omitempty"`
}

func (x *SubUserOnlineStatus) Reset() { *x = SubUserOnlineStatus{} }

func (x *SubUserOnlineStatus) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SubUserOnlineStatus) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SubUserOnlineStatus) GetSubscribeUserID() []string {
	if x != nil {
		return x.SubscribeUserID
	}
	return nil
}

func (x *SubUserOnlineStatus) GetUnsubscribeUserID() []string {
	if x != nil {
		return x.UnsubscribeUserID
	}
	return nil
}

type StreamMsgTips struct {
	ConversationID string   `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	ClientMsgID    string   `protobuf:"bytes,2,opt,name=clientMsgID" json:"clientMsgID,omitempty"`
	StartIndex     int64    `protobuf:"varint,3,opt,name=startIndex" json:"startIndex,omitempty"`
	Packets        []string `protobuf:"bytes,4,rep,name=packets" json:"packets,omitempty"`
	End            bool     `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
}

func (x *StreamMsgTips) Reset() { *x = StreamMsgTips{} }

func (x *StreamMsgTips) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *StreamMsgTips) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *StreamMsgTips) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *StreamMsgTips) GetClientMsgID() string {
	if x != nil {
		return x.ClientMsgID
	}
	return ""
}

func (x *StreamMsgTips) GetStartIndex() int64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *StreamMsgTips) GetPackets() []string {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *StreamMsgTips) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}
