// Code generated by Kitex v0.13.1. DO NOT EDIT.

package push

import (
	"context"
	"github.com/rhp-QE/roc-im-server/internal/kitex_gen/sdkws"

	"github.com/cloudwego/prutal"
)

type PushMsgReq struct {
	MsgData        *sdkws.MsgData `protobuf:"bytes,1,opt,name=msgData" json:"msgData,omitempty"`
	ConversationID string         `protobuf:"bytes,2,opt,name=conversationID" json:"conversationID,omitempty"`
	UserIDs        []string       `protobuf:"bytes,3,rep,name=userIDs" json:"userIDs,omitempty"`
}

func (x *PushMsgReq) Reset() { *x = PushMsgReq{} }

func (x *PushMsgReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushMsgReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PushMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *PushMsgReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *PushMsgReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type PushMsgResp struct {
}

func (x *PushMsgResp) Reset() { *x = PushMsgResp{} }

func (x *PushMsgResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PushMsgResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DelUserPushTokenReq struct {
	UserID     string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	PlatformID int32  `protobuf:"varint,2,opt,name=platformID" json:"platformID,omitempty"`
}

func (x *DelUserPushTokenReq) Reset() { *x = DelUserPushTokenReq{} }

func (x *DelUserPushTokenReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DelUserPushTokenReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DelUserPushTokenReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelUserPushTokenReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

type DelUserPushTokenResp struct {
}

func (x *DelUserPushTokenResp) Reset() { *x = DelUserPushTokenResp{} }

func (x *DelUserPushTokenResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DelUserPushTokenResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type PushService interface {
	PushMsg(ctx context.Context, req *PushMsgReq) (res *PushMsgResp, err error)
	DelUserPushToken(ctx context.Context, req *DelUserPushTokenReq) (res *DelUserPushTokenResp, err error)
}
