// Code generated by Kitex v0.13.1. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	msg "github.com/roc/roc-im-server/internal/kitex_gen/msg"
	sdkws "github.com/roc/roc-im-server/internal/kitex_gen/sdkws"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetMaxSeq(ctx context.Context, Req *sdkws.GetMaxSeqReq, callOptions ...callopt.Option) (r *sdkws.GetMaxSeqResp, err error)
	GetMaxSeqs(ctx context.Context, Req *msg.GetMaxSeqsReq, callOptions ...callopt.Option) (r *msg.SeqsInfoResp, err error)
	GetHasReadSeqs(ctx context.Context, Req *msg.GetHasReadSeqsReq, callOptions ...callopt.Option) (r *msg.SeqsInfoResp, err error)
	GetMsgByConversationIDs(ctx context.Context, Req *msg.GetMsgByConversationIDsReq, callOptions ...callopt.Option) (r *msg.GetMsgByConversationIDsResp, err error)
	GetConversationMaxSeq(ctx context.Context, Req *msg.GetConversationMaxSeqReq, callOptions ...callopt.Option) (r *msg.GetConversationMaxSeqResp, err error)
	PullMessageBySeqs(ctx context.Context, Req *sdkws.PullMessageBySeqsReq, callOptions ...callopt.Option) (r *sdkws.PullMessageBySeqsResp, err error)
	GetSeqMessage(ctx context.Context, Req *msg.GetSeqMessageReq, callOptions ...callopt.Option) (r *msg.GetSeqMessageResp, err error)
	SearchMessage(ctx context.Context, Req *msg.SearchMessageReq, callOptions ...callopt.Option) (r *msg.SearchMessageResp, err error)
	SendMsg(ctx context.Context, Req *msg.SendMsgReq, callOptions ...callopt.Option) (r *msg.SendMsgResp, err error)
	SendSimpleMsg(ctx context.Context, Req *msg.SendSimpleMsgReq, callOptions ...callopt.Option) (r *msg.SendSimpleMsgResp, err error)
	SetUserConversationsMinSeq(ctx context.Context, Req *msg.SetUserConversationsMinSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationsMinSeqResp, err error)
	ClearConversationsMsg(ctx context.Context, Req *msg.ClearConversationsMsgReq, callOptions ...callopt.Option) (r *msg.ClearConversationsMsgResp, err error)
	UserClearAllMsg(ctx context.Context, Req *msg.UserClearAllMsgReq, callOptions ...callopt.Option) (r *msg.UserClearAllMsgResp, err error)
	DeleteMsgs(ctx context.Context, Req *msg.DeleteMsgsReq, callOptions ...callopt.Option) (r *msg.DeleteMsgsResp, err error)
	DeleteMsgPhysicalBySeq(ctx context.Context, Req *msg.DeleteMsgPhysicalBySeqReq, callOptions ...callopt.Option) (r *msg.DeleteMsgPhysicalBySeqResp, err error)
	DeleteMsgPhysical(ctx context.Context, Req *msg.DeleteMsgPhysicalReq, callOptions ...callopt.Option) (r *msg.DeleteMsgPhysicalResp, err error)
	SetSendMsgStatus(ctx context.Context, Req *msg.SetSendMsgStatusReq, callOptions ...callopt.Option) (r *msg.SetSendMsgStatusResp, err error)
	GetSendMsgStatus(ctx context.Context, Req *msg.GetSendMsgStatusReq, callOptions ...callopt.Option) (r *msg.GetSendMsgStatusResp, err error)
	RevokeMsg(ctx context.Context, Req *msg.RevokeMsgReq, callOptions ...callopt.Option) (r *msg.RevokeMsgResp, err error)
	MarkMsgsAsRead(ctx context.Context, Req *msg.MarkMsgsAsReadReq, callOptions ...callopt.Option) (r *msg.MarkMsgsAsReadResp, err error)
	MarkConversationAsRead(ctx context.Context, Req *msg.MarkConversationAsReadReq, callOptions ...callopt.Option) (r *msg.MarkConversationAsReadResp, err error)
	SetConversationHasReadSeq(ctx context.Context, Req *msg.SetConversationHasReadSeqReq, callOptions ...callopt.Option) (r *msg.SetConversationHasReadSeqResp, err error)
	GetConversationsHasReadAndMaxSeq(ctx context.Context, Req *msg.GetConversationsHasReadAndMaxSeqReq, callOptions ...callopt.Option) (r *msg.GetConversationsHasReadAndMaxSeqResp, err error)
	GetActiveUser(ctx context.Context, Req *msg.GetActiveUserReq, callOptions ...callopt.Option) (r *msg.GetActiveUserResp, err error)
	GetActiveGroup(ctx context.Context, Req *msg.GetActiveGroupReq, callOptions ...callopt.Option) (r *msg.GetActiveGroupResp, err error)
	GetServerTime(ctx context.Context, Req *msg.GetServerTimeReq, callOptions ...callopt.Option) (r *msg.GetServerTimeResp, err error)
	ClearMsg(ctx context.Context, Req *msg.ClearMsgReq, callOptions ...callopt.Option) (r *msg.ClearMsgResp, err error)
	DestructMsgs(ctx context.Context, Req *msg.DestructMsgsReq, callOptions ...callopt.Option) (r *msg.DestructMsgsResp, err error)
	GetActiveConversation(ctx context.Context, Req *msg.GetActiveConversationReq, callOptions ...callopt.Option) (r *msg.GetActiveConversationResp, err error)
	SetUserConversationMaxSeq(ctx context.Context, Req *msg.SetUserConversationMaxSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationMaxSeqResp, err error)
	SetUserConversationMinSeq(ctx context.Context, Req *msg.SetUserConversationMinSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationMinSeqResp, err error)
	GetLastMessageSeqByTime(ctx context.Context, Req *msg.GetLastMessageSeqByTimeReq, callOptions ...callopt.Option) (r *msg.GetLastMessageSeqByTimeResp, err error)
	GetLastMessage(ctx context.Context, Req *msg.GetLastMessageReq, callOptions ...callopt.Option) (r *msg.GetLastMessageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) GetMaxSeq(ctx context.Context, Req *sdkws.GetMaxSeqReq, callOptions ...callopt.Option) (r *sdkws.GetMaxSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMaxSeq(ctx, Req)
}

func (p *kMessageServiceClient) GetMaxSeqs(ctx context.Context, Req *msg.GetMaxSeqsReq, callOptions ...callopt.Option) (r *msg.SeqsInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMaxSeqs(ctx, Req)
}

func (p *kMessageServiceClient) GetHasReadSeqs(ctx context.Context, Req *msg.GetHasReadSeqsReq, callOptions ...callopt.Option) (r *msg.SeqsInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHasReadSeqs(ctx, Req)
}

func (p *kMessageServiceClient) GetMsgByConversationIDs(ctx context.Context, Req *msg.GetMsgByConversationIDsReq, callOptions ...callopt.Option) (r *msg.GetMsgByConversationIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMsgByConversationIDs(ctx, Req)
}

func (p *kMessageServiceClient) GetConversationMaxSeq(ctx context.Context, Req *msg.GetConversationMaxSeqReq, callOptions ...callopt.Option) (r *msg.GetConversationMaxSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationMaxSeq(ctx, Req)
}

func (p *kMessageServiceClient) PullMessageBySeqs(ctx context.Context, Req *sdkws.PullMessageBySeqsReq, callOptions ...callopt.Option) (r *sdkws.PullMessageBySeqsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PullMessageBySeqs(ctx, Req)
}

func (p *kMessageServiceClient) GetSeqMessage(ctx context.Context, Req *msg.GetSeqMessageReq, callOptions ...callopt.Option) (r *msg.GetSeqMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSeqMessage(ctx, Req)
}

func (p *kMessageServiceClient) SearchMessage(ctx context.Context, Req *msg.SearchMessageReq, callOptions ...callopt.Option) (r *msg.SearchMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchMessage(ctx, Req)
}

func (p *kMessageServiceClient) SendMsg(ctx context.Context, Req *msg.SendMsgReq, callOptions ...callopt.Option) (r *msg.SendMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMsg(ctx, Req)
}

func (p *kMessageServiceClient) SendSimpleMsg(ctx context.Context, Req *msg.SendSimpleMsgReq, callOptions ...callopt.Option) (r *msg.SendSimpleMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSimpleMsg(ctx, Req)
}

func (p *kMessageServiceClient) SetUserConversationsMinSeq(ctx context.Context, Req *msg.SetUserConversationsMinSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationsMinSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetUserConversationsMinSeq(ctx, Req)
}

func (p *kMessageServiceClient) ClearConversationsMsg(ctx context.Context, Req *msg.ClearConversationsMsgReq, callOptions ...callopt.Option) (r *msg.ClearConversationsMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearConversationsMsg(ctx, Req)
}

func (p *kMessageServiceClient) UserClearAllMsg(ctx context.Context, Req *msg.UserClearAllMsgReq, callOptions ...callopt.Option) (r *msg.UserClearAllMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserClearAllMsg(ctx, Req)
}

func (p *kMessageServiceClient) DeleteMsgs(ctx context.Context, Req *msg.DeleteMsgsReq, callOptions ...callopt.Option) (r *msg.DeleteMsgsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMsgs(ctx, Req)
}

func (p *kMessageServiceClient) DeleteMsgPhysicalBySeq(ctx context.Context, Req *msg.DeleteMsgPhysicalBySeqReq, callOptions ...callopt.Option) (r *msg.DeleteMsgPhysicalBySeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMsgPhysicalBySeq(ctx, Req)
}

func (p *kMessageServiceClient) DeleteMsgPhysical(ctx context.Context, Req *msg.DeleteMsgPhysicalReq, callOptions ...callopt.Option) (r *msg.DeleteMsgPhysicalResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMsgPhysical(ctx, Req)
}

func (p *kMessageServiceClient) SetSendMsgStatus(ctx context.Context, Req *msg.SetSendMsgStatusReq, callOptions ...callopt.Option) (r *msg.SetSendMsgStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetSendMsgStatus(ctx, Req)
}

func (p *kMessageServiceClient) GetSendMsgStatus(ctx context.Context, Req *msg.GetSendMsgStatusReq, callOptions ...callopt.Option) (r *msg.GetSendMsgStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSendMsgStatus(ctx, Req)
}

func (p *kMessageServiceClient) RevokeMsg(ctx context.Context, Req *msg.RevokeMsgReq, callOptions ...callopt.Option) (r *msg.RevokeMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeMsg(ctx, Req)
}

func (p *kMessageServiceClient) MarkMsgsAsRead(ctx context.Context, Req *msg.MarkMsgsAsReadReq, callOptions ...callopt.Option) (r *msg.MarkMsgsAsReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkMsgsAsRead(ctx, Req)
}

func (p *kMessageServiceClient) MarkConversationAsRead(ctx context.Context, Req *msg.MarkConversationAsReadReq, callOptions ...callopt.Option) (r *msg.MarkConversationAsReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkConversationAsRead(ctx, Req)
}

func (p *kMessageServiceClient) SetConversationHasReadSeq(ctx context.Context, Req *msg.SetConversationHasReadSeqReq, callOptions ...callopt.Option) (r *msg.SetConversationHasReadSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetConversationHasReadSeq(ctx, Req)
}

func (p *kMessageServiceClient) GetConversationsHasReadAndMaxSeq(ctx context.Context, Req *msg.GetConversationsHasReadAndMaxSeqReq, callOptions ...callopt.Option) (r *msg.GetConversationsHasReadAndMaxSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationsHasReadAndMaxSeq(ctx, Req)
}

func (p *kMessageServiceClient) GetActiveUser(ctx context.Context, Req *msg.GetActiveUserReq, callOptions ...callopt.Option) (r *msg.GetActiveUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetActiveUser(ctx, Req)
}

func (p *kMessageServiceClient) GetActiveGroup(ctx context.Context, Req *msg.GetActiveGroupReq, callOptions ...callopt.Option) (r *msg.GetActiveGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetActiveGroup(ctx, Req)
}

func (p *kMessageServiceClient) GetServerTime(ctx context.Context, Req *msg.GetServerTimeReq, callOptions ...callopt.Option) (r *msg.GetServerTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetServerTime(ctx, Req)
}

func (p *kMessageServiceClient) ClearMsg(ctx context.Context, Req *msg.ClearMsgReq, callOptions ...callopt.Option) (r *msg.ClearMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearMsg(ctx, Req)
}

func (p *kMessageServiceClient) DestructMsgs(ctx context.Context, Req *msg.DestructMsgsReq, callOptions ...callopt.Option) (r *msg.DestructMsgsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DestructMsgs(ctx, Req)
}

func (p *kMessageServiceClient) GetActiveConversation(ctx context.Context, Req *msg.GetActiveConversationReq, callOptions ...callopt.Option) (r *msg.GetActiveConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetActiveConversation(ctx, Req)
}

func (p *kMessageServiceClient) SetUserConversationMaxSeq(ctx context.Context, Req *msg.SetUserConversationMaxSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationMaxSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetUserConversationMaxSeq(ctx, Req)
}

func (p *kMessageServiceClient) SetUserConversationMinSeq(ctx context.Context, Req *msg.SetUserConversationMinSeqReq, callOptions ...callopt.Option) (r *msg.SetUserConversationMinSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetUserConversationMinSeq(ctx, Req)
}

func (p *kMessageServiceClient) GetLastMessageSeqByTime(ctx context.Context, Req *msg.GetLastMessageSeqByTimeReq, callOptions ...callopt.Option) (r *msg.GetLastMessageSeqByTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastMessageSeqByTime(ctx, Req)
}

func (p *kMessageServiceClient) GetLastMessage(ctx context.Context, Req *msg.GetLastMessageReq, callOptions ...callopt.Option) (r *msg.GetLastMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastMessage(ctx, Req)
}
