// Code generated by Kitex v0.13.1. DO NOT EDIT.
package messageservice

import (
	server "github.com/cloudwego/kitex/server"
	msg "github.com/rhp-QE/roc-im-server/internal/kitex_gen/msg"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler msg.MessageService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler msg.MessageService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
