// 
// Author : Auto Generated
// Date   : 2025/01/XX
// Sequence Service - 会话序列号服务

syntax = "proto3";
package sequence;

import "sdkws.proto";

option go_package = "github.com/rhp-QE/roc-im-server/kitex_gen/sequence";

// 获取下一个序列号请求 (递增)
message GetNextSeqIncRequest {
  string id = 1; // 唯一ID
}

// 获取下一个序列号 (连续递增）
message GetNextSeqConsecutiveRequest {
  string id = 1; // 唯一ID
}

// 获取下一个序列号响应
message GetNextSeqResponse {
  int64 seq = 1;              // 生成的序列号
  string error_code = 2;      // 错误码
  string error_msg  = 3;       // 错误信息
}


// 序列号服务
service SequenceService {
  // 获取下一个序列号（递增）
  rpc GetNextSeqInc(GetNextSeqIncRequest) returns (GetNextSeqResponse);
  
  // 获取下一个序列号（连续递增）
  rpc GetNextSeqConsecutive(GetNextSeqConsecutiveRequest) returns (GetNextSeqResponse);
}

