// Code generated by Kitex v0.15.2. DO NOT EDIT.

package conversationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sdkws "github.com/rhp-QE/roc-im-server/kitex_gen/sdkws"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BatchChangeConversations(ctx context.Context, Req *sdkws.BatchChangeConversationsRequest, callOptions ...callopt.Option) (r *sdkws.BatchChangeConversationsResponse, err error)
	FetchUserRecentConvList(ctx context.Context, Req *sdkws.FetchUserRecentConvListRequest, callOptions ...callopt.Option) (r *sdkws.FetchUserRecentConvListResponse, err error)
	UserMessageIntegrityCheck(ctx context.Context, Req *sdkws.UserMessageIntegrityCheckRequest, callOptions ...callopt.Option) (r *sdkws.UserMessageIntegrityCheckResponse, err error)
	BatchGetConversations(ctx context.Context, Req *sdkws.BatchGetConversationsRequest, callOptions ...callopt.Option) (r *sdkws.BatchGetConversationsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConversationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConversationServiceClient struct {
	*kClient
}

func (p *kConversationServiceClient) BatchChangeConversations(ctx context.Context, Req *sdkws.BatchChangeConversationsRequest, callOptions ...callopt.Option) (r *sdkws.BatchChangeConversationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchChangeConversations(ctx, Req)
}

func (p *kConversationServiceClient) FetchUserRecentConvList(ctx context.Context, Req *sdkws.FetchUserRecentConvListRequest, callOptions ...callopt.Option) (r *sdkws.FetchUserRecentConvListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchUserRecentConvList(ctx, Req)
}

func (p *kConversationServiceClient) UserMessageIntegrityCheck(ctx context.Context, Req *sdkws.UserMessageIntegrityCheckRequest, callOptions ...callopt.Option) (r *sdkws.UserMessageIntegrityCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserMessageIntegrityCheck(ctx, Req)
}

func (p *kConversationServiceClient) BatchGetConversations(ctx context.Context, Req *sdkws.BatchGetConversationsRequest, callOptions ...callopt.Option) (r *sdkws.BatchGetConversationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetConversations(ctx, Req)
}
