// Code generated by Kitex v0.15.2. DO NOT EDIT.

package conversationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	conversation "github.com/rhp-QE/roc-im-server/kitex_gen/conversation"
	sdkws "github.com/rhp-QE/roc-im-server/kitex_gen/sdkws"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"BatchChangeConversations": kitex.NewMethodInfo(
		batchChangeConversationsHandler,
		newBatchChangeConversationsArgs,
		newBatchChangeConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FetchUserRecentConvList": kitex.NewMethodInfo(
		fetchUserRecentConvListHandler,
		newFetchUserRecentConvListArgs,
		newFetchUserRecentConvListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserMessageIntegrityCheck": kitex.NewMethodInfo(
		userMessageIntegrityCheckHandler,
		newUserMessageIntegrityCheckArgs,
		newUserMessageIntegrityCheckResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGetConversations": kitex.NewMethodInfo(
		batchGetConversationsHandler,
		newBatchGetConversationsArgs,
		newBatchGetConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	conversationServiceServiceInfo                = NewServiceInfo()
	conversationServiceServiceInfoForClient       = NewServiceInfoForClient()
	conversationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return conversationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConversationService"
	handlerType := (*conversation.ConversationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "conversation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func batchChangeConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.BatchChangeConversationsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).BatchChangeConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchChangeConversationsArgs:
		success, err := handler.(conversation.ConversationService).BatchChangeConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchChangeConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchChangeConversationsArgs() interface{} {
	return &BatchChangeConversationsArgs{}
}

func newBatchChangeConversationsResult() interface{} {
	return &BatchChangeConversationsResult{}
}

type BatchChangeConversationsArgs struct {
	Req *sdkws.BatchChangeConversationsRequest
}

func (p *BatchChangeConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchChangeConversationsArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchChangeConversationsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchChangeConversationsArgs_Req_DEFAULT *sdkws.BatchChangeConversationsRequest

func (p *BatchChangeConversationsArgs) GetReq() *sdkws.BatchChangeConversationsRequest {
	if !p.IsSetReq() {
		return BatchChangeConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchChangeConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchChangeConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchChangeConversationsResult struct {
	Success *sdkws.BatchChangeConversationsResponse
}

var BatchChangeConversationsResult_Success_DEFAULT *sdkws.BatchChangeConversationsResponse

func (p *BatchChangeConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchChangeConversationsResult) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchChangeConversationsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchChangeConversationsResult) GetSuccess() *sdkws.BatchChangeConversationsResponse {
	if !p.IsSetSuccess() {
		return BatchChangeConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchChangeConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.BatchChangeConversationsResponse)
}

func (p *BatchChangeConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchChangeConversationsResult) GetResult() interface{} {
	return p.Success
}

func fetchUserRecentConvListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchUserRecentConvListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).FetchUserRecentConvList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchUserRecentConvListArgs:
		success, err := handler.(conversation.ConversationService).FetchUserRecentConvList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchUserRecentConvListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchUserRecentConvListArgs() interface{} {
	return &FetchUserRecentConvListArgs{}
}

func newFetchUserRecentConvListResult() interface{} {
	return &FetchUserRecentConvListResult{}
}

type FetchUserRecentConvListArgs struct {
	Req *sdkws.FetchUserRecentConvListRequest
}

func (p *FetchUserRecentConvListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchUserRecentConvListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserRecentConvListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchUserRecentConvListArgs_Req_DEFAULT *sdkws.FetchUserRecentConvListRequest

func (p *FetchUserRecentConvListArgs) GetReq() *sdkws.FetchUserRecentConvListRequest {
	if !p.IsSetReq() {
		return FetchUserRecentConvListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchUserRecentConvListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchUserRecentConvListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchUserRecentConvListResult struct {
	Success *sdkws.FetchUserRecentConvListResponse
}

var FetchUserRecentConvListResult_Success_DEFAULT *sdkws.FetchUserRecentConvListResponse

func (p *FetchUserRecentConvListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchUserRecentConvListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserRecentConvListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchUserRecentConvListResult) GetSuccess() *sdkws.FetchUserRecentConvListResponse {
	if !p.IsSetSuccess() {
		return FetchUserRecentConvListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchUserRecentConvListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchUserRecentConvListResponse)
}

func (p *FetchUserRecentConvListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchUserRecentConvListResult) GetResult() interface{} {
	return p.Success
}

func userMessageIntegrityCheckHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.UserMessageIntegrityCheckRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).UserMessageIntegrityCheck(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserMessageIntegrityCheckArgs:
		success, err := handler.(conversation.ConversationService).UserMessageIntegrityCheck(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserMessageIntegrityCheckResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserMessageIntegrityCheckArgs() interface{} {
	return &UserMessageIntegrityCheckArgs{}
}

func newUserMessageIntegrityCheckResult() interface{} {
	return &UserMessageIntegrityCheckResult{}
}

type UserMessageIntegrityCheckArgs struct {
	Req *sdkws.UserMessageIntegrityCheckRequest
}

func (p *UserMessageIntegrityCheckArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserMessageIntegrityCheckArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.UserMessageIntegrityCheckRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserMessageIntegrityCheckArgs_Req_DEFAULT *sdkws.UserMessageIntegrityCheckRequest

func (p *UserMessageIntegrityCheckArgs) GetReq() *sdkws.UserMessageIntegrityCheckRequest {
	if !p.IsSetReq() {
		return UserMessageIntegrityCheckArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserMessageIntegrityCheckArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserMessageIntegrityCheckArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserMessageIntegrityCheckResult struct {
	Success *sdkws.UserMessageIntegrityCheckResponse
}

var UserMessageIntegrityCheckResult_Success_DEFAULT *sdkws.UserMessageIntegrityCheckResponse

func (p *UserMessageIntegrityCheckResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserMessageIntegrityCheckResult) Unmarshal(in []byte) error {
	msg := new(sdkws.UserMessageIntegrityCheckResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserMessageIntegrityCheckResult) GetSuccess() *sdkws.UserMessageIntegrityCheckResponse {
	if !p.IsSetSuccess() {
		return UserMessageIntegrityCheckResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserMessageIntegrityCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.UserMessageIntegrityCheckResponse)
}

func (p *UserMessageIntegrityCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserMessageIntegrityCheckResult) GetResult() interface{} {
	return p.Success
}

func batchGetConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.BatchGetConversationsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).BatchGetConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetConversationsArgs:
		success, err := handler.(conversation.ConversationService).BatchGetConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetConversationsArgs() interface{} {
	return &BatchGetConversationsArgs{}
}

func newBatchGetConversationsResult() interface{} {
	return &BatchGetConversationsResult{}
}

type BatchGetConversationsArgs struct {
	Req *sdkws.BatchGetConversationsRequest
}

func (p *BatchGetConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetConversationsArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchGetConversationsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetConversationsArgs_Req_DEFAULT *sdkws.BatchGetConversationsRequest

func (p *BatchGetConversationsArgs) GetReq() *sdkws.BatchGetConversationsRequest {
	if !p.IsSetReq() {
		return BatchGetConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetConversationsResult struct {
	Success *sdkws.BatchGetConversationsResponse
}

var BatchGetConversationsResult_Success_DEFAULT *sdkws.BatchGetConversationsResponse

func (p *BatchGetConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetConversationsResult) Unmarshal(in []byte) error {
	msg := new(sdkws.BatchGetConversationsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetConversationsResult) GetSuccess() *sdkws.BatchGetConversationsResponse {
	if !p.IsSetSuccess() {
		return BatchGetConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.BatchGetConversationsResponse)
}

func (p *BatchGetConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetConversationsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) BatchChangeConversations(ctx context.Context, Req *sdkws.BatchChangeConversationsRequest) (r *sdkws.BatchChangeConversationsResponse, err error) {
	var _args BatchChangeConversationsArgs
	_args.Req = Req
	var _result BatchChangeConversationsResult
	if err = p.c.Call(ctx, "BatchChangeConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchUserRecentConvList(ctx context.Context, Req *sdkws.FetchUserRecentConvListRequest) (r *sdkws.FetchUserRecentConvListResponse, err error) {
	var _args FetchUserRecentConvListArgs
	_args.Req = Req
	var _result FetchUserRecentConvListResult
	if err = p.c.Call(ctx, "FetchUserRecentConvList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserMessageIntegrityCheck(ctx context.Context, Req *sdkws.UserMessageIntegrityCheckRequest) (r *sdkws.UserMessageIntegrityCheckResponse, err error) {
	var _args UserMessageIntegrityCheckArgs
	_args.Req = Req
	var _result UserMessageIntegrityCheckResult
	if err = p.c.Call(ctx, "UserMessageIntegrityCheck", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetConversations(ctx context.Context, Req *sdkws.BatchGetConversationsRequest) (r *sdkws.BatchGetConversationsResponse, err error) {
	var _args BatchGetConversationsArgs
	_args.Req = Req
	var _result BatchGetConversationsResult
	if err = p.c.Call(ctx, "BatchGetConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
