// Code generated by Kitex v0.15.2. DO NOT EDIT.
package conversationservice

import (
	server "github.com/cloudwego/kitex/server"
	conversation "github.com/roc/roc-im-server/kitex_gen/conversation"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler conversation.ConversationService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler conversation.ConversationService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
