// Code generated by Kitex v0.13.1. DO NOT EDIT.

package pushservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	push "github.com/roc/roc-im-server/internal/kitex_gen/push"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushMsg(ctx context.Context, Req *push.PushMsgReq, callOptions ...callopt.Option) (r *push.PushMsgResp, err error)
	DelUserPushToken(ctx context.Context, Req *push.DelUserPushTokenReq, callOptions ...callopt.Option) (r *push.DelUserPushTokenResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPushServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPushServiceClient struct {
	*kClient
}

func (p *kPushServiceClient) PushMsg(ctx context.Context, Req *push.PushMsgReq, callOptions ...callopt.Option) (r *push.PushMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushMsg(ctx, Req)
}

func (p *kPushServiceClient) DelUserPushToken(ctx context.Context, Req *push.DelUserPushTokenReq, callOptions ...callopt.Option) (r *push.DelUserPushTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelUserPushToken(ctx, Req)
}
