// Code generated by Kitex v0.13.1. DO NOT EDIT.

package pushservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	push "github.com/rhp-QE/roc-im-server/internal/kitex_gen/push"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PushMsg": kitex.NewMethodInfo(
		pushMsgHandler,
		newPushMsgArgs,
		newPushMsgResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DelUserPushToken": kitex.NewMethodInfo(
		delUserPushTokenHandler,
		newDelUserPushTokenArgs,
		newDelUserPushTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	pushServiceServiceInfo                = NewServiceInfo()
	pushServiceServiceInfoForClient       = NewServiceInfoForClient()
	pushServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pushServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pushServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pushServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PushService"
	handlerType := (*push.PushService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "push",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func pushMsgHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(push.PushMsgReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(push.PushService).PushMsg(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PushMsgArgs:
		success, err := handler.(push.PushService).PushMsg(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PushMsgResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPushMsgArgs() interface{} {
	return &PushMsgArgs{}
}

func newPushMsgResult() interface{} {
	return &PushMsgResult{}
}

type PushMsgArgs struct {
	Req *push.PushMsgReq
}

func (p *PushMsgArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PushMsgArgs) Unmarshal(in []byte) error {
	msg := new(push.PushMsgReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PushMsgArgs_Req_DEFAULT *push.PushMsgReq

func (p *PushMsgArgs) GetReq() *push.PushMsgReq {
	if !p.IsSetReq() {
		return PushMsgArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PushMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushMsgArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PushMsgResult struct {
	Success *push.PushMsgResp
}

var PushMsgResult_Success_DEFAULT *push.PushMsgResp

func (p *PushMsgResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PushMsgResult) Unmarshal(in []byte) error {
	msg := new(push.PushMsgResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PushMsgResult) GetSuccess() *push.PushMsgResp {
	if !p.IsSetSuccess() {
		return PushMsgResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PushMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*push.PushMsgResp)
}

func (p *PushMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushMsgResult) GetResult() interface{} {
	return p.Success
}

func delUserPushTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(push.DelUserPushTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(push.PushService).DelUserPushToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DelUserPushTokenArgs:
		success, err := handler.(push.PushService).DelUserPushToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DelUserPushTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDelUserPushTokenArgs() interface{} {
	return &DelUserPushTokenArgs{}
}

func newDelUserPushTokenResult() interface{} {
	return &DelUserPushTokenResult{}
}

type DelUserPushTokenArgs struct {
	Req *push.DelUserPushTokenReq
}

func (p *DelUserPushTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DelUserPushTokenArgs) Unmarshal(in []byte) error {
	msg := new(push.DelUserPushTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DelUserPushTokenArgs_Req_DEFAULT *push.DelUserPushTokenReq

func (p *DelUserPushTokenArgs) GetReq() *push.DelUserPushTokenReq {
	if !p.IsSetReq() {
		return DelUserPushTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DelUserPushTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DelUserPushTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DelUserPushTokenResult struct {
	Success *push.DelUserPushTokenResp
}

var DelUserPushTokenResult_Success_DEFAULT *push.DelUserPushTokenResp

func (p *DelUserPushTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DelUserPushTokenResult) Unmarshal(in []byte) error {
	msg := new(push.DelUserPushTokenResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DelUserPushTokenResult) GetSuccess() *push.DelUserPushTokenResp {
	if !p.IsSetSuccess() {
		return DelUserPushTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DelUserPushTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*push.DelUserPushTokenResp)
}

func (p *DelUserPushTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DelUserPushTokenResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PushMsg(ctx context.Context, Req *push.PushMsgReq) (r *push.PushMsgResp, err error) {
	var _args PushMsgArgs
	_args.Req = Req
	var _result PushMsgResult
	if err = p.c.Call(ctx, "PushMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelUserPushToken(ctx context.Context, Req *push.DelUserPushTokenReq) (r *push.DelUserPushTokenResp, err error) {
	var _args DelUserPushTokenArgs
	_args.Req = Req
	var _result DelUserPushTokenResult
	if err = p.c.Call(ctx, "DelUserPushToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
