// Code generated by Kitex v0.13.1. DO NOT EDIT.

package conversationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sdkws "github.com/roc/roc-im-server/internal/kitex_gen/sdkws"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResp, err error)
	FetchUserMessageList(ctx context.Context, Req *sdkws.FetchUserMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchUserMessageListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConversationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConversationServiceClient struct {
	*kClient
}

func (p *kConversationServiceClient) FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchConvMessageList(ctx, Req)
}

func (p *kConversationServiceClient) FetchUserMessageList(ctx context.Context, Req *sdkws.FetchUserMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchUserMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchUserMessageList(ctx, Req)
}
