// Code generated by Kitex v0.13.1. DO NOT EDIT.

package conversationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	conversation "github.com/rhp-QE/roc-im-server/internal/kitex_gen/conversation"
	sdkws "github.com/rhp-QE/roc-im-server/internal/kitex_gen/sdkws"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetConversation(ctx context.Context, Req *conversation.GetConversationReq, callOptions ...callopt.Option) (r *conversation.GetConversationResp, err error)
	GetSortedConversationList(ctx context.Context, Req *conversation.GetSortedConversationListReq, callOptions ...callopt.Option) (r *conversation.GetSortedConversationListResp, err error)
	GetAllConversations(ctx context.Context, Req *conversation.GetAllConversationsReq, callOptions ...callopt.Option) (r *conversation.GetAllConversationsResp, err error)
	GetConversations(ctx context.Context, Req *conversation.GetConversationsReq, callOptions ...callopt.Option) (r *conversation.GetConversationsResp, err error)
	SetConversation(ctx context.Context, Req *conversation.SetConversationReq, callOptions ...callopt.Option) (r *conversation.SetConversationResp, err error)
	GetRecvMsgNotNotifyUserIDs(ctx context.Context, Req *conversation.GetRecvMsgNotNotifyUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetRecvMsgNotNotifyUserIDsResp, err error)
	CreateSingleChatConversations(ctx context.Context, Req *conversation.CreateSingleChatConversationsReq, callOptions ...callopt.Option) (r *conversation.CreateSingleChatConversationsResp, err error)
	CreateGroupChatConversations(ctx context.Context, Req *conversation.CreateGroupChatConversationsReq, callOptions ...callopt.Option) (r *conversation.CreateGroupChatConversationsResp, err error)
	SetConversationMaxSeq(ctx context.Context, Req *conversation.SetConversationMaxSeqReq, callOptions ...callopt.Option) (r *conversation.SetConversationMaxSeqResp, err error)
	SetConversationMinSeq(ctx context.Context, Req *conversation.SetConversationMinSeqReq, callOptions ...callopt.Option) (r *conversation.SetConversationMinSeqResp, err error)
	GetConversationIDs(ctx context.Context, Req *conversation.GetConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationIDsResp, err error)
	SetConversations(ctx context.Context, Req *conversation.SetConversationsReq, callOptions ...callopt.Option) (r *conversation.SetConversationsResp, err error)
	GetUserConversationIDsHash(ctx context.Context, Req *conversation.GetUserConversationIDsHashReq, callOptions ...callopt.Option) (r *conversation.GetUserConversationIDsHashResp, err error)
	GetConversationsByConversationID(ctx context.Context, Req *conversation.GetConversationsByConversationIDReq, callOptions ...callopt.Option) (r *conversation.GetConversationsByConversationIDResp, err error)
	GetConversationOfflinePushUserIDs(ctx context.Context, Req *conversation.GetConversationOfflinePushUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationOfflinePushUserIDsResp, err error)
	GetConversationNotReceiveMessageUserIDs(ctx context.Context, Req *conversation.GetConversationNotReceiveMessageUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationNotReceiveMessageUserIDsResp, err error)
	UpdateConversation(ctx context.Context, Req *conversation.UpdateConversationReq, callOptions ...callopt.Option) (r *conversation.UpdateConversationResp, err error)
	GetFullOwnerConversationIDs(ctx context.Context, Req *conversation.GetFullOwnerConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetFullOwnerConversationIDsResp, err error)
	GetIncrementalConversation(ctx context.Context, Req *conversation.GetIncrementalConversationReq, callOptions ...callopt.Option) (r *conversation.GetIncrementalConversationResp, err error)
	GetOwnerConversation(ctx context.Context, Req *conversation.GetOwnerConversationReq, callOptions ...callopt.Option) (r *conversation.GetOwnerConversationResp, err error)
	GetConversationsNeedClearMsg(ctx context.Context, Req *conversation.GetConversationsNeedClearMsgReq, callOptions ...callopt.Option) (r *conversation.GetConversationsNeedClearMsgResp, err error)
	GetNotNotifyConversationIDs(ctx context.Context, Req *conversation.GetNotNotifyConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetNotNotifyConversationIDsResp, err error)
	GetPinnedConversationIDs(ctx context.Context, Req *conversation.GetPinnedConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetPinnedConversationIDsResp, err error)
	ClearUserConversationMsg(ctx context.Context, Req *conversation.ClearUserConversationMsgReq, callOptions ...callopt.Option) (r *conversation.ClearUserConversationMsgResp, err error)
	UpdateConversationsByUser(ctx context.Context, Req *conversation.UpdateConversationsByUserReq, callOptions ...callopt.Option) (r *conversation.UpdateConversationsByUserResp, err error)
	FetchConvMessaegList(ctx context.Context, Req *sdkws.FetchConvMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResp, err error)
	FetchUserMessaegList(ctx context.Context, Req *sdkws.FetchUserMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchUserMessageListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConversationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConversationServiceClient struct {
	*kClient
}

func (p *kConversationServiceClient) GetConversation(ctx context.Context, Req *conversation.GetConversationReq, callOptions ...callopt.Option) (r *conversation.GetConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversation(ctx, Req)
}

func (p *kConversationServiceClient) GetSortedConversationList(ctx context.Context, Req *conversation.GetSortedConversationListReq, callOptions ...callopt.Option) (r *conversation.GetSortedConversationListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSortedConversationList(ctx, Req)
}

func (p *kConversationServiceClient) GetAllConversations(ctx context.Context, Req *conversation.GetAllConversationsReq, callOptions ...callopt.Option) (r *conversation.GetAllConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllConversations(ctx, Req)
}

func (p *kConversationServiceClient) GetConversations(ctx context.Context, Req *conversation.GetConversationsReq, callOptions ...callopt.Option) (r *conversation.GetConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversations(ctx, Req)
}

func (p *kConversationServiceClient) SetConversation(ctx context.Context, Req *conversation.SetConversationReq, callOptions ...callopt.Option) (r *conversation.SetConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetConversation(ctx, Req)
}

func (p *kConversationServiceClient) GetRecvMsgNotNotifyUserIDs(ctx context.Context, Req *conversation.GetRecvMsgNotNotifyUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetRecvMsgNotNotifyUserIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecvMsgNotNotifyUserIDs(ctx, Req)
}

func (p *kConversationServiceClient) CreateSingleChatConversations(ctx context.Context, Req *conversation.CreateSingleChatConversationsReq, callOptions ...callopt.Option) (r *conversation.CreateSingleChatConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSingleChatConversations(ctx, Req)
}

func (p *kConversationServiceClient) CreateGroupChatConversations(ctx context.Context, Req *conversation.CreateGroupChatConversationsReq, callOptions ...callopt.Option) (r *conversation.CreateGroupChatConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGroupChatConversations(ctx, Req)
}

func (p *kConversationServiceClient) SetConversationMaxSeq(ctx context.Context, Req *conversation.SetConversationMaxSeqReq, callOptions ...callopt.Option) (r *conversation.SetConversationMaxSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetConversationMaxSeq(ctx, Req)
}

func (p *kConversationServiceClient) SetConversationMinSeq(ctx context.Context, Req *conversation.SetConversationMinSeqReq, callOptions ...callopt.Option) (r *conversation.SetConversationMinSeqResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetConversationMinSeq(ctx, Req)
}

func (p *kConversationServiceClient) GetConversationIDs(ctx context.Context, Req *conversation.GetConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationIDs(ctx, Req)
}

func (p *kConversationServiceClient) SetConversations(ctx context.Context, Req *conversation.SetConversationsReq, callOptions ...callopt.Option) (r *conversation.SetConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetConversations(ctx, Req)
}

func (p *kConversationServiceClient) GetUserConversationIDsHash(ctx context.Context, Req *conversation.GetUserConversationIDsHashReq, callOptions ...callopt.Option) (r *conversation.GetUserConversationIDsHashResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserConversationIDsHash(ctx, Req)
}

func (p *kConversationServiceClient) GetConversationsByConversationID(ctx context.Context, Req *conversation.GetConversationsByConversationIDReq, callOptions ...callopt.Option) (r *conversation.GetConversationsByConversationIDResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationsByConversationID(ctx, Req)
}

func (p *kConversationServiceClient) GetConversationOfflinePushUserIDs(ctx context.Context, Req *conversation.GetConversationOfflinePushUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationOfflinePushUserIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationOfflinePushUserIDs(ctx, Req)
}

func (p *kConversationServiceClient) GetConversationNotReceiveMessageUserIDs(ctx context.Context, Req *conversation.GetConversationNotReceiveMessageUserIDsReq, callOptions ...callopt.Option) (r *conversation.GetConversationNotReceiveMessageUserIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationNotReceiveMessageUserIDs(ctx, Req)
}

func (p *kConversationServiceClient) UpdateConversation(ctx context.Context, Req *conversation.UpdateConversationReq, callOptions ...callopt.Option) (r *conversation.UpdateConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateConversation(ctx, Req)
}

func (p *kConversationServiceClient) GetFullOwnerConversationIDs(ctx context.Context, Req *conversation.GetFullOwnerConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetFullOwnerConversationIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFullOwnerConversationIDs(ctx, Req)
}

func (p *kConversationServiceClient) GetIncrementalConversation(ctx context.Context, Req *conversation.GetIncrementalConversationReq, callOptions ...callopt.Option) (r *conversation.GetIncrementalConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetIncrementalConversation(ctx, Req)
}

func (p *kConversationServiceClient) GetOwnerConversation(ctx context.Context, Req *conversation.GetOwnerConversationReq, callOptions ...callopt.Option) (r *conversation.GetOwnerConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOwnerConversation(ctx, Req)
}

func (p *kConversationServiceClient) GetConversationsNeedClearMsg(ctx context.Context, Req *conversation.GetConversationsNeedClearMsgReq, callOptions ...callopt.Option) (r *conversation.GetConversationsNeedClearMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationsNeedClearMsg(ctx, Req)
}

func (p *kConversationServiceClient) GetNotNotifyConversationIDs(ctx context.Context, Req *conversation.GetNotNotifyConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetNotNotifyConversationIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNotNotifyConversationIDs(ctx, Req)
}

func (p *kConversationServiceClient) GetPinnedConversationIDs(ctx context.Context, Req *conversation.GetPinnedConversationIDsReq, callOptions ...callopt.Option) (r *conversation.GetPinnedConversationIDsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPinnedConversationIDs(ctx, Req)
}

func (p *kConversationServiceClient) ClearUserConversationMsg(ctx context.Context, Req *conversation.ClearUserConversationMsgReq, callOptions ...callopt.Option) (r *conversation.ClearUserConversationMsgResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearUserConversationMsg(ctx, Req)
}

func (p *kConversationServiceClient) UpdateConversationsByUser(ctx context.Context, Req *conversation.UpdateConversationsByUserReq, callOptions ...callopt.Option) (r *conversation.UpdateConversationsByUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateConversationsByUser(ctx, Req)
}

func (p *kConversationServiceClient) FetchConvMessaegList(ctx context.Context, Req *sdkws.FetchConvMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchConvMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchConvMessaegList(ctx, Req)
}

func (p *kConversationServiceClient) FetchUserMessaegList(ctx context.Context, Req *sdkws.FetchUserMessageListReq, callOptions ...callopt.Option) (r *sdkws.FetchUserMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchUserMessaegList(ctx, Req)
}
