// Code generated by Kitex v0.13.1. DO NOT EDIT.

package conversationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	conversation "github.com/roc/roc-im-server/internal/kitex_gen/conversation"
	sdkws "github.com/roc/roc-im-server/internal/kitex_gen/sdkws"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"FetchConvMessageList": kitex.NewMethodInfo(
		fetchConvMessageListHandler,
		newFetchConvMessageListArgs,
		newFetchConvMessageListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FetchUserMessageList": kitex.NewMethodInfo(
		fetchUserMessageListHandler,
		newFetchUserMessageListArgs,
		newFetchUserMessageListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	conversationServiceServiceInfo                = NewServiceInfo()
	conversationServiceServiceInfoForClient       = NewServiceInfoForClient()
	conversationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return conversationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConversationService"
	handlerType := (*conversation.ConversationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "conversation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func fetchConvMessageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchConvMessageListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).FetchConvMessageList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchConvMessageListArgs:
		success, err := handler.(conversation.ConversationService).FetchConvMessageList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchConvMessageListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchConvMessageListArgs() interface{} {
	return &FetchConvMessageListArgs{}
}

func newFetchConvMessageListResult() interface{} {
	return &FetchConvMessageListResult{}
}

type FetchConvMessageListArgs struct {
	Req *sdkws.FetchConvMessageListReq
}

func (p *FetchConvMessageListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchConvMessageListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchConvMessageListArgs_Req_DEFAULT *sdkws.FetchConvMessageListReq

func (p *FetchConvMessageListArgs) GetReq() *sdkws.FetchConvMessageListReq {
	if !p.IsSetReq() {
		return FetchConvMessageListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchConvMessageListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchConvMessageListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchConvMessageListResult struct {
	Success *sdkws.FetchConvMessageListResp
}

var FetchConvMessageListResult_Success_DEFAULT *sdkws.FetchConvMessageListResp

func (p *FetchConvMessageListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchConvMessageListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchConvMessageListResult) GetSuccess() *sdkws.FetchConvMessageListResp {
	if !p.IsSetSuccess() {
		return FetchConvMessageListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchConvMessageListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchConvMessageListResp)
}

func (p *FetchConvMessageListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchConvMessageListResult) GetResult() interface{} {
	return p.Success
}

func fetchUserMessageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchUserMessageListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).FetchUserMessageList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchUserMessageListArgs:
		success, err := handler.(conversation.ConversationService).FetchUserMessageList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchUserMessageListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchUserMessageListArgs() interface{} {
	return &FetchUserMessageListArgs{}
}

func newFetchUserMessageListResult() interface{} {
	return &FetchUserMessageListResult{}
}

type FetchUserMessageListArgs struct {
	Req *sdkws.FetchUserMessageListReq
}

func (p *FetchUserMessageListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchUserMessageListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserMessageListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchUserMessageListArgs_Req_DEFAULT *sdkws.FetchUserMessageListReq

func (p *FetchUserMessageListArgs) GetReq() *sdkws.FetchUserMessageListReq {
	if !p.IsSetReq() {
		return FetchUserMessageListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchUserMessageListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchUserMessageListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchUserMessageListResult struct {
	Success *sdkws.FetchUserMessageListResp
}

var FetchUserMessageListResult_Success_DEFAULT *sdkws.FetchUserMessageListResp

func (p *FetchUserMessageListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchUserMessageListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserMessageListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchUserMessageListResult) GetSuccess() *sdkws.FetchUserMessageListResp {
	if !p.IsSetSuccess() {
		return FetchUserMessageListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchUserMessageListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchUserMessageListResp)
}

func (p *FetchUserMessageListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchUserMessageListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FetchConvMessageList(ctx context.Context, Req *sdkws.FetchConvMessageListReq) (r *sdkws.FetchConvMessageListResp, err error) {
	var _args FetchConvMessageListArgs
	_args.Req = Req
	var _result FetchConvMessageListResult
	if err = p.c.Call(ctx, "FetchConvMessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchUserMessageList(ctx context.Context, Req *sdkws.FetchUserMessageListReq) (r *sdkws.FetchUserMessageListResp, err error) {
	var _args FetchUserMessageListArgs
	_args.Req = Req
	var _result FetchUserMessageListResult
	if err = p.c.Call(ctx, "FetchUserMessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
