// Code generated by Kitex v0.13.1. DO NOT EDIT.

package conversationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	conversation "github.com/rhp-QE/roc-im-server/internal/kitex_gen/conversation"
	sdkws "github.com/rhp-QE/roc-im-server/internal/kitex_gen/sdkws"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetConversation": kitex.NewMethodInfo(
		getConversationHandler,
		newGetConversationArgs,
		newGetConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetSortedConversationList": kitex.NewMethodInfo(
		getSortedConversationListHandler,
		newGetSortedConversationListArgs,
		newGetSortedConversationListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetAllConversations": kitex.NewMethodInfo(
		getAllConversationsHandler,
		newGetAllConversationsArgs,
		newGetAllConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversations": kitex.NewMethodInfo(
		getConversationsHandler,
		newGetConversationsArgs,
		newGetConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SetConversation": kitex.NewMethodInfo(
		setConversationHandler,
		newSetConversationArgs,
		newSetConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecvMsgNotNotifyUserIDs": kitex.NewMethodInfo(
		getRecvMsgNotNotifyUserIDsHandler,
		newGetRecvMsgNotNotifyUserIDsArgs,
		newGetRecvMsgNotNotifyUserIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateSingleChatConversations": kitex.NewMethodInfo(
		createSingleChatConversationsHandler,
		newCreateSingleChatConversationsArgs,
		newCreateSingleChatConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateGroupChatConversations": kitex.NewMethodInfo(
		createGroupChatConversationsHandler,
		newCreateGroupChatConversationsArgs,
		newCreateGroupChatConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SetConversationMaxSeq": kitex.NewMethodInfo(
		setConversationMaxSeqHandler,
		newSetConversationMaxSeqArgs,
		newSetConversationMaxSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SetConversationMinSeq": kitex.NewMethodInfo(
		setConversationMinSeqHandler,
		newSetConversationMinSeqArgs,
		newSetConversationMinSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversationIDs": kitex.NewMethodInfo(
		getConversationIDsHandler,
		newGetConversationIDsArgs,
		newGetConversationIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SetConversations": kitex.NewMethodInfo(
		setConversationsHandler,
		newSetConversationsArgs,
		newSetConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserConversationIDsHash": kitex.NewMethodInfo(
		getUserConversationIDsHashHandler,
		newGetUserConversationIDsHashArgs,
		newGetUserConversationIDsHashResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversationsByConversationID": kitex.NewMethodInfo(
		getConversationsByConversationIDHandler,
		newGetConversationsByConversationIDArgs,
		newGetConversationsByConversationIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversationOfflinePushUserIDs": kitex.NewMethodInfo(
		getConversationOfflinePushUserIDsHandler,
		newGetConversationOfflinePushUserIDsArgs,
		newGetConversationOfflinePushUserIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversationNotReceiveMessageUserIDs": kitex.NewMethodInfo(
		getConversationNotReceiveMessageUserIDsHandler,
		newGetConversationNotReceiveMessageUserIDsArgs,
		newGetConversationNotReceiveMessageUserIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateConversation": kitex.NewMethodInfo(
		updateConversationHandler,
		newUpdateConversationArgs,
		newUpdateConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetFullOwnerConversationIDs": kitex.NewMethodInfo(
		getFullOwnerConversationIDsHandler,
		newGetFullOwnerConversationIDsArgs,
		newGetFullOwnerConversationIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetIncrementalConversation": kitex.NewMethodInfo(
		getIncrementalConversationHandler,
		newGetIncrementalConversationArgs,
		newGetIncrementalConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetOwnerConversation": kitex.NewMethodInfo(
		getOwnerConversationHandler,
		newGetOwnerConversationArgs,
		newGetOwnerConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetConversationsNeedClearMsg": kitex.NewMethodInfo(
		getConversationsNeedClearMsgHandler,
		newGetConversationsNeedClearMsgArgs,
		newGetConversationsNeedClearMsgResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetNotNotifyConversationIDs": kitex.NewMethodInfo(
		getNotNotifyConversationIDsHandler,
		newGetNotNotifyConversationIDsArgs,
		newGetNotNotifyConversationIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPinnedConversationIDs": kitex.NewMethodInfo(
		getPinnedConversationIDsHandler,
		newGetPinnedConversationIDsArgs,
		newGetPinnedConversationIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ClearUserConversationMsg": kitex.NewMethodInfo(
		clearUserConversationMsgHandler,
		newClearUserConversationMsgArgs,
		newClearUserConversationMsgResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateConversationsByUser": kitex.NewMethodInfo(
		updateConversationsByUserHandler,
		newUpdateConversationsByUserArgs,
		newUpdateConversationsByUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FetchConvMessaegList": kitex.NewMethodInfo(
		fetchConvMessaegListHandler,
		newFetchConvMessaegListArgs,
		newFetchConvMessaegListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FetchUserMessaegList": kitex.NewMethodInfo(
		fetchUserMessaegListHandler,
		newFetchUserMessaegListArgs,
		newFetchUserMessaegListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	conversationServiceServiceInfo                = NewServiceInfo()
	conversationServiceServiceInfoForClient       = NewServiceInfoForClient()
	conversationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return conversationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return conversationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConversationService"
	handlerType := (*conversation.ConversationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "conversation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func getConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationArgs:
		success, err := handler.(conversation.ConversationService).GetConversation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationArgs() interface{} {
	return &GetConversationArgs{}
}

func newGetConversationResult() interface{} {
	return &GetConversationResult{}
}

type GetConversationArgs struct {
	Req *conversation.GetConversationReq
}

func (p *GetConversationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationArgs_Req_DEFAULT *conversation.GetConversationReq

func (p *GetConversationArgs) GetReq() *conversation.GetConversationReq {
	if !p.IsSetReq() {
		return GetConversationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationResult struct {
	Success *conversation.GetConversationResp
}

var GetConversationResult_Success_DEFAULT *conversation.GetConversationResp

func (p *GetConversationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationResult) GetSuccess() *conversation.GetConversationResp {
	if !p.IsSetSuccess() {
		return GetConversationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationResp)
}

func (p *GetConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationResult) GetResult() interface{} {
	return p.Success
}

func getSortedConversationListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetSortedConversationListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetSortedConversationList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSortedConversationListArgs:
		success, err := handler.(conversation.ConversationService).GetSortedConversationList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSortedConversationListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSortedConversationListArgs() interface{} {
	return &GetSortedConversationListArgs{}
}

func newGetSortedConversationListResult() interface{} {
	return &GetSortedConversationListResult{}
}

type GetSortedConversationListArgs struct {
	Req *conversation.GetSortedConversationListReq
}

func (p *GetSortedConversationListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSortedConversationListArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetSortedConversationListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSortedConversationListArgs_Req_DEFAULT *conversation.GetSortedConversationListReq

func (p *GetSortedConversationListArgs) GetReq() *conversation.GetSortedConversationListReq {
	if !p.IsSetReq() {
		return GetSortedConversationListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSortedConversationListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSortedConversationListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSortedConversationListResult struct {
	Success *conversation.GetSortedConversationListResp
}

var GetSortedConversationListResult_Success_DEFAULT *conversation.GetSortedConversationListResp

func (p *GetSortedConversationListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSortedConversationListResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetSortedConversationListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSortedConversationListResult) GetSuccess() *conversation.GetSortedConversationListResp {
	if !p.IsSetSuccess() {
		return GetSortedConversationListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSortedConversationListResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetSortedConversationListResp)
}

func (p *GetSortedConversationListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSortedConversationListResult) GetResult() interface{} {
	return p.Success
}

func getAllConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetAllConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetAllConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetAllConversationsArgs:
		success, err := handler.(conversation.ConversationService).GetAllConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetAllConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetAllConversationsArgs() interface{} {
	return &GetAllConversationsArgs{}
}

func newGetAllConversationsResult() interface{} {
	return &GetAllConversationsResult{}
}

type GetAllConversationsArgs struct {
	Req *conversation.GetAllConversationsReq
}

func (p *GetAllConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetAllConversationsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetAllConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetAllConversationsArgs_Req_DEFAULT *conversation.GetAllConversationsReq

func (p *GetAllConversationsArgs) GetReq() *conversation.GetAllConversationsReq {
	if !p.IsSetReq() {
		return GetAllConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetAllConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetAllConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetAllConversationsResult struct {
	Success *conversation.GetAllConversationsResp
}

var GetAllConversationsResult_Success_DEFAULT *conversation.GetAllConversationsResp

func (p *GetAllConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetAllConversationsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetAllConversationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetAllConversationsResult) GetSuccess() *conversation.GetAllConversationsResp {
	if !p.IsSetSuccess() {
		return GetAllConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetAllConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetAllConversationsResp)
}

func (p *GetAllConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetAllConversationsResult) GetResult() interface{} {
	return p.Success
}

func getConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationsArgs:
		success, err := handler.(conversation.ConversationService).GetConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationsArgs() interface{} {
	return &GetConversationsArgs{}
}

func newGetConversationsResult() interface{} {
	return &GetConversationsResult{}
}

type GetConversationsArgs struct {
	Req *conversation.GetConversationsReq
}

func (p *GetConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationsArgs_Req_DEFAULT *conversation.GetConversationsReq

func (p *GetConversationsArgs) GetReq() *conversation.GetConversationsReq {
	if !p.IsSetReq() {
		return GetConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationsResult struct {
	Success *conversation.GetConversationsResp
}

var GetConversationsResult_Success_DEFAULT *conversation.GetConversationsResp

func (p *GetConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationsResult) GetSuccess() *conversation.GetConversationsResp {
	if !p.IsSetSuccess() {
		return GetConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationsResp)
}

func (p *GetConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationsResult) GetResult() interface{} {
	return p.Success
}

func setConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.SetConversationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).SetConversation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SetConversationArgs:
		success, err := handler.(conversation.ConversationService).SetConversation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SetConversationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSetConversationArgs() interface{} {
	return &SetConversationArgs{}
}

func newSetConversationResult() interface{} {
	return &SetConversationResult{}
}

type SetConversationArgs struct {
	Req *conversation.SetConversationReq
}

func (p *SetConversationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SetConversationArgs) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SetConversationArgs_Req_DEFAULT *conversation.SetConversationReq

func (p *SetConversationArgs) GetReq() *conversation.SetConversationReq {
	if !p.IsSetReq() {
		return SetConversationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SetConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SetConversationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SetConversationResult struct {
	Success *conversation.SetConversationResp
}

var SetConversationResult_Success_DEFAULT *conversation.SetConversationResp

func (p *SetConversationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SetConversationResult) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SetConversationResult) GetSuccess() *conversation.SetConversationResp {
	if !p.IsSetSuccess() {
		return SetConversationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SetConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.SetConversationResp)
}

func (p *SetConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetConversationResult) GetResult() interface{} {
	return p.Success
}

func getRecvMsgNotNotifyUserIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetRecvMsgNotNotifyUserIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetRecvMsgNotNotifyUserIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecvMsgNotNotifyUserIDsArgs:
		success, err := handler.(conversation.ConversationService).GetRecvMsgNotNotifyUserIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecvMsgNotNotifyUserIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecvMsgNotNotifyUserIDsArgs() interface{} {
	return &GetRecvMsgNotNotifyUserIDsArgs{}
}

func newGetRecvMsgNotNotifyUserIDsResult() interface{} {
	return &GetRecvMsgNotNotifyUserIDsResult{}
}

type GetRecvMsgNotNotifyUserIDsArgs struct {
	Req *conversation.GetRecvMsgNotNotifyUserIDsReq
}

func (p *GetRecvMsgNotNotifyUserIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecvMsgNotNotifyUserIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetRecvMsgNotNotifyUserIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecvMsgNotNotifyUserIDsArgs_Req_DEFAULT *conversation.GetRecvMsgNotNotifyUserIDsReq

func (p *GetRecvMsgNotNotifyUserIDsArgs) GetReq() *conversation.GetRecvMsgNotNotifyUserIDsReq {
	if !p.IsSetReq() {
		return GetRecvMsgNotNotifyUserIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecvMsgNotNotifyUserIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecvMsgNotNotifyUserIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecvMsgNotNotifyUserIDsResult struct {
	Success *conversation.GetRecvMsgNotNotifyUserIDsResp
}

var GetRecvMsgNotNotifyUserIDsResult_Success_DEFAULT *conversation.GetRecvMsgNotNotifyUserIDsResp

func (p *GetRecvMsgNotNotifyUserIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecvMsgNotNotifyUserIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetRecvMsgNotNotifyUserIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecvMsgNotNotifyUserIDsResult) GetSuccess() *conversation.GetRecvMsgNotNotifyUserIDsResp {
	if !p.IsSetSuccess() {
		return GetRecvMsgNotNotifyUserIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecvMsgNotNotifyUserIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetRecvMsgNotNotifyUserIDsResp)
}

func (p *GetRecvMsgNotNotifyUserIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecvMsgNotNotifyUserIDsResult) GetResult() interface{} {
	return p.Success
}

func createSingleChatConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.CreateSingleChatConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).CreateSingleChatConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateSingleChatConversationsArgs:
		success, err := handler.(conversation.ConversationService).CreateSingleChatConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateSingleChatConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateSingleChatConversationsArgs() interface{} {
	return &CreateSingleChatConversationsArgs{}
}

func newCreateSingleChatConversationsResult() interface{} {
	return &CreateSingleChatConversationsResult{}
}

type CreateSingleChatConversationsArgs struct {
	Req *conversation.CreateSingleChatConversationsReq
}

func (p *CreateSingleChatConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateSingleChatConversationsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.CreateSingleChatConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateSingleChatConversationsArgs_Req_DEFAULT *conversation.CreateSingleChatConversationsReq

func (p *CreateSingleChatConversationsArgs) GetReq() *conversation.CreateSingleChatConversationsReq {
	if !p.IsSetReq() {
		return CreateSingleChatConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateSingleChatConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateSingleChatConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateSingleChatConversationsResult struct {
	Success *conversation.CreateSingleChatConversationsResp
}

var CreateSingleChatConversationsResult_Success_DEFAULT *conversation.CreateSingleChatConversationsResp

func (p *CreateSingleChatConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateSingleChatConversationsResult) Unmarshal(in []byte) error {
	msg := new(conversation.CreateSingleChatConversationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateSingleChatConversationsResult) GetSuccess() *conversation.CreateSingleChatConversationsResp {
	if !p.IsSetSuccess() {
		return CreateSingleChatConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateSingleChatConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.CreateSingleChatConversationsResp)
}

func (p *CreateSingleChatConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateSingleChatConversationsResult) GetResult() interface{} {
	return p.Success
}

func createGroupChatConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.CreateGroupChatConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).CreateGroupChatConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateGroupChatConversationsArgs:
		success, err := handler.(conversation.ConversationService).CreateGroupChatConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateGroupChatConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateGroupChatConversationsArgs() interface{} {
	return &CreateGroupChatConversationsArgs{}
}

func newCreateGroupChatConversationsResult() interface{} {
	return &CreateGroupChatConversationsResult{}
}

type CreateGroupChatConversationsArgs struct {
	Req *conversation.CreateGroupChatConversationsReq
}

func (p *CreateGroupChatConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateGroupChatConversationsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.CreateGroupChatConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateGroupChatConversationsArgs_Req_DEFAULT *conversation.CreateGroupChatConversationsReq

func (p *CreateGroupChatConversationsArgs) GetReq() *conversation.CreateGroupChatConversationsReq {
	if !p.IsSetReq() {
		return CreateGroupChatConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateGroupChatConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateGroupChatConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateGroupChatConversationsResult struct {
	Success *conversation.CreateGroupChatConversationsResp
}

var CreateGroupChatConversationsResult_Success_DEFAULT *conversation.CreateGroupChatConversationsResp

func (p *CreateGroupChatConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateGroupChatConversationsResult) Unmarshal(in []byte) error {
	msg := new(conversation.CreateGroupChatConversationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateGroupChatConversationsResult) GetSuccess() *conversation.CreateGroupChatConversationsResp {
	if !p.IsSetSuccess() {
		return CreateGroupChatConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateGroupChatConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.CreateGroupChatConversationsResp)
}

func (p *CreateGroupChatConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateGroupChatConversationsResult) GetResult() interface{} {
	return p.Success
}

func setConversationMaxSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.SetConversationMaxSeqReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).SetConversationMaxSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SetConversationMaxSeqArgs:
		success, err := handler.(conversation.ConversationService).SetConversationMaxSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SetConversationMaxSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSetConversationMaxSeqArgs() interface{} {
	return &SetConversationMaxSeqArgs{}
}

func newSetConversationMaxSeqResult() interface{} {
	return &SetConversationMaxSeqResult{}
}

type SetConversationMaxSeqArgs struct {
	Req *conversation.SetConversationMaxSeqReq
}

func (p *SetConversationMaxSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SetConversationMaxSeqArgs) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationMaxSeqReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SetConversationMaxSeqArgs_Req_DEFAULT *conversation.SetConversationMaxSeqReq

func (p *SetConversationMaxSeqArgs) GetReq() *conversation.SetConversationMaxSeqReq {
	if !p.IsSetReq() {
		return SetConversationMaxSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SetConversationMaxSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SetConversationMaxSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SetConversationMaxSeqResult struct {
	Success *conversation.SetConversationMaxSeqResp
}

var SetConversationMaxSeqResult_Success_DEFAULT *conversation.SetConversationMaxSeqResp

func (p *SetConversationMaxSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SetConversationMaxSeqResult) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationMaxSeqResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SetConversationMaxSeqResult) GetSuccess() *conversation.SetConversationMaxSeqResp {
	if !p.IsSetSuccess() {
		return SetConversationMaxSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SetConversationMaxSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.SetConversationMaxSeqResp)
}

func (p *SetConversationMaxSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetConversationMaxSeqResult) GetResult() interface{} {
	return p.Success
}

func setConversationMinSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.SetConversationMinSeqReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).SetConversationMinSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SetConversationMinSeqArgs:
		success, err := handler.(conversation.ConversationService).SetConversationMinSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SetConversationMinSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSetConversationMinSeqArgs() interface{} {
	return &SetConversationMinSeqArgs{}
}

func newSetConversationMinSeqResult() interface{} {
	return &SetConversationMinSeqResult{}
}

type SetConversationMinSeqArgs struct {
	Req *conversation.SetConversationMinSeqReq
}

func (p *SetConversationMinSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SetConversationMinSeqArgs) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationMinSeqReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SetConversationMinSeqArgs_Req_DEFAULT *conversation.SetConversationMinSeqReq

func (p *SetConversationMinSeqArgs) GetReq() *conversation.SetConversationMinSeqReq {
	if !p.IsSetReq() {
		return SetConversationMinSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SetConversationMinSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SetConversationMinSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SetConversationMinSeqResult struct {
	Success *conversation.SetConversationMinSeqResp
}

var SetConversationMinSeqResult_Success_DEFAULT *conversation.SetConversationMinSeqResp

func (p *SetConversationMinSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SetConversationMinSeqResult) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationMinSeqResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SetConversationMinSeqResult) GetSuccess() *conversation.SetConversationMinSeqResp {
	if !p.IsSetSuccess() {
		return SetConversationMinSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SetConversationMinSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.SetConversationMinSeqResp)
}

func (p *SetConversationMinSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetConversationMinSeqResult) GetResult() interface{} {
	return p.Success
}

func getConversationIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversationIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationIDsArgs:
		success, err := handler.(conversation.ConversationService).GetConversationIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationIDsArgs() interface{} {
	return &GetConversationIDsArgs{}
}

func newGetConversationIDsResult() interface{} {
	return &GetConversationIDsResult{}
}

type GetConversationIDsArgs struct {
	Req *conversation.GetConversationIDsReq
}

func (p *GetConversationIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationIDsArgs_Req_DEFAULT *conversation.GetConversationIDsReq

func (p *GetConversationIDsArgs) GetReq() *conversation.GetConversationIDsReq {
	if !p.IsSetReq() {
		return GetConversationIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationIDsResult struct {
	Success *conversation.GetConversationIDsResp
}

var GetConversationIDsResult_Success_DEFAULT *conversation.GetConversationIDsResp

func (p *GetConversationIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationIDsResult) GetSuccess() *conversation.GetConversationIDsResp {
	if !p.IsSetSuccess() {
		return GetConversationIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationIDsResp)
}

func (p *GetConversationIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationIDsResult) GetResult() interface{} {
	return p.Success
}

func setConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.SetConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).SetConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SetConversationsArgs:
		success, err := handler.(conversation.ConversationService).SetConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SetConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSetConversationsArgs() interface{} {
	return &SetConversationsArgs{}
}

func newSetConversationsResult() interface{} {
	return &SetConversationsResult{}
}

type SetConversationsArgs struct {
	Req *conversation.SetConversationsReq
}

func (p *SetConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SetConversationsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SetConversationsArgs_Req_DEFAULT *conversation.SetConversationsReq

func (p *SetConversationsArgs) GetReq() *conversation.SetConversationsReq {
	if !p.IsSetReq() {
		return SetConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SetConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SetConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SetConversationsResult struct {
	Success *conversation.SetConversationsResp
}

var SetConversationsResult_Success_DEFAULT *conversation.SetConversationsResp

func (p *SetConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SetConversationsResult) Unmarshal(in []byte) error {
	msg := new(conversation.SetConversationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SetConversationsResult) GetSuccess() *conversation.SetConversationsResp {
	if !p.IsSetSuccess() {
		return SetConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SetConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.SetConversationsResp)
}

func (p *SetConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetConversationsResult) GetResult() interface{} {
	return p.Success
}

func getUserConversationIDsHashHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetUserConversationIDsHashReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetUserConversationIDsHash(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserConversationIDsHashArgs:
		success, err := handler.(conversation.ConversationService).GetUserConversationIDsHash(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserConversationIDsHashResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserConversationIDsHashArgs() interface{} {
	return &GetUserConversationIDsHashArgs{}
}

func newGetUserConversationIDsHashResult() interface{} {
	return &GetUserConversationIDsHashResult{}
}

type GetUserConversationIDsHashArgs struct {
	Req *conversation.GetUserConversationIDsHashReq
}

func (p *GetUserConversationIDsHashArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserConversationIDsHashArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetUserConversationIDsHashReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserConversationIDsHashArgs_Req_DEFAULT *conversation.GetUserConversationIDsHashReq

func (p *GetUserConversationIDsHashArgs) GetReq() *conversation.GetUserConversationIDsHashReq {
	if !p.IsSetReq() {
		return GetUserConversationIDsHashArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserConversationIDsHashArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserConversationIDsHashArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserConversationIDsHashResult struct {
	Success *conversation.GetUserConversationIDsHashResp
}

var GetUserConversationIDsHashResult_Success_DEFAULT *conversation.GetUserConversationIDsHashResp

func (p *GetUserConversationIDsHashResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserConversationIDsHashResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetUserConversationIDsHashResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserConversationIDsHashResult) GetSuccess() *conversation.GetUserConversationIDsHashResp {
	if !p.IsSetSuccess() {
		return GetUserConversationIDsHashResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserConversationIDsHashResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetUserConversationIDsHashResp)
}

func (p *GetUserConversationIDsHashResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserConversationIDsHashResult) GetResult() interface{} {
	return p.Success
}

func getConversationsByConversationIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationsByConversationIDReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversationsByConversationID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationsByConversationIDArgs:
		success, err := handler.(conversation.ConversationService).GetConversationsByConversationID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationsByConversationIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationsByConversationIDArgs() interface{} {
	return &GetConversationsByConversationIDArgs{}
}

func newGetConversationsByConversationIDResult() interface{} {
	return &GetConversationsByConversationIDResult{}
}

type GetConversationsByConversationIDArgs struct {
	Req *conversation.GetConversationsByConversationIDReq
}

func (p *GetConversationsByConversationIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationsByConversationIDArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsByConversationIDReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationsByConversationIDArgs_Req_DEFAULT *conversation.GetConversationsByConversationIDReq

func (p *GetConversationsByConversationIDArgs) GetReq() *conversation.GetConversationsByConversationIDReq {
	if !p.IsSetReq() {
		return GetConversationsByConversationIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationsByConversationIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationsByConversationIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationsByConversationIDResult struct {
	Success *conversation.GetConversationsByConversationIDResp
}

var GetConversationsByConversationIDResult_Success_DEFAULT *conversation.GetConversationsByConversationIDResp

func (p *GetConversationsByConversationIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationsByConversationIDResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsByConversationIDResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationsByConversationIDResult) GetSuccess() *conversation.GetConversationsByConversationIDResp {
	if !p.IsSetSuccess() {
		return GetConversationsByConversationIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationsByConversationIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationsByConversationIDResp)
}

func (p *GetConversationsByConversationIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationsByConversationIDResult) GetResult() interface{} {
	return p.Success
}

func getConversationOfflinePushUserIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationOfflinePushUserIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversationOfflinePushUserIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationOfflinePushUserIDsArgs:
		success, err := handler.(conversation.ConversationService).GetConversationOfflinePushUserIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationOfflinePushUserIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationOfflinePushUserIDsArgs() interface{} {
	return &GetConversationOfflinePushUserIDsArgs{}
}

func newGetConversationOfflinePushUserIDsResult() interface{} {
	return &GetConversationOfflinePushUserIDsResult{}
}

type GetConversationOfflinePushUserIDsArgs struct {
	Req *conversation.GetConversationOfflinePushUserIDsReq
}

func (p *GetConversationOfflinePushUserIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationOfflinePushUserIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationOfflinePushUserIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationOfflinePushUserIDsArgs_Req_DEFAULT *conversation.GetConversationOfflinePushUserIDsReq

func (p *GetConversationOfflinePushUserIDsArgs) GetReq() *conversation.GetConversationOfflinePushUserIDsReq {
	if !p.IsSetReq() {
		return GetConversationOfflinePushUserIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationOfflinePushUserIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationOfflinePushUserIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationOfflinePushUserIDsResult struct {
	Success *conversation.GetConversationOfflinePushUserIDsResp
}

var GetConversationOfflinePushUserIDsResult_Success_DEFAULT *conversation.GetConversationOfflinePushUserIDsResp

func (p *GetConversationOfflinePushUserIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationOfflinePushUserIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationOfflinePushUserIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationOfflinePushUserIDsResult) GetSuccess() *conversation.GetConversationOfflinePushUserIDsResp {
	if !p.IsSetSuccess() {
		return GetConversationOfflinePushUserIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationOfflinePushUserIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationOfflinePushUserIDsResp)
}

func (p *GetConversationOfflinePushUserIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationOfflinePushUserIDsResult) GetResult() interface{} {
	return p.Success
}

func getConversationNotReceiveMessageUserIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationNotReceiveMessageUserIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversationNotReceiveMessageUserIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationNotReceiveMessageUserIDsArgs:
		success, err := handler.(conversation.ConversationService).GetConversationNotReceiveMessageUserIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationNotReceiveMessageUserIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationNotReceiveMessageUserIDsArgs() interface{} {
	return &GetConversationNotReceiveMessageUserIDsArgs{}
}

func newGetConversationNotReceiveMessageUserIDsResult() interface{} {
	return &GetConversationNotReceiveMessageUserIDsResult{}
}

type GetConversationNotReceiveMessageUserIDsArgs struct {
	Req *conversation.GetConversationNotReceiveMessageUserIDsReq
}

func (p *GetConversationNotReceiveMessageUserIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationNotReceiveMessageUserIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationNotReceiveMessageUserIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationNotReceiveMessageUserIDsArgs_Req_DEFAULT *conversation.GetConversationNotReceiveMessageUserIDsReq

func (p *GetConversationNotReceiveMessageUserIDsArgs) GetReq() *conversation.GetConversationNotReceiveMessageUserIDsReq {
	if !p.IsSetReq() {
		return GetConversationNotReceiveMessageUserIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationNotReceiveMessageUserIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationNotReceiveMessageUserIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationNotReceiveMessageUserIDsResult struct {
	Success *conversation.GetConversationNotReceiveMessageUserIDsResp
}

var GetConversationNotReceiveMessageUserIDsResult_Success_DEFAULT *conversation.GetConversationNotReceiveMessageUserIDsResp

func (p *GetConversationNotReceiveMessageUserIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationNotReceiveMessageUserIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationNotReceiveMessageUserIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationNotReceiveMessageUserIDsResult) GetSuccess() *conversation.GetConversationNotReceiveMessageUserIDsResp {
	if !p.IsSetSuccess() {
		return GetConversationNotReceiveMessageUserIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationNotReceiveMessageUserIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationNotReceiveMessageUserIDsResp)
}

func (p *GetConversationNotReceiveMessageUserIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationNotReceiveMessageUserIDsResult) GetResult() interface{} {
	return p.Success
}

func updateConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.UpdateConversationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).UpdateConversation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateConversationArgs:
		success, err := handler.(conversation.ConversationService).UpdateConversation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateConversationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateConversationArgs() interface{} {
	return &UpdateConversationArgs{}
}

func newUpdateConversationResult() interface{} {
	return &UpdateConversationResult{}
}

type UpdateConversationArgs struct {
	Req *conversation.UpdateConversationReq
}

func (p *UpdateConversationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateConversationArgs) Unmarshal(in []byte) error {
	msg := new(conversation.UpdateConversationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateConversationArgs_Req_DEFAULT *conversation.UpdateConversationReq

func (p *UpdateConversationArgs) GetReq() *conversation.UpdateConversationReq {
	if !p.IsSetReq() {
		return UpdateConversationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateConversationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateConversationResult struct {
	Success *conversation.UpdateConversationResp
}

var UpdateConversationResult_Success_DEFAULT *conversation.UpdateConversationResp

func (p *UpdateConversationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateConversationResult) Unmarshal(in []byte) error {
	msg := new(conversation.UpdateConversationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateConversationResult) GetSuccess() *conversation.UpdateConversationResp {
	if !p.IsSetSuccess() {
		return UpdateConversationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.UpdateConversationResp)
}

func (p *UpdateConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateConversationResult) GetResult() interface{} {
	return p.Success
}

func getFullOwnerConversationIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetFullOwnerConversationIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetFullOwnerConversationIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFullOwnerConversationIDsArgs:
		success, err := handler.(conversation.ConversationService).GetFullOwnerConversationIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFullOwnerConversationIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFullOwnerConversationIDsArgs() interface{} {
	return &GetFullOwnerConversationIDsArgs{}
}

func newGetFullOwnerConversationIDsResult() interface{} {
	return &GetFullOwnerConversationIDsResult{}
}

type GetFullOwnerConversationIDsArgs struct {
	Req *conversation.GetFullOwnerConversationIDsReq
}

func (p *GetFullOwnerConversationIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFullOwnerConversationIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetFullOwnerConversationIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFullOwnerConversationIDsArgs_Req_DEFAULT *conversation.GetFullOwnerConversationIDsReq

func (p *GetFullOwnerConversationIDsArgs) GetReq() *conversation.GetFullOwnerConversationIDsReq {
	if !p.IsSetReq() {
		return GetFullOwnerConversationIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFullOwnerConversationIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFullOwnerConversationIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFullOwnerConversationIDsResult struct {
	Success *conversation.GetFullOwnerConversationIDsResp
}

var GetFullOwnerConversationIDsResult_Success_DEFAULT *conversation.GetFullOwnerConversationIDsResp

func (p *GetFullOwnerConversationIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFullOwnerConversationIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetFullOwnerConversationIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFullOwnerConversationIDsResult) GetSuccess() *conversation.GetFullOwnerConversationIDsResp {
	if !p.IsSetSuccess() {
		return GetFullOwnerConversationIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFullOwnerConversationIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetFullOwnerConversationIDsResp)
}

func (p *GetFullOwnerConversationIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFullOwnerConversationIDsResult) GetResult() interface{} {
	return p.Success
}

func getIncrementalConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetIncrementalConversationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetIncrementalConversation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetIncrementalConversationArgs:
		success, err := handler.(conversation.ConversationService).GetIncrementalConversation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetIncrementalConversationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetIncrementalConversationArgs() interface{} {
	return &GetIncrementalConversationArgs{}
}

func newGetIncrementalConversationResult() interface{} {
	return &GetIncrementalConversationResult{}
}

type GetIncrementalConversationArgs struct {
	Req *conversation.GetIncrementalConversationReq
}

func (p *GetIncrementalConversationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetIncrementalConversationArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetIncrementalConversationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetIncrementalConversationArgs_Req_DEFAULT *conversation.GetIncrementalConversationReq

func (p *GetIncrementalConversationArgs) GetReq() *conversation.GetIncrementalConversationReq {
	if !p.IsSetReq() {
		return GetIncrementalConversationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetIncrementalConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetIncrementalConversationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetIncrementalConversationResult struct {
	Success *conversation.GetIncrementalConversationResp
}

var GetIncrementalConversationResult_Success_DEFAULT *conversation.GetIncrementalConversationResp

func (p *GetIncrementalConversationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetIncrementalConversationResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetIncrementalConversationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetIncrementalConversationResult) GetSuccess() *conversation.GetIncrementalConversationResp {
	if !p.IsSetSuccess() {
		return GetIncrementalConversationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetIncrementalConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetIncrementalConversationResp)
}

func (p *GetIncrementalConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetIncrementalConversationResult) GetResult() interface{} {
	return p.Success
}

func getOwnerConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetOwnerConversationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetOwnerConversation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetOwnerConversationArgs:
		success, err := handler.(conversation.ConversationService).GetOwnerConversation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetOwnerConversationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetOwnerConversationArgs() interface{} {
	return &GetOwnerConversationArgs{}
}

func newGetOwnerConversationResult() interface{} {
	return &GetOwnerConversationResult{}
}

type GetOwnerConversationArgs struct {
	Req *conversation.GetOwnerConversationReq
}

func (p *GetOwnerConversationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetOwnerConversationArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetOwnerConversationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetOwnerConversationArgs_Req_DEFAULT *conversation.GetOwnerConversationReq

func (p *GetOwnerConversationArgs) GetReq() *conversation.GetOwnerConversationReq {
	if !p.IsSetReq() {
		return GetOwnerConversationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetOwnerConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetOwnerConversationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetOwnerConversationResult struct {
	Success *conversation.GetOwnerConversationResp
}

var GetOwnerConversationResult_Success_DEFAULT *conversation.GetOwnerConversationResp

func (p *GetOwnerConversationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetOwnerConversationResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetOwnerConversationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetOwnerConversationResult) GetSuccess() *conversation.GetOwnerConversationResp {
	if !p.IsSetSuccess() {
		return GetOwnerConversationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetOwnerConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetOwnerConversationResp)
}

func (p *GetOwnerConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetOwnerConversationResult) GetResult() interface{} {
	return p.Success
}

func getConversationsNeedClearMsgHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetConversationsNeedClearMsgReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetConversationsNeedClearMsg(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConversationsNeedClearMsgArgs:
		success, err := handler.(conversation.ConversationService).GetConversationsNeedClearMsg(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConversationsNeedClearMsgResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConversationsNeedClearMsgArgs() interface{} {
	return &GetConversationsNeedClearMsgArgs{}
}

func newGetConversationsNeedClearMsgResult() interface{} {
	return &GetConversationsNeedClearMsgResult{}
}

type GetConversationsNeedClearMsgArgs struct {
	Req *conversation.GetConversationsNeedClearMsgReq
}

func (p *GetConversationsNeedClearMsgArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConversationsNeedClearMsgArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsNeedClearMsgReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConversationsNeedClearMsgArgs_Req_DEFAULT *conversation.GetConversationsNeedClearMsgReq

func (p *GetConversationsNeedClearMsgArgs) GetReq() *conversation.GetConversationsNeedClearMsgReq {
	if !p.IsSetReq() {
		return GetConversationsNeedClearMsgArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConversationsNeedClearMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConversationsNeedClearMsgArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConversationsNeedClearMsgResult struct {
	Success *conversation.GetConversationsNeedClearMsgResp
}

var GetConversationsNeedClearMsgResult_Success_DEFAULT *conversation.GetConversationsNeedClearMsgResp

func (p *GetConversationsNeedClearMsgResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConversationsNeedClearMsgResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetConversationsNeedClearMsgResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConversationsNeedClearMsgResult) GetSuccess() *conversation.GetConversationsNeedClearMsgResp {
	if !p.IsSetSuccess() {
		return GetConversationsNeedClearMsgResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConversationsNeedClearMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetConversationsNeedClearMsgResp)
}

func (p *GetConversationsNeedClearMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConversationsNeedClearMsgResult) GetResult() interface{} {
	return p.Success
}

func getNotNotifyConversationIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetNotNotifyConversationIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetNotNotifyConversationIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetNotNotifyConversationIDsArgs:
		success, err := handler.(conversation.ConversationService).GetNotNotifyConversationIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetNotNotifyConversationIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetNotNotifyConversationIDsArgs() interface{} {
	return &GetNotNotifyConversationIDsArgs{}
}

func newGetNotNotifyConversationIDsResult() interface{} {
	return &GetNotNotifyConversationIDsResult{}
}

type GetNotNotifyConversationIDsArgs struct {
	Req *conversation.GetNotNotifyConversationIDsReq
}

func (p *GetNotNotifyConversationIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetNotNotifyConversationIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetNotNotifyConversationIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetNotNotifyConversationIDsArgs_Req_DEFAULT *conversation.GetNotNotifyConversationIDsReq

func (p *GetNotNotifyConversationIDsArgs) GetReq() *conversation.GetNotNotifyConversationIDsReq {
	if !p.IsSetReq() {
		return GetNotNotifyConversationIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetNotNotifyConversationIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetNotNotifyConversationIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetNotNotifyConversationIDsResult struct {
	Success *conversation.GetNotNotifyConversationIDsResp
}

var GetNotNotifyConversationIDsResult_Success_DEFAULT *conversation.GetNotNotifyConversationIDsResp

func (p *GetNotNotifyConversationIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetNotNotifyConversationIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetNotNotifyConversationIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetNotNotifyConversationIDsResult) GetSuccess() *conversation.GetNotNotifyConversationIDsResp {
	if !p.IsSetSuccess() {
		return GetNotNotifyConversationIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetNotNotifyConversationIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetNotNotifyConversationIDsResp)
}

func (p *GetNotNotifyConversationIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetNotNotifyConversationIDsResult) GetResult() interface{} {
	return p.Success
}

func getPinnedConversationIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.GetPinnedConversationIDsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).GetPinnedConversationIDs(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPinnedConversationIDsArgs:
		success, err := handler.(conversation.ConversationService).GetPinnedConversationIDs(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPinnedConversationIDsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPinnedConversationIDsArgs() interface{} {
	return &GetPinnedConversationIDsArgs{}
}

func newGetPinnedConversationIDsResult() interface{} {
	return &GetPinnedConversationIDsResult{}
}

type GetPinnedConversationIDsArgs struct {
	Req *conversation.GetPinnedConversationIDsReq
}

func (p *GetPinnedConversationIDsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPinnedConversationIDsArgs) Unmarshal(in []byte) error {
	msg := new(conversation.GetPinnedConversationIDsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPinnedConversationIDsArgs_Req_DEFAULT *conversation.GetPinnedConversationIDsReq

func (p *GetPinnedConversationIDsArgs) GetReq() *conversation.GetPinnedConversationIDsReq {
	if !p.IsSetReq() {
		return GetPinnedConversationIDsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPinnedConversationIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPinnedConversationIDsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPinnedConversationIDsResult struct {
	Success *conversation.GetPinnedConversationIDsResp
}

var GetPinnedConversationIDsResult_Success_DEFAULT *conversation.GetPinnedConversationIDsResp

func (p *GetPinnedConversationIDsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPinnedConversationIDsResult) Unmarshal(in []byte) error {
	msg := new(conversation.GetPinnedConversationIDsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPinnedConversationIDsResult) GetSuccess() *conversation.GetPinnedConversationIDsResp {
	if !p.IsSetSuccess() {
		return GetPinnedConversationIDsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPinnedConversationIDsResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.GetPinnedConversationIDsResp)
}

func (p *GetPinnedConversationIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPinnedConversationIDsResult) GetResult() interface{} {
	return p.Success
}

func clearUserConversationMsgHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.ClearUserConversationMsgReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).ClearUserConversationMsg(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ClearUserConversationMsgArgs:
		success, err := handler.(conversation.ConversationService).ClearUserConversationMsg(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ClearUserConversationMsgResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newClearUserConversationMsgArgs() interface{} {
	return &ClearUserConversationMsgArgs{}
}

func newClearUserConversationMsgResult() interface{} {
	return &ClearUserConversationMsgResult{}
}

type ClearUserConversationMsgArgs struct {
	Req *conversation.ClearUserConversationMsgReq
}

func (p *ClearUserConversationMsgArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ClearUserConversationMsgArgs) Unmarshal(in []byte) error {
	msg := new(conversation.ClearUserConversationMsgReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ClearUserConversationMsgArgs_Req_DEFAULT *conversation.ClearUserConversationMsgReq

func (p *ClearUserConversationMsgArgs) GetReq() *conversation.ClearUserConversationMsgReq {
	if !p.IsSetReq() {
		return ClearUserConversationMsgArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ClearUserConversationMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ClearUserConversationMsgArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ClearUserConversationMsgResult struct {
	Success *conversation.ClearUserConversationMsgResp
}

var ClearUserConversationMsgResult_Success_DEFAULT *conversation.ClearUserConversationMsgResp

func (p *ClearUserConversationMsgResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ClearUserConversationMsgResult) Unmarshal(in []byte) error {
	msg := new(conversation.ClearUserConversationMsgResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ClearUserConversationMsgResult) GetSuccess() *conversation.ClearUserConversationMsgResp {
	if !p.IsSetSuccess() {
		return ClearUserConversationMsgResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ClearUserConversationMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.ClearUserConversationMsgResp)
}

func (p *ClearUserConversationMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ClearUserConversationMsgResult) GetResult() interface{} {
	return p.Success
}

func updateConversationsByUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(conversation.UpdateConversationsByUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).UpdateConversationsByUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateConversationsByUserArgs:
		success, err := handler.(conversation.ConversationService).UpdateConversationsByUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateConversationsByUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateConversationsByUserArgs() interface{} {
	return &UpdateConversationsByUserArgs{}
}

func newUpdateConversationsByUserResult() interface{} {
	return &UpdateConversationsByUserResult{}
}

type UpdateConversationsByUserArgs struct {
	Req *conversation.UpdateConversationsByUserReq
}

func (p *UpdateConversationsByUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateConversationsByUserArgs) Unmarshal(in []byte) error {
	msg := new(conversation.UpdateConversationsByUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateConversationsByUserArgs_Req_DEFAULT *conversation.UpdateConversationsByUserReq

func (p *UpdateConversationsByUserArgs) GetReq() *conversation.UpdateConversationsByUserReq {
	if !p.IsSetReq() {
		return UpdateConversationsByUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateConversationsByUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateConversationsByUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateConversationsByUserResult struct {
	Success *conversation.UpdateConversationsByUserResp
}

var UpdateConversationsByUserResult_Success_DEFAULT *conversation.UpdateConversationsByUserResp

func (p *UpdateConversationsByUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateConversationsByUserResult) Unmarshal(in []byte) error {
	msg := new(conversation.UpdateConversationsByUserResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateConversationsByUserResult) GetSuccess() *conversation.UpdateConversationsByUserResp {
	if !p.IsSetSuccess() {
		return UpdateConversationsByUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateConversationsByUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*conversation.UpdateConversationsByUserResp)
}

func (p *UpdateConversationsByUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateConversationsByUserResult) GetResult() interface{} {
	return p.Success
}

func fetchConvMessaegListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchConvMessageListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).FetchConvMessaegList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchConvMessaegListArgs:
		success, err := handler.(conversation.ConversationService).FetchConvMessaegList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchConvMessaegListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchConvMessaegListArgs() interface{} {
	return &FetchConvMessaegListArgs{}
}

func newFetchConvMessaegListResult() interface{} {
	return &FetchConvMessaegListResult{}
}

type FetchConvMessaegListArgs struct {
	Req *sdkws.FetchConvMessageListReq
}

func (p *FetchConvMessaegListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchConvMessaegListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchConvMessaegListArgs_Req_DEFAULT *sdkws.FetchConvMessageListReq

func (p *FetchConvMessaegListArgs) GetReq() *sdkws.FetchConvMessageListReq {
	if !p.IsSetReq() {
		return FetchConvMessaegListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchConvMessaegListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchConvMessaegListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchConvMessaegListResult struct {
	Success *sdkws.FetchConvMessageListResp
}

var FetchConvMessaegListResult_Success_DEFAULT *sdkws.FetchConvMessageListResp

func (p *FetchConvMessaegListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchConvMessaegListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchConvMessageListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchConvMessaegListResult) GetSuccess() *sdkws.FetchConvMessageListResp {
	if !p.IsSetSuccess() {
		return FetchConvMessaegListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchConvMessaegListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchConvMessageListResp)
}

func (p *FetchConvMessaegListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchConvMessaegListResult) GetResult() interface{} {
	return p.Success
}

func fetchUserMessaegListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(sdkws.FetchUserMessageListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(conversation.ConversationService).FetchUserMessaegList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchUserMessaegListArgs:
		success, err := handler.(conversation.ConversationService).FetchUserMessaegList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchUserMessaegListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchUserMessaegListArgs() interface{} {
	return &FetchUserMessaegListArgs{}
}

func newFetchUserMessaegListResult() interface{} {
	return &FetchUserMessaegListResult{}
}

type FetchUserMessaegListArgs struct {
	Req *sdkws.FetchUserMessageListReq
}

func (p *FetchUserMessaegListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchUserMessaegListArgs) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserMessageListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchUserMessaegListArgs_Req_DEFAULT *sdkws.FetchUserMessageListReq

func (p *FetchUserMessaegListArgs) GetReq() *sdkws.FetchUserMessageListReq {
	if !p.IsSetReq() {
		return FetchUserMessaegListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchUserMessaegListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchUserMessaegListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchUserMessaegListResult struct {
	Success *sdkws.FetchUserMessageListResp
}

var FetchUserMessaegListResult_Success_DEFAULT *sdkws.FetchUserMessageListResp

func (p *FetchUserMessaegListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchUserMessaegListResult) Unmarshal(in []byte) error {
	msg := new(sdkws.FetchUserMessageListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchUserMessaegListResult) GetSuccess() *sdkws.FetchUserMessageListResp {
	if !p.IsSetSuccess() {
		return FetchUserMessaegListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchUserMessaegListResult) SetSuccess(x interface{}) {
	p.Success = x.(*sdkws.FetchUserMessageListResp)
}

func (p *FetchUserMessaegListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchUserMessaegListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetConversation(ctx context.Context, Req *conversation.GetConversationReq) (r *conversation.GetConversationResp, err error) {
	var _args GetConversationArgs
	_args.Req = Req
	var _result GetConversationResult
	if err = p.c.Call(ctx, "GetConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSortedConversationList(ctx context.Context, Req *conversation.GetSortedConversationListReq) (r *conversation.GetSortedConversationListResp, err error) {
	var _args GetSortedConversationListArgs
	_args.Req = Req
	var _result GetSortedConversationListResult
	if err = p.c.Call(ctx, "GetSortedConversationList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAllConversations(ctx context.Context, Req *conversation.GetAllConversationsReq) (r *conversation.GetAllConversationsResp, err error) {
	var _args GetAllConversationsArgs
	_args.Req = Req
	var _result GetAllConversationsResult
	if err = p.c.Call(ctx, "GetAllConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversations(ctx context.Context, Req *conversation.GetConversationsReq) (r *conversation.GetConversationsResp, err error) {
	var _args GetConversationsArgs
	_args.Req = Req
	var _result GetConversationsResult
	if err = p.c.Call(ctx, "GetConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetConversation(ctx context.Context, Req *conversation.SetConversationReq) (r *conversation.SetConversationResp, err error) {
	var _args SetConversationArgs
	_args.Req = Req
	var _result SetConversationResult
	if err = p.c.Call(ctx, "SetConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecvMsgNotNotifyUserIDs(ctx context.Context, Req *conversation.GetRecvMsgNotNotifyUserIDsReq) (r *conversation.GetRecvMsgNotNotifyUserIDsResp, err error) {
	var _args GetRecvMsgNotNotifyUserIDsArgs
	_args.Req = Req
	var _result GetRecvMsgNotNotifyUserIDsResult
	if err = p.c.Call(ctx, "GetRecvMsgNotNotifyUserIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSingleChatConversations(ctx context.Context, Req *conversation.CreateSingleChatConversationsReq) (r *conversation.CreateSingleChatConversationsResp, err error) {
	var _args CreateSingleChatConversationsArgs
	_args.Req = Req
	var _result CreateSingleChatConversationsResult
	if err = p.c.Call(ctx, "CreateSingleChatConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGroupChatConversations(ctx context.Context, Req *conversation.CreateGroupChatConversationsReq) (r *conversation.CreateGroupChatConversationsResp, err error) {
	var _args CreateGroupChatConversationsArgs
	_args.Req = Req
	var _result CreateGroupChatConversationsResult
	if err = p.c.Call(ctx, "CreateGroupChatConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetConversationMaxSeq(ctx context.Context, Req *conversation.SetConversationMaxSeqReq) (r *conversation.SetConversationMaxSeqResp, err error) {
	var _args SetConversationMaxSeqArgs
	_args.Req = Req
	var _result SetConversationMaxSeqResult
	if err = p.c.Call(ctx, "SetConversationMaxSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetConversationMinSeq(ctx context.Context, Req *conversation.SetConversationMinSeqReq) (r *conversation.SetConversationMinSeqResp, err error) {
	var _args SetConversationMinSeqArgs
	_args.Req = Req
	var _result SetConversationMinSeqResult
	if err = p.c.Call(ctx, "SetConversationMinSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationIDs(ctx context.Context, Req *conversation.GetConversationIDsReq) (r *conversation.GetConversationIDsResp, err error) {
	var _args GetConversationIDsArgs
	_args.Req = Req
	var _result GetConversationIDsResult
	if err = p.c.Call(ctx, "GetConversationIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetConversations(ctx context.Context, Req *conversation.SetConversationsReq) (r *conversation.SetConversationsResp, err error) {
	var _args SetConversationsArgs
	_args.Req = Req
	var _result SetConversationsResult
	if err = p.c.Call(ctx, "SetConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserConversationIDsHash(ctx context.Context, Req *conversation.GetUserConversationIDsHashReq) (r *conversation.GetUserConversationIDsHashResp, err error) {
	var _args GetUserConversationIDsHashArgs
	_args.Req = Req
	var _result GetUserConversationIDsHashResult
	if err = p.c.Call(ctx, "GetUserConversationIDsHash", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationsByConversationID(ctx context.Context, Req *conversation.GetConversationsByConversationIDReq) (r *conversation.GetConversationsByConversationIDResp, err error) {
	var _args GetConversationsByConversationIDArgs
	_args.Req = Req
	var _result GetConversationsByConversationIDResult
	if err = p.c.Call(ctx, "GetConversationsByConversationID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationOfflinePushUserIDs(ctx context.Context, Req *conversation.GetConversationOfflinePushUserIDsReq) (r *conversation.GetConversationOfflinePushUserIDsResp, err error) {
	var _args GetConversationOfflinePushUserIDsArgs
	_args.Req = Req
	var _result GetConversationOfflinePushUserIDsResult
	if err = p.c.Call(ctx, "GetConversationOfflinePushUserIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationNotReceiveMessageUserIDs(ctx context.Context, Req *conversation.GetConversationNotReceiveMessageUserIDsReq) (r *conversation.GetConversationNotReceiveMessageUserIDsResp, err error) {
	var _args GetConversationNotReceiveMessageUserIDsArgs
	_args.Req = Req
	var _result GetConversationNotReceiveMessageUserIDsResult
	if err = p.c.Call(ctx, "GetConversationNotReceiveMessageUserIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateConversation(ctx context.Context, Req *conversation.UpdateConversationReq) (r *conversation.UpdateConversationResp, err error) {
	var _args UpdateConversationArgs
	_args.Req = Req
	var _result UpdateConversationResult
	if err = p.c.Call(ctx, "UpdateConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFullOwnerConversationIDs(ctx context.Context, Req *conversation.GetFullOwnerConversationIDsReq) (r *conversation.GetFullOwnerConversationIDsResp, err error) {
	var _args GetFullOwnerConversationIDsArgs
	_args.Req = Req
	var _result GetFullOwnerConversationIDsResult
	if err = p.c.Call(ctx, "GetFullOwnerConversationIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIncrementalConversation(ctx context.Context, Req *conversation.GetIncrementalConversationReq) (r *conversation.GetIncrementalConversationResp, err error) {
	var _args GetIncrementalConversationArgs
	_args.Req = Req
	var _result GetIncrementalConversationResult
	if err = p.c.Call(ctx, "GetIncrementalConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOwnerConversation(ctx context.Context, Req *conversation.GetOwnerConversationReq) (r *conversation.GetOwnerConversationResp, err error) {
	var _args GetOwnerConversationArgs
	_args.Req = Req
	var _result GetOwnerConversationResult
	if err = p.c.Call(ctx, "GetOwnerConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationsNeedClearMsg(ctx context.Context, Req *conversation.GetConversationsNeedClearMsgReq) (r *conversation.GetConversationsNeedClearMsgResp, err error) {
	var _args GetConversationsNeedClearMsgArgs
	_args.Req = Req
	var _result GetConversationsNeedClearMsgResult
	if err = p.c.Call(ctx, "GetConversationsNeedClearMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNotNotifyConversationIDs(ctx context.Context, Req *conversation.GetNotNotifyConversationIDsReq) (r *conversation.GetNotNotifyConversationIDsResp, err error) {
	var _args GetNotNotifyConversationIDsArgs
	_args.Req = Req
	var _result GetNotNotifyConversationIDsResult
	if err = p.c.Call(ctx, "GetNotNotifyConversationIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPinnedConversationIDs(ctx context.Context, Req *conversation.GetPinnedConversationIDsReq) (r *conversation.GetPinnedConversationIDsResp, err error) {
	var _args GetPinnedConversationIDsArgs
	_args.Req = Req
	var _result GetPinnedConversationIDsResult
	if err = p.c.Call(ctx, "GetPinnedConversationIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ClearUserConversationMsg(ctx context.Context, Req *conversation.ClearUserConversationMsgReq) (r *conversation.ClearUserConversationMsgResp, err error) {
	var _args ClearUserConversationMsgArgs
	_args.Req = Req
	var _result ClearUserConversationMsgResult
	if err = p.c.Call(ctx, "ClearUserConversationMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateConversationsByUser(ctx context.Context, Req *conversation.UpdateConversationsByUserReq) (r *conversation.UpdateConversationsByUserResp, err error) {
	var _args UpdateConversationsByUserArgs
	_args.Req = Req
	var _result UpdateConversationsByUserResult
	if err = p.c.Call(ctx, "UpdateConversationsByUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchConvMessaegList(ctx context.Context, Req *sdkws.FetchConvMessageListReq) (r *sdkws.FetchConvMessageListResp, err error) {
	var _args FetchConvMessaegListArgs
	_args.Req = Req
	var _result FetchConvMessaegListResult
	if err = p.c.Call(ctx, "FetchConvMessaegList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchUserMessaegList(ctx context.Context, Req *sdkws.FetchUserMessageListReq) (r *sdkws.FetchUserMessageListResp, err error) {
	var _args FetchUserMessaegListArgs
	_args.Req = Req
	var _result FetchUserMessaegListResult
	if err = p.c.Call(ctx, "FetchUserMessaegList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
